using System;
using System.IO;
using System.Text;

using Allure.Xunit.Attributes;

using Mississippi.DocumentationGenerator.Output;


namespace Mississippi.DocumentationGenerator.L0Tests.Output;

/// <summary>
///     Unit tests for DocumentationWriter.
/// </summary>
[AllureParentSuite("Documentation Generator")]
[AllureSuite("Output")]
[AllureSubSuite("Documentation Writer")]
public sealed class DocumentationWriterTests : IDisposable
{
    private readonly string tempDir;
    private readonly DocumentationWriter writer;

    /// <summary>
    ///     Initializes a new instance of the <see cref="DocumentationWriterTests" /> class.
    /// </summary>
    public DocumentationWriterTests()
    {
        tempDir = Path.Combine(Path.GetTempPath(), $"DocumentationWriterTests_{Guid.NewGuid():N}");
        Directory.CreateDirectory(tempDir);
        writer = new DocumentationWriter();
    }

    /// <summary>
    ///     Disposes the test resources.
    /// </summary>
    public void Dispose()
    {
        if (Directory.Exists(tempDir))
        {
            Directory.Delete(tempDir, recursive: true);
        }
    }

    /// <summary>
    ///     Tests that PrepareOutputDirectory creates directory if not exists.
    /// </summary>
    [Fact(DisplayName = "PrepareOutputDirectory creates directory if not exists")]
    public void PrepareOutputDirectoryCreatesDirectoryIfNotExists()
    {
        // Arrange
        string outputDir = Path.Combine(tempDir, "output");

        // Act
        writer.PrepareOutputDirectory(outputDir);

        // Assert
        Assert.True(Directory.Exists(outputDir));
    }

    /// <summary>
    ///     Tests that PrepareOutputDirectory clears existing directory.
    /// </summary>
    [Fact(DisplayName = "PrepareOutputDirectory clears existing directory")]
    public void PrepareOutputDirectoryClearsExistingDirectory()
    {
        // Arrange
        string outputDir = Path.Combine(tempDir, "output");
        Directory.CreateDirectory(outputDir);
        File.WriteAllText(Path.Combine(outputDir, "existing.txt"), "content");

        // Act
        writer.PrepareOutputDirectory(outputDir);

        // Assert
        Assert.True(Directory.Exists(outputDir));
        Assert.Empty(Directory.GetFiles(outputDir));
    }

    /// <summary>
    ///     Tests that WriteMdxFile creates file with correct structure.
    /// </summary>
    [Fact(DisplayName = "WriteMdxFile creates file with correct structure")]
    public void WriteMdxFileCreatesFileWithCorrectStructure()
    {
        // Arrange
        string filePath = Path.Combine(tempDir, "test.mdx");
        string title = "Test Title";
        string content = "Test content";

        // Act
        writer.WriteMdxFile(filePath, title, content, 1);

        // Assert
        Assert.True(File.Exists(filePath));
        string fileContent = File.ReadAllText(filePath);
        Assert.Contains("sidebar_position: 1", fileContent, StringComparison.Ordinal);
        Assert.Contains("# Test Title", fileContent, StringComparison.Ordinal);
        Assert.Contains("Test content", fileContent, StringComparison.Ordinal);
    }

    /// <summary>
    ///     Tests that WriteMdxFile includes auto-generated notice by default.
    /// </summary>
    [Fact(DisplayName = "WriteMdxFile includes auto-generated notice by default")]
    public void WriteMdxFileIncludesAutoGeneratedNoticeByDefault()
    {
        // Arrange
        string filePath = Path.Combine(tempDir, "test.mdx");

        // Act
        writer.WriteMdxFile(filePath, "Title", "Content", 1);

        // Assert
        string fileContent = File.ReadAllText(filePath);
        Assert.Contains(":::note Auto-generated", fileContent, StringComparison.Ordinal);
    }

    /// <summary>
    ///     Tests that WriteMdxFile excludes notice when specified.
    /// </summary>
    [Fact(DisplayName = "WriteMdxFile excludes notice when specified")]
    public void WriteMdxFileExcludesNoticeWhenSpecified()
    {
        // Arrange
        string filePath = Path.Combine(tempDir, "test.mdx");

        // Act
        writer.WriteMdxFile(filePath, "Title", "Content", 1, includeAutoGeneratedNotice: false);

        // Assert
        string fileContent = File.ReadAllText(filePath);
        Assert.DoesNotContain(":::note Auto-generated", fileContent, StringComparison.Ordinal);
    }

    /// <summary>
    ///     Tests that WriteCategoryJson creates valid JSON file.
    /// </summary>
    [Fact(DisplayName = "WriteCategoryJson creates valid JSON file")]
    public void WriteCategoryJsonCreatesValidJsonFile()
    {
        // Arrange
        string categoryDir = Path.Combine(tempDir, "category");

        // Act
        writer.WriteCategoryJson(categoryDir, "Test Category", 5);

        // Assert
        string jsonPath = Path.Combine(categoryDir, "_category_.json");
        Assert.True(File.Exists(jsonPath));
        string jsonContent = File.ReadAllText(jsonPath);
        Assert.Contains("\"label\": \"Test Category\"", jsonContent, StringComparison.Ordinal);
        Assert.Contains("\"position\": 5", jsonContent, StringComparison.Ordinal);
    }

    /// <summary>
    ///     Tests that WriteCategoryJson creates directory if needed.
    /// </summary>
    [Fact(DisplayName = "WriteCategoryJson creates directory if needed")]
    public void WriteCategoryJsonCreatesDirectoryIfNeeded()
    {
        // Arrange
        string categoryDir = Path.Combine(tempDir, "new-category");

        // Act
        writer.WriteCategoryJson(categoryDir, "New Category", 1);

        // Assert
        Assert.True(Directory.Exists(categoryDir));
        Assert.True(File.Exists(Path.Combine(categoryDir, "_category_.json")));
    }
}
