# PR Labeler configuration
# See https://github.com/actions/labeler for documentation
#
# Label naming conventions:
#   area:<module>     - Framework modules (filter PRs by subsystem)
#   sample:<name>     - Sample applications
#   semver:<type>     - Version bump type (parsed from PR title suffix)
#   documentation     - Docs changes (matches GitHub default label)
#   ci/cd             - Build/workflow changes
#   tests-only        - PRs that only modify tests
#   generators        - Source generator projects
#   build-config      - MSBuild/versioning infrastructure
#
# Semver labels (applied by pr-labeler.yml based on PR title):
#   semver:breaking   - Title ends with +semver: breaking
#   semver:feature    - Title ends with +semver: feature
#   semver:fix        - Title ends with +semver: fix
#   semver:skip       - Title ends with +semver: skip
#
# See: .github/instructions/pr-description.instructions.md

# =============================================================================
# MODULE LABELS (area:*)
# =============================================================================

'area:Inlet':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/Inlet*/**/!(*lock.json)'
          - 'tests/Inlet*/**/!(*lock.json)'

'area:Reservoir':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/Reservoir*/**/!(*lock.json)'
          - 'tests/Reservoir*/**/!(*lock.json)'

'area:Aqueduct':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/Aqueduct*/**/!(*lock.json)'
          - 'tests/Aqueduct*/**/!(*lock.json)'

'area:EventSourcing':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/EventSourcing*/**/!(*lock.json)'
          - 'tests/EventSourcing*/**/!(*lock.json)'

'area:Refraction':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/Refraction*/**/!(*lock.json)'
          - 'tests/Refraction*/**/!(*lock.json)'

'area:Common':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/Common*/**/!(*lock.json)'
          - 'tests/Common*/**/!(*lock.json)'

'area:SDK':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/Sdk*/**/!(*lock.json)'
          - 'tests/Sdk*/**/!(*lock.json)'

# =============================================================================
# CROSS-CUTTING LABELS
# =============================================================================

# Source generators deserve special attention (complex, affects DX)
generators:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/Inlet.*.Generators/**/!(*lock.json)'
          - 'src/Inlet.Generators.*/**/!(*lock.json)'
          - 'tests/Inlet.*.Generators*/**/!(*lock.json)'

# Storage provider-specific changes
'storage:Cosmos':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**/*.Cosmos/**/!(*lock.json)'
          - 'tests/**/*.Cosmos*/**/!(*lock.json)'

# Orleans runtime and silo/grain changes
'runtime:Orleans':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**/*.Grains/**/!(*lock.json)'
          - 'src/**/*.Silo/**/!(*lock.json)'
          - 'tests/**/*.Grains*/**/!(*lock.json)'
          - 'tests/**/*.Silo*/**/!(*lock.json)'

# Blazor UI and pages
'ui:Blazor':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**/*.Blazor/**/!(*lock.json)'
          - 'src/**/*.Pages/**/!(*lock.json)'
          - 'tests/**/*.Blazor*/**/!(*lock.json)'
          - 'tests/**/*.Pages*/**/!(*lock.json)'

# Public API surface
api:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**/*.Api/**/!(*lock.json)'
          - 'tests/**/*.Api*/**/!(*lock.json)'

# Matches GitHub's default 'documentation' label
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**/!(*lock.json)'
          - '.github/instructions/**/!(*lock.json)'
          - '**/*.md'

# CI/CD and automation
'ci/cd':
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**/!(*lock.json)'
          - '.github/actions/**/!(*lock.json)'
          - '.github/linters/**/!(*lock.json)'
          - 'eng/**/!(*lock.json)'
          - '*.ps1'
          - '.cursor/rules/**/!(*lock.json)'

# Root build configuration (high-impact, review carefully)
build-config:
  - changed-files:
      - any-glob-to-any-file:
          - 'Directory.Build.props'
          - 'Directory.Packages.props'
          - 'global.json'
          - '*.slnx'
          - 'stryker-config.json'
          - 'GitVersion.yml'

# PRs that ONLY touch tests (no src changes) - lower risk
tests-only:
  - all:
      - changed-files:
          - any-glob-to-any-file: 'tests/**/!(*lock.json)'
          - all-globs-to-all-files: '!src/**'

# =============================================================================
# SAMPLE LABELS (sample:*)
# =============================================================================

'sample:Spring':
  - changed-files:
      - any-glob-to-any-file:
          - 'samples/Spring/**/!(*lock.json)'

'sample:Crescent':
  - changed-files:
      - any-glob-to-any-file:
          - 'samples/Crescent/**/!(*lock.json)'
