using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using Mississippi.Inlet.Generators.Core.Emit;


namespace Mississippi.Inlet.Silo.Generators;

/// <summary>
///     Generates saga status reducers for projections marked with [GenerateSagaStatusReducers].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SagaStatusReducersGenerator : IIncrementalGenerator
{
    private const string GenerateSagaStatusReducersAttributeFullName =
        "Mississippi.Inlet.Generators.Abstractions.GenerateSagaStatusReducersAttribute";

    private const string GeneratorName = "SagaStatusReducersGenerator";

    private static void FindProjectionsInNamespace(
        INamespaceSymbol namespaceSymbol,
        INamedTypeSymbol attributeSymbol,
        List<ProjectionInfo> projections
    )
    {
        foreach (INamedTypeSymbol typeSymbol in namespaceSymbol.GetTypeMembers()
                     .Where(typeSymbol => typeSymbol.GetAttributes()
                         .Any(attr => SymbolEqualityComparer.Default.Equals(attr.AttributeClass, attributeSymbol))))
        {
            projections.Add(new(typeSymbol, typeSymbol.Name, typeSymbol.ContainingNamespace.ToDisplayString()));
        }

        foreach (INamespaceSymbol childNamespace in namespaceSymbol.GetNamespaceMembers())
        {
            FindProjectionsInNamespace(childNamespace, attributeSymbol, projections);
        }
    }

    private static string GenerateReducerClass(
        string projectionTypeName,
        string className,
        string eventTypeName,
        string reduceBody
    )
    {
        SourceBuilder sb = new();
        sb.AppendSummary($"Reduces <see cref=\"{eventTypeName}\" /> into saga status state.");
        sb.AppendGeneratedCodeAttribute(GeneratorName);
        sb.AppendLine($"internal sealed class {className} : EventReducerBase<{eventTypeName}, {projectionTypeName}>");
        sb.OpenBrace();
        sb.AppendLine("/// <inheritdoc />");
        sb.AppendLine($"protected override {projectionTypeName} ReduceCore(");
        sb.IncreaseIndent();
        sb.AppendLine($"{projectionTypeName} state,");
        sb.AppendLine($"{eventTypeName} eventData");
        sb.DecreaseIndent();
        sb.AppendLine(")");
        sb.OpenBrace();
        sb.AppendLine("ArgumentNullException.ThrowIfNull(eventData);");
        sb.AppendLine("return state with");
        sb.OpenBrace();
        sb.AppendLine(reduceBody);
        sb.CloseBrace();
        sb.AppendLine(";");
        sb.CloseBrace();
        sb.CloseBrace();
        return sb.ToString();
    }

    private static void GenerateReducers(
        SourceProductionContext context,
        ProjectionInfo projection
    )
    {
        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing("System");
        sb.AppendUsing("Mississippi.EventSourcing.Reducers.Abstractions");
        sb.AppendUsing("Mississippi.EventSourcing.Sagas.Abstractions");
        sb.AppendFileScopedNamespace(projection.Namespace + ".Reducers");
        sb.AppendLine();
        const string sagaStartedBody = "Phase = SagaPhase.Running,\n" +
                                       "StartedAt = eventData.StartedAt,\n" +
                                       "LastCompletedStepIndex = -1,\n" +
                                       "ErrorCode = null,\n" +
                                       "ErrorMessage = null,\n" +
                                       "CompletedAt = null,";
        const string sagaStepCompletedBody = "LastCompletedStepIndex = eventData.StepIndex,";
        const string sagaStepFailedBody =
            "ErrorCode = eventData.ErrorCode,\n" + "ErrorMessage = eventData.ErrorMessage,";
        const string sagaFailedBody = "Phase = SagaPhase.Failed,\n" +
                                      "ErrorCode = eventData.ErrorCode,\n" +
                                      "ErrorMessage = eventData.ErrorMessage,\n" +
                                      "CompletedAt = eventData.FailedAt,";
        const string sagaCompletedBody = "Phase = SagaPhase.Completed,\n" + "CompletedAt = eventData.CompletedAt,";
        const string sagaCompensatingBody = "Phase = SagaPhase.Compensating,";
        const string sagaCompensatedBody = "Phase = SagaPhase.Compensated,\n" + "CompletedAt = eventData.CompletedAt,";
        List<string> reducerBlocks =
        [
            GenerateReducerClass(projection.TypeName, "SagaStartedStatusReducer", "SagaStartedEvent", sagaStartedBody),
            GenerateReducerClass(
                projection.TypeName,
                "SagaStepCompletedStatusReducer",
                "SagaStepCompleted",
                sagaStepCompletedBody),
            GenerateReducerClass(
                projection.TypeName,
                "SagaStepFailedStatusReducer",
                "SagaStepFailed",
                sagaStepFailedBody),
            GenerateReducerClass(projection.TypeName, "SagaFailedStatusReducer", "SagaFailed", sagaFailedBody),
            GenerateReducerClass(projection.TypeName, "SagaCompletedStatusReducer", "SagaCompleted", sagaCompletedBody),
            GenerateReducerClass(
                projection.TypeName,
                "SagaCompensatingStatusReducer",
                "SagaCompensating",
                sagaCompensatingBody),
            GenerateReducerClass(
                projection.TypeName,
                "SagaCompensatedStatusReducer",
                "SagaCompensated",
                sagaCompensatedBody),
        ];
        foreach (string reducerBlock in reducerBlocks)
        {
            sb.AppendLine(reducerBlock);
            sb.AppendLine();
        }

        context.AddSource(
            $"{projection.TypeName}.SagaStatusReducers.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static List<ProjectionInfo> GetProjectionsFromCompilation(
        Compilation compilation
    )
    {
        List<ProjectionInfo> projections = new();
        INamedTypeSymbol? attributeSymbol = compilation.GetTypeByMetadataName(
            GenerateSagaStatusReducersAttributeFullName);
        if (attributeSymbol is null)
        {
            return projections;
        }

        FindProjectionsInNamespace(compilation.Assembly.GlobalNamespace, attributeSymbol, projections);
        return projections;
    }

    /// <inheritdoc />
    public void Initialize(
        IncrementalGeneratorInitializationContext context
    )
    {
        IncrementalValueProvider<List<ProjectionInfo>> projectionsProvider = context.CompilationProvider.Select((
            compilation,
            _
        ) => GetProjectionsFromCompilation(compilation));
        context.RegisterSourceOutput(
            projectionsProvider,
            static (
                spc,
                projections
            ) =>
            {
                foreach (ProjectionInfo projection in projections)
                {
                    GenerateReducers(spc, projection);
                }
            });
    }

    private sealed class ProjectionInfo
    {
        public ProjectionInfo(
            INamedTypeSymbol typeSymbol,
            string typeName,
            string @namespace
        )
        {
            TypeSymbol = typeSymbol;
            TypeName = typeName;
            Namespace = @namespace;
        }

        public string Namespace { get; }

        public string TypeName { get; }

        public INamedTypeSymbol TypeSymbol { get; }
    }
}