using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using Mississippi.Inlet.Generators.Core.Emit;


namespace Mississippi.Inlet.Runtime.Generators;

/// <summary>
///     Generates saga status reducers for projections marked with [GenerateSagaStatusReducers].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SagaStatusReducersGenerator : IIncrementalGenerator
{
    private const string GenerateSagaStatusReducersAttributeFullName =
        "Mississippi.Inlet.Generators.Abstractions.GenerateSagaStatusReducersAttribute";

    private const string GeneratorName = "SagaStatusReducersGenerator";

    private static void FindProjectionsInNamespace(
        INamespaceSymbol namespaceSymbol,
        INamedTypeSymbol attributeSymbol,
        List<ProjectionInfo> projections
    )
    {
        foreach (INamedTypeSymbol typeSymbol in namespaceSymbol.GetTypeMembers()
                     .Where(typeSymbol => typeSymbol.GetAttributes()
                         .Any(attr => SymbolEqualityComparer.Default.Equals(attr.AttributeClass, attributeSymbol))))
        {
            projections.Add(new(typeSymbol, typeSymbol.Name, typeSymbol.ContainingNamespace.ToDisplayString()));
        }

        foreach (INamespaceSymbol childNamespace in namespaceSymbol.GetNamespaceMembers())
        {
            FindProjectionsInNamespace(childNamespace, attributeSymbol, projections);
        }
    }

    private static string GenerateReducerClass(
        string projectionTypeName,
        string className,
        string eventTypeName,
        string reduceBody
    )
    {
        SourceBuilder sb = new();
        sb.AppendSummary($"Reduces <see cref=\"{eventTypeName}\" /> into saga status state.");
        sb.AppendGeneratedCodeAttribute(GeneratorName);
        sb.AppendLine($"internal sealed class {className} : EventReducerBase<{eventTypeName}, {projectionTypeName}>");
        sb.OpenBrace();
        sb.AppendLine("/// <inheritdoc />");
        sb.AppendLine($"protected override {projectionTypeName} ReduceCore(");
        sb.IncreaseIndent();
        sb.AppendLine($"{projectionTypeName} state,");
        sb.AppendLine($"{eventTypeName} eventData");
        sb.DecreaseIndent();
        sb.AppendLine(")");
        sb.OpenBrace();
        sb.AppendLine("ArgumentNullException.ThrowIfNull(eventData);");
        sb.AppendLine("return state with");
        sb.OpenBrace();
        sb.AppendLine(reduceBody);
        sb.CloseBrace();
        sb.AppendLine(";");
        sb.CloseBrace();
        sb.CloseBrace();
        return sb.ToString();
    }

    private static string JoinAssignments(
        IEnumerable<string> assignments
    ) => string.Join("\n", assignments.Select(static assignment => assignment + ","));

    private static void AddAssignment(
        List<string> assignments,
        bool condition,
        string assignment
    )
    {
        if (condition)
        {
            assignments.Add(assignment);
        }
    }

    private static void GenerateReducers(
        SourceProductionContext context,
        ProjectionInfo projection
    )
    {
        ProjectionProperties properties = ProjectionProperties.Create(projection.TypeSymbol);
        const string AutomaticPendingDisposition = "ResumeDisposition = SagaResumeDisposition.AutomaticPending";
        const string ManualInterventionDisposition =
            "ResumeDisposition = SagaResumeDisposition.ManualInterventionRequired";
        const string StartedDisposition =
            "ResumeDisposition = eventData.RecoveryMode is SagaRecoveryMode.ManualOnly ? SagaResumeDisposition.ManualInterventionRequired : SagaResumeDisposition.AutomaticPending";
        const string TerminalDisposition = "ResumeDisposition = SagaResumeDisposition.Terminal";
        const string ManualAwarePendingDisposition =
            "ResumeDisposition = state.RecoveryMode is SagaRecoveryMode.ManualOnly ? SagaResumeDisposition.ManualInterventionRequired : SagaResumeDisposition.AutomaticPending";
        string pendingDisposition = properties.RecoveryMode
            ? ManualAwarePendingDisposition
            : AutomaticPendingDisposition;
        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing("System");
        sb.AppendUsing("Mississippi.Tributary.Abstractions");
        sb.AppendUsing("Mississippi.DomainModeling.Abstractions");
        sb.AppendFileScopedNamespace(projection.Namespace + ".Reducers");
        sb.AppendLine();
        List<string> sagaStartedAssignments =
        [
            "Phase = SagaPhase.Running",
            "StartedAt = eventData.StartedAt",
            "LastCompletedStepIndex = -1",
            "ErrorCode = null",
            "ErrorMessage = null",
            "CompletedAt = null",
        ];
        AddAssignment(sagaStartedAssignments, properties.RecoveryMode, "RecoveryMode = eventData.RecoveryMode");
        AddAssignment(sagaStartedAssignments, properties.RecoveryProfile, "RecoveryProfile = eventData.RecoveryProfile");
        AddAssignment(sagaStartedAssignments, properties.PendingDirection, "PendingDirection = SagaExecutionDirection.Forward");
        AddAssignment(sagaStartedAssignments, properties.PendingStepIndex, "PendingStepIndex = 0");
        AddAssignment(sagaStartedAssignments, properties.PendingStepName, "PendingStepName = null");
        AddAssignment(sagaStartedAssignments, properties.BlockedReason, "BlockedReason = null");
        AddAssignment(sagaStartedAssignments, properties.LastResumeSource, "LastResumeSource = null");
        AddAssignment(sagaStartedAssignments, properties.LastResumeAttemptedAt, "LastResumeAttemptedAt = null");
        AddAssignment(sagaStartedAssignments, properties.AutomaticAttemptCount, "AutomaticAttemptCount = 0");
        AddAssignment(sagaStartedAssignments, properties.ResumeDisposition, StartedDisposition);

        List<string> sagaStepCompletedAssignments = ["LastCompletedStepIndex = eventData.StepIndex"];
        AddAssignment(sagaStepCompletedAssignments, properties.PendingDirection, "PendingDirection = SagaExecutionDirection.Forward");
        AddAssignment(sagaStepCompletedAssignments, properties.PendingStepIndex, "PendingStepIndex = eventData.StepIndex + 1");
        AddAssignment(sagaStepCompletedAssignments, properties.PendingStepName, "PendingStepName = null");
        AddAssignment(sagaStepCompletedAssignments, properties.BlockedReason, "BlockedReason = null");
        AddAssignment(sagaStepCompletedAssignments, properties.ResumeDisposition, pendingDisposition);

        List<string> sagaStepFailedAssignments =
        [
            "ErrorCode = eventData.ErrorCode",
            "ErrorMessage = eventData.ErrorMessage",
        ];
        AddAssignment(sagaStepFailedAssignments, properties.PendingDirection, "PendingDirection = SagaExecutionDirection.Forward");
        AddAssignment(sagaStepFailedAssignments, properties.PendingStepIndex, "PendingStepIndex = eventData.StepIndex");
        AddAssignment(sagaStepFailedAssignments, properties.PendingStepName, "PendingStepName = eventData.StepName");
        AddAssignment(sagaStepFailedAssignments, properties.BlockedReason, "BlockedReason = null");
        AddAssignment(sagaStepFailedAssignments, properties.ResumeDisposition, pendingDisposition);

        List<string> sagaFailedAssignments =
        [
            "Phase = SagaPhase.Failed",
            "ErrorCode = eventData.ErrorCode",
            "ErrorMessage = eventData.ErrorMessage",
            "CompletedAt = eventData.FailedAt",
        ];
        AddAssignment(sagaFailedAssignments, properties.PendingDirection, "PendingDirection = null");
        AddAssignment(sagaFailedAssignments, properties.PendingStepIndex, "PendingStepIndex = null");
        AddAssignment(sagaFailedAssignments, properties.PendingStepName, "PendingStepName = null");
        AddAssignment(sagaFailedAssignments, properties.BlockedReason, "BlockedReason = null");
        AddAssignment(sagaFailedAssignments, properties.ResumeDisposition, TerminalDisposition);

        List<string> sagaCompletedAssignments =
        [
            "Phase = SagaPhase.Completed",
            "CompletedAt = eventData.CompletedAt",
        ];
        AddAssignment(sagaCompletedAssignments, properties.PendingDirection, "PendingDirection = null");
        AddAssignment(sagaCompletedAssignments, properties.PendingStepIndex, "PendingStepIndex = null");
        AddAssignment(sagaCompletedAssignments, properties.PendingStepName, "PendingStepName = null");
        AddAssignment(sagaCompletedAssignments, properties.BlockedReason, "BlockedReason = null");
        AddAssignment(sagaCompletedAssignments, properties.ResumeDisposition, TerminalDisposition);

        List<string> sagaCompensatingAssignments = ["Phase = SagaPhase.Compensating"];
        AddAssignment(
            sagaCompensatingAssignments,
            properties.PendingDirection,
            "PendingDirection = SagaExecutionDirection.Compensation");
        AddAssignment(sagaCompensatingAssignments, properties.PendingStepIndex, "PendingStepIndex = eventData.FromStepIndex");
        AddAssignment(sagaCompensatingAssignments, properties.PendingStepName, "PendingStepName = null");
        AddAssignment(sagaCompensatingAssignments, properties.BlockedReason, "BlockedReason = null");
        AddAssignment(sagaCompensatingAssignments, properties.ResumeDisposition, pendingDisposition);

        List<string> sagaCompensatedAssignments =
        [
            "Phase = SagaPhase.Compensated",
            "CompletedAt = eventData.CompletedAt",
        ];
        AddAssignment(sagaCompensatedAssignments, properties.PendingDirection, "PendingDirection = null");
        AddAssignment(sagaCompensatedAssignments, properties.PendingStepIndex, "PendingStepIndex = null");
        AddAssignment(sagaCompensatedAssignments, properties.PendingStepName, "PendingStepName = null");
        AddAssignment(sagaCompensatedAssignments, properties.BlockedReason, "BlockedReason = null");
        AddAssignment(sagaCompensatedAssignments, properties.ResumeDisposition, TerminalDisposition);

        List<string> reducerBlocks =
        [
            GenerateReducerClass(
                projection.TypeName,
                "SagaStartedStatusReducer",
                "SagaStartedEvent",
                JoinAssignments(sagaStartedAssignments)),
            GenerateReducerClass(
                projection.TypeName,
                "SagaStepCompletedStatusReducer",
                "SagaStepCompleted",
                JoinAssignments(sagaStepCompletedAssignments)),
            GenerateReducerClass(
                projection.TypeName,
                "SagaStepFailedStatusReducer",
                "SagaStepFailed",
                JoinAssignments(sagaStepFailedAssignments)),
            GenerateReducerClass(
                projection.TypeName,
                "SagaFailedStatusReducer",
                "SagaFailed",
                JoinAssignments(sagaFailedAssignments)),
            GenerateReducerClass(
                projection.TypeName,
                "SagaCompletedStatusReducer",
                "SagaCompleted",
                JoinAssignments(sagaCompletedAssignments)),
            GenerateReducerClass(
                projection.TypeName,
                "SagaCompensatingStatusReducer",
                "SagaCompensating",
                JoinAssignments(sagaCompensatingAssignments)),
            GenerateReducerClass(
                projection.TypeName,
                "SagaCompensatedStatusReducer",
                "SagaCompensated",
                JoinAssignments(sagaCompensatedAssignments)),
        ];
        if (properties.HasRecoveryMetadata)
        {
            List<string> executionStartedAssignments = [];
            AddAssignment(executionStartedAssignments, properties.PendingDirection, "PendingDirection = eventData.Direction");
            AddAssignment(executionStartedAssignments, properties.PendingStepIndex, "PendingStepIndex = eventData.StepIndex");
            AddAssignment(executionStartedAssignments, properties.PendingStepName, "PendingStepName = eventData.StepName");
            AddAssignment(executionStartedAssignments, properties.BlockedReason, "BlockedReason = null");
            AddAssignment(
                executionStartedAssignments,
                properties.LastResumeSource,
                "LastResumeSource = eventData.Source is not SagaResumeSource.Initial ? eventData.Source : state.LastResumeSource");
            AddAssignment(
                executionStartedAssignments,
                properties.LastResumeAttemptedAt,
                "LastResumeAttemptedAt = eventData.Source is not SagaResumeSource.Initial ? eventData.StartedAt : state.LastResumeAttemptedAt");
            AddAssignment(
                executionStartedAssignments,
                properties.AutomaticAttemptCount,
                "AutomaticAttemptCount = eventData.Source is SagaResumeSource.Reminder ? state.AutomaticAttemptCount + 1 : state.AutomaticAttemptCount");
            AddAssignment(executionStartedAssignments, properties.ResumeDisposition, pendingDisposition);
            if (executionStartedAssignments.Count > 0)
            {
                reducerBlocks.Add(
                    GenerateReducerClass(
                        projection.TypeName,
                        "SagaStepExecutionStartedStatusReducer",
                        "SagaStepExecutionStarted",
                        JoinAssignments(executionStartedAssignments)));
            }

            List<string> resumeBlockedAssignments = [];
            AddAssignment(resumeBlockedAssignments, properties.PendingDirection, "PendingDirection = eventData.Direction");
            AddAssignment(resumeBlockedAssignments, properties.PendingStepIndex, "PendingStepIndex = eventData.StepIndex");
            AddAssignment(resumeBlockedAssignments, properties.PendingStepName, "PendingStepName = eventData.StepName");
            AddAssignment(resumeBlockedAssignments, properties.BlockedReason, "BlockedReason = eventData.BlockedReason");
            AddAssignment(resumeBlockedAssignments, properties.LastResumeSource, "LastResumeSource = eventData.Source");
            AddAssignment(resumeBlockedAssignments, properties.LastResumeAttemptedAt, "LastResumeAttemptedAt = eventData.BlockedAt");
            AddAssignment(
                resumeBlockedAssignments,
                properties.AutomaticAttemptCount,
                "AutomaticAttemptCount = eventData.Source is SagaResumeSource.Reminder ? state.AutomaticAttemptCount + 1 : state.AutomaticAttemptCount");
            AddAssignment(resumeBlockedAssignments, properties.ResumeDisposition, ManualInterventionDisposition);
            if (resumeBlockedAssignments.Count > 0)
            {
                reducerBlocks.Add(
                    GenerateReducerClass(
                        projection.TypeName,
                        "SagaResumeBlockedStatusReducer",
                        "SagaResumeBlocked",
                        JoinAssignments(resumeBlockedAssignments)));
            }

            List<string> stepCompensatedAssignments = [];
            AddAssignment(
                stepCompensatedAssignments,
                properties.PendingDirection,
                "PendingDirection = SagaExecutionDirection.Compensation");
            AddAssignment(stepCompensatedAssignments, properties.PendingStepIndex, "PendingStepIndex = eventData.StepIndex - 1");
            AddAssignment(stepCompensatedAssignments, properties.PendingStepName, "PendingStepName = null");
            AddAssignment(stepCompensatedAssignments, properties.BlockedReason, "BlockedReason = null");
            AddAssignment(stepCompensatedAssignments, properties.ResumeDisposition, pendingDisposition);
            if (stepCompensatedAssignments.Count > 0)
            {
                reducerBlocks.Add(
                    GenerateReducerClass(
                        projection.TypeName,
                        "SagaStepCompensatedStatusReducer",
                        "SagaStepCompensated",
                        JoinAssignments(stepCompensatedAssignments)));
            }
        }

        foreach (string reducerBlock in reducerBlocks)
        {
            sb.AppendLine(reducerBlock);
            sb.AppendLine();
        }

        context.AddSource(
            $"{projection.TypeName}.SagaStatusReducers.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static List<ProjectionInfo> GetProjectionsFromCompilation(
        Compilation compilation
    )
    {
        List<ProjectionInfo> projections = new();
        INamedTypeSymbol? attributeSymbol = compilation.GetTypeByMetadataName(
            GenerateSagaStatusReducersAttributeFullName);
        if (attributeSymbol is null)
        {
            return projections;
        }

        FindProjectionsInNamespace(compilation.Assembly.GlobalNamespace, attributeSymbol, projections);
        return projections;
    }

    /// <inheritdoc />
    public void Initialize(
        IncrementalGeneratorInitializationContext context
    )
    {
        IncrementalValueProvider<List<ProjectionInfo>> projectionsProvider = context.CompilationProvider.Select((
            compilation,
            _
        ) => GetProjectionsFromCompilation(compilation));
        context.RegisterSourceOutput(
            projectionsProvider,
            static (
                spc,
                projections
            ) =>
            {
                foreach (ProjectionInfo projection in projections)
                {
                    GenerateReducers(spc, projection);
                }
            });
    }

    private sealed class ProjectionInfo
    {
        public ProjectionInfo(
            INamedTypeSymbol typeSymbol,
            string typeName,
            string @namespace
        )
        {
            TypeSymbol = typeSymbol;
            TypeName = typeName;
            Namespace = @namespace;
        }

        public string Namespace { get; }

        public string TypeName { get; }

        public INamedTypeSymbol TypeSymbol { get; }
    }

    private sealed class ProjectionProperties
    {
        private ProjectionProperties(
            bool recoveryMode,
            bool recoveryProfile,
            bool pendingDirection,
            bool pendingStepIndex,
            bool pendingStepName,
            bool resumeDisposition,
            bool blockedReason,
            bool lastResumeSource,
            bool lastResumeAttemptedAt,
            bool automaticAttemptCount
        )
        {
            RecoveryMode = recoveryMode;
            RecoveryProfile = recoveryProfile;
            PendingDirection = pendingDirection;
            PendingStepIndex = pendingStepIndex;
            PendingStepName = pendingStepName;
            ResumeDisposition = resumeDisposition;
            BlockedReason = blockedReason;
            LastResumeSource = lastResumeSource;
            LastResumeAttemptedAt = lastResumeAttemptedAt;
            AutomaticAttemptCount = automaticAttemptCount;
        }

        public bool AutomaticAttemptCount { get; }

        public bool BlockedReason { get; }

        public bool HasRecoveryMetadata =>
            RecoveryMode || RecoveryProfile || PendingDirection || PendingStepIndex || PendingStepName ||
            ResumeDisposition || BlockedReason || LastResumeSource || LastResumeAttemptedAt || AutomaticAttemptCount;

        public bool LastResumeAttemptedAt { get; }

        public bool LastResumeSource { get; }

        public bool PendingDirection { get; }

        public bool PendingStepIndex { get; }

        public bool PendingStepName { get; }

        public bool RecoveryMode { get; }

        public bool RecoveryProfile { get; }

        public bool ResumeDisposition { get; }

        public static ProjectionProperties Create(
            INamedTypeSymbol projectionType
        ) =>
            new(
                HasNamedTypeProperty(
                    projectionType,
                    nameof(RecoveryMode),
                    "Mississippi.DomainModeling.Abstractions.SagaRecoveryMode"),
                HasStringProperty(projectionType, nameof(RecoveryProfile)),
                HasNamedTypeProperty(
                    projectionType,
                    nameof(PendingDirection),
                    "Mississippi.DomainModeling.Abstractions.SagaExecutionDirection",
                    nullable: true),
                HasIntProperty(projectionType, nameof(PendingStepIndex), nullable: true),
                HasStringProperty(projectionType, nameof(PendingStepName)),
                HasNamedTypeProperty(
                    projectionType,
                    nameof(ResumeDisposition),
                    "Mississippi.DomainModeling.Abstractions.SagaResumeDisposition"),
                HasStringProperty(projectionType, nameof(BlockedReason)),
                HasNamedTypeProperty(
                    projectionType,
                    nameof(LastResumeSource),
                    "Mississippi.DomainModeling.Abstractions.SagaResumeSource",
                    nullable: true),
                HasNamedTypeProperty(
                    projectionType,
                    nameof(LastResumeAttemptedAt),
                    "System.DateTimeOffset",
                    nullable: true),
                HasIntProperty(projectionType, nameof(AutomaticAttemptCount)));

        private static bool HasNamedTypeProperty(
            INamedTypeSymbol projectionType,
            string propertyName,
            string fullTypeName,
            bool nullable = false
        )
        {
            if (!TryGetProperty(projectionType, propertyName, out IPropertySymbol property))
            {
                return false;
            }

            return nullable
                ? property.Type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } nullableType &&
                  nullableType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                      .Replace("global::", string.Empty) == fullTypeName
                : property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                    .Replace("global::", string.Empty) == fullTypeName;
        }

        private static bool HasIntProperty(
            INamedTypeSymbol projectionType,
            string propertyName,
            bool nullable = false
        )
        {
            if (!TryGetProperty(projectionType, propertyName, out IPropertySymbol property))
            {
                return false;
            }

            return nullable
                ? property.Type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } nullableType &&
                  nullableType.TypeArguments[0].SpecialType == SpecialType.System_Int32
                : property.Type.SpecialType == SpecialType.System_Int32;
        }

        private static bool HasStringProperty(
            INamedTypeSymbol projectionType,
            string propertyName
        )
        {
            if (!TryGetProperty(projectionType, propertyName, out IPropertySymbol property))
            {
                return false;
            }

            return property.Type.SpecialType == SpecialType.System_String;
        }

        private static bool TryGetProperty(
            INamedTypeSymbol projectionType,
            string propertyName,
            out IPropertySymbol property
        )
        {
            property = projectionType.GetMembers(propertyName).OfType<IPropertySymbol>().FirstOrDefault()!;
            return property is not null;
        }
    }
}