using System;
using System.IO;
using System.Text;


namespace Mississippi.DocumentationGenerator.Output;

/// <summary>
///     Provides utilities for writing documentation output files.
/// </summary>
public sealed class DocumentationWriter
{
    private const string GeneratedHeader = """
        ---
        sidebar_position: {0}
        ---

        {1}

        """;

    private const string AutoGeneratedNotice = """
        :::note Auto-generated
        This page is automatically generated by the Mississippi Documentation Generator.
        Do not edit this file directly - your changes will be overwritten.
        :::

        """;

    /// <summary>
    ///     Prepares the output directory by cleaning it if it exists.
    /// </summary>
    /// <param name="outputDirectory">The output directory path.</param>
    public void PrepareOutputDirectory(
        string outputDirectory
    )
    {
        ArgumentNullException.ThrowIfNull(outputDirectory);

        if (Directory.Exists(outputDirectory))
        {
            Directory.Delete(outputDirectory, recursive: true);
        }

        Directory.CreateDirectory(outputDirectory);
    }

    /// <summary>
    ///     Writes an MDX file with the standard header.
    /// </summary>
    /// <param name="filePath">The file path to write to.</param>
    /// <param name="title">The page title.</param>
    /// <param name="content">The page content.</param>
    /// <param name="sidebarPosition">The sidebar position.</param>
    /// <param name="includeAutoGeneratedNotice">Whether to include the auto-generated notice.</param>
    public void WriteMdxFile(
        string filePath,
        string title,
        string content,
        int sidebarPosition = 1,
        bool includeAutoGeneratedNotice = true
    )
    {
        ArgumentNullException.ThrowIfNull(filePath);
        ArgumentNullException.ThrowIfNull(title);
        ArgumentNullException.ThrowIfNull(content);

        string? directory = Path.GetDirectoryName(filePath);
        if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
        {
            Directory.CreateDirectory(directory);
        }

        StringBuilder sb = new();
        sb.AppendFormat(GeneratedHeader, sidebarPosition, $"# {title}");
        sb.AppendLine();

        if (includeAutoGeneratedNotice)
        {
            sb.Append(AutoGeneratedNotice);
            sb.AppendLine();
        }

        sb.Append(content);

        // Ensure file ends with newline for deterministic output
        string finalContent = sb.ToString();
        if (!finalContent.EndsWith('\n'))
        {
            finalContent += Environment.NewLine;
        }

        File.WriteAllText(filePath, finalContent, Encoding.UTF8);
    }

    /// <summary>
    ///     Writes a category JSON file for Docusaurus sidebar organization.
    /// </summary>
    /// <param name="directoryPath">The directory to write the category file in.</param>
    /// <param name="label">The category label.</param>
    /// <param name="position">The sidebar position.</param>
    public void WriteCategoryJson(
        string directoryPath,
        string label,
        int position = 1
    )
    {
        ArgumentNullException.ThrowIfNull(directoryPath);
        ArgumentNullException.ThrowIfNull(label);

        if (!Directory.Exists(directoryPath))
        {
            Directory.CreateDirectory(directoryPath);
        }

        string categoryPath = Path.Combine(directoryPath, "_category_.json");
        string content = $$"""
            {
              "label": "{{label}}",
              "position": {{position}},
              "link": {
                "type": "generated-index"
              }
            }
            """;

        File.WriteAllText(categoryPath, content + Environment.NewLine, Encoding.UTF8);
    }
}
