using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;

using Allure.Xunit.Attributes;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;


namespace Mississippi.Sdk.Client.Generators.L0Tests;

/// <summary>
///     Tests for <see cref="CommandClientActionsGenerator" />.
/// </summary>
[AllureParentSuite("SDK")]
[AllureSuite("Client Generators")]
[AllureSubSuite("Command Client Actions Generator")]
public class CommandClientActionsGeneratorTests
{
    /// <summary>
    ///     Minimal stubs needed for compilation without referencing the full SDK.
    /// </summary>
    private const string AttributeStubs = """
                                          namespace Mississippi.Sdk.Generators.Abstractions
                                          {
                                              using System;

                                              [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, Inherited = false)]
                                              public sealed class GenerateCommandAttribute : Attribute
                                              {
                                                  public string? Route { get; set; }
                                                  public string HttpMethod { get; set; } = "POST";
                                              }
                                          }
                                          """;

    /// <summary>
    ///     Creates a Roslyn compilation from the provided source code and runs the generator.
    /// </summary>
    private static (Compilation OutputCompilation, ImmutableArray<Diagnostic> Diagnostics, GeneratorDriverRunResult
        RunResult) RunGenerator(
            params string[] sources
        )
    {
        SyntaxTree[] syntaxTrees = sources.Select(s => CSharpSyntaxTree.ParseText(s)).ToArray();
        string runtimeDirectory = Path.GetDirectoryName(typeof(object).Assembly.Location)!;
        List<MetadataReference> references =
        [
            MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
            MetadataReference.CreateFromFile(Path.Combine(runtimeDirectory, "System.Runtime.dll")),
            MetadataReference.CreateFromFile(Path.Combine(runtimeDirectory, "System.Collections.dll")),
            MetadataReference.CreateFromFile(Path.Combine(runtimeDirectory, "System.Collections.Immutable.dll")),
        ];
        string netstandardPath = Path.Combine(runtimeDirectory, "netstandard.dll");
        if (File.Exists(netstandardPath))
        {
            references.Add(MetadataReference.CreateFromFile(netstandardPath));
        }

        CSharpCompilation compilation = CSharpCompilation.Create(
            "TestAssembly",
            syntaxTrees,
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary).WithNullableContextOptions(
                NullableContextOptions.Enable));
        CommandClientActionsGenerator generator = new();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);
        driver = driver.RunGeneratorsAndUpdateCompilation(
            compilation,
            out Compilation outputCompilation,
            out ImmutableArray<Diagnostic> diagnostics);
        return (outputCompilation, diagnostics, driver.GetRunResult());
    }

    /// <summary>
    ///     Generated actions should have auto-generated header.
    /// </summary>
    [Fact]
    public void GeneratedActionsHaveAutoGeneratedHeader()
    {
        const string commandSource = """
                                     using Mississippi.Sdk.Generators.Abstractions;

                                     namespace TestApp.Domain.Aggregates.Order.Commands
                                     {
                                         [GenerateCommand]
                                         public sealed record PlaceOrder
                                         {
                                             public string ProductId { get; init; }
                                         }
                                     }
                                     """;
        (Compilation _, ImmutableArray<Diagnostic> _, GeneratorDriverRunResult runResult) =
            RunGenerator(AttributeStubs, commandSource);
        Assert.NotEmpty(runResult.GeneratedTrees);
        string generatedCode = runResult.GeneratedTrees[0].GetText().ToString();
        Assert.Contains("// <auto-generated", generatedCode, StringComparison.Ordinal);
    }

    /// <summary>
    ///     Generated actions should include executing action.
    /// </summary>
    [Fact]
    public void GeneratedActionsIncludeExecutingAction()
    {
        const string commandSource = """
                                     using Mississippi.Sdk.Generators.Abstractions;

                                     namespace TestApp.Domain.Aggregates.Order.Commands
                                     {
                                         [GenerateCommand]
                                         public sealed record PlaceOrder
                                         {
                                             public string ProductId { get; init; }
                                         }
                                     }
                                     """;
        (Compilation _, ImmutableArray<Diagnostic> _, GeneratorDriverRunResult runResult) =
            RunGenerator(AttributeStubs, commandSource);
        bool hasExecutingAction = runResult.GeneratedTrees.Any(t => t.FilePath.Contains(
            "PlaceOrderExecutingAction.g.cs",
            StringComparison.Ordinal));
        Assert.True(hasExecutingAction);
    }

    /// <summary>
    ///     Generated actions should include failed action.
    /// </summary>
    [Fact]
    public void GeneratedActionsIncludeFailedAction()
    {
        const string commandSource = """
                                     using Mississippi.Sdk.Generators.Abstractions;

                                     namespace TestApp.Domain.Aggregates.Order.Commands
                                     {
                                         [GenerateCommand]
                                         public sealed record PlaceOrder
                                         {
                                             public string ProductId { get; init; }
                                         }
                                     }
                                     """;
        (Compilation _, ImmutableArray<Diagnostic> _, GeneratorDriverRunResult runResult) =
            RunGenerator(AttributeStubs, commandSource);
        bool hasFailedAction = runResult.GeneratedTrees.Any(t => t.FilePath.Contains(
            "PlaceOrderFailedAction.g.cs",
            StringComparison.Ordinal));
        Assert.True(hasFailedAction);
    }

    /// <summary>
    ///     Generated actions should include primary action.
    /// </summary>
    [Fact]
    public void GeneratedActionsIncludePrimaryAction()
    {
        const string commandSource = """
                                     using Mississippi.Sdk.Generators.Abstractions;

                                     namespace TestApp.Domain.Aggregates.Order.Commands
                                     {
                                         [GenerateCommand]
                                         public sealed record PlaceOrder
                                         {
                                             public string ProductId { get; init; }
                                         }
                                     }
                                     """;
        (Compilation _, ImmutableArray<Diagnostic> _, GeneratorDriverRunResult runResult) =
            RunGenerator(AttributeStubs, commandSource);
        bool hasPrimaryAction = runResult.GeneratedTrees.Any(t => t.FilePath.Contains(
            "PlaceOrderAction.g.cs",
            StringComparison.Ordinal));
        Assert.True(hasPrimaryAction);
    }

    /// <summary>
    ///     Generated actions should include succeeded action.
    /// </summary>
    [Fact]
    public void GeneratedActionsIncludeSucceededAction()
    {
        const string commandSource = """
                                     using Mississippi.Sdk.Generators.Abstractions;

                                     namespace TestApp.Domain.Aggregates.Order.Commands
                                     {
                                         [GenerateCommand]
                                         public sealed record PlaceOrder
                                         {
                                             public string ProductId { get; init; }
                                         }
                                     }
                                     """;
        (Compilation _, ImmutableArray<Diagnostic> _, GeneratorDriverRunResult runResult) =
            RunGenerator(AttributeStubs, commandSource);
        bool hasSucceededAction = runResult.GeneratedTrees.Any(t => t.FilePath.Contains(
            "PlaceOrderSucceededAction.g.cs",
            StringComparison.Ordinal));
        Assert.True(hasSucceededAction);
    }

    /// <summary>
    ///     Generator should produce four action types per command.
    /// </summary>
    [Fact]
    public void GeneratorProducesFourActionTypesPerCommand()
    {
        const string commandSource = """
                                     using Mississippi.Sdk.Generators.Abstractions;

                                     namespace TestApp.Domain.Aggregates.Order.Commands
                                     {
                                         [GenerateCommand]
                                         public sealed record PlaceOrder
                                         {
                                             public string ProductId { get; init; }
                                         }
                                     }
                                     """;
        (Compilation _, ImmutableArray<Diagnostic> _, GeneratorDriverRunResult runResult) =
            RunGenerator(AttributeStubs, commandSource);

        // Should generate: PlaceOrderAction, PlaceOrderExecutingAction, PlaceOrderSucceededAction, PlaceOrderFailedAction
        Assert.Equal(4, runResult.GeneratedTrees.Length);
    }

    /// <summary>
    ///     Generator should produce no output when no commands are present.
    /// </summary>
    [Fact]
    public void GeneratorProducesNoOutputWhenNoCommands()
    {
        const string source = """
                              namespace TestApp
                              {
                                  public class RegularClass
                                  {
                                      public string Name { get; set; }
                                  }
                              }
                              """;
        (Compilation _, ImmutableArray<Diagnostic> _, GeneratorDriverRunResult runResult) =
            RunGenerator(AttributeStubs, source);
        Assert.Empty(runResult.GeneratedTrees);
    }

    /// <summary>
    ///     Multiple commands should generate separate action sets.
    /// </summary>
    [Fact]
    public void MultipleCommandsGenerateSeparateActionSets()
    {
        const string commandSource = """
                                     using Mississippi.Sdk.Generators.Abstractions;

                                     namespace TestApp.Domain.Aggregates.Order.Commands
                                     {
                                         [GenerateCommand]
                                         public sealed record PlaceOrder
                                         {
                                             public string ProductId { get; init; }
                                         }

                                         [GenerateCommand]
                                         public sealed record CancelOrder
                                         {
                                             public string Reason { get; init; }
                                         }
                                     }
                                     """;
        (Compilation _, ImmutableArray<Diagnostic> _, GeneratorDriverRunResult runResult) =
            RunGenerator(AttributeStubs, commandSource);

        // 4 actions per command * 2 commands = 8 total
        Assert.Equal(8, runResult.GeneratedTrees.Length);
    }
}