using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

using Mississippi.Inlet.Generators.Core.Analysis;
using Mississippi.Inlet.Generators.Core.Naming;


namespace Mississippi.Inlet.Gateway.Generators;

/// <summary>
///     Generates server-side domain composition registrations that aggregate all generated mapper registrations.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class DomainServerRegistrationGenerator : IIncrementalGenerator
{
    private const string GenerateCommandAttributeFullName =
        "Mississippi.Inlet.Generators.Abstractions.GenerateCommandAttribute";

    private const string GenerateProjectionEndpointsAttributeFullName =
        "Mississippi.Inlet.Generators.Abstractions.GenerateProjectionEndpointsAttribute";

    private const string ProjectionPathAttributeFullName = "Mississippi.Inlet.Abstractions.ProjectionPathAttribute";

    private static void AddAggregateNameIfPresent(
        INamedTypeSymbol typeSymbol,
        INamedTypeSymbol? generateCommandAttribute,
        string containingNamespace,
        string domainRoot,
        Dictionary<string, HashSet<string>> aggregateNamesByDomain
    )
    {
        if (!GeneratorSymbolAnalysis.ContainsAttribute(typeSymbol, generateCommandAttribute))
        {
            return;
        }

        string? aggregateName = TargetNamespaceResolver.ExtractAggregateName(containingNamespace);
        if (string.IsNullOrEmpty(aggregateName))
        {
            return;
        }

        if (!aggregateNamesByDomain.TryGetValue(domainRoot, out HashSet<string>? aggregateNames))
        {
            aggregateNames = [];
            aggregateNamesByDomain[domainRoot] = aggregateNames;
        }

        aggregateNames.Add(aggregateName!);
    }

    private static void AddProjectionInfoIfPresent(
        INamedTypeSymbol typeSymbol,
        INamedTypeSymbol? generateProjectionAttribute,
        INamedTypeSymbol? projectionPathAttribute,
        string domainRoot,
        Dictionary<string, Dictionary<string, string>> projectionsByDomain
    )
    {
        if (!GeneratorSymbolAnalysis.ContainsAttribute(typeSymbol, generateProjectionAttribute) ||
            !GeneratorSymbolAnalysis.ContainsAttribute(typeSymbol, projectionPathAttribute))
        {
            return;
        }

        string projectionName = typeSymbol.Name.EndsWith("Projection", StringComparison.Ordinal)
            ? typeSymbol.Name.Substring(0, typeSymbol.Name.Length - "Projection".Length)
            : typeSymbol.Name;
        if (!projectionsByDomain.TryGetValue(domainRoot, out Dictionary<string, string>? projections))
        {
            projections = new(StringComparer.Ordinal);
            projectionsByDomain[domainRoot] = projections;
        }

        projections[projectionName] = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }

    private static void GatherFromNamespace(
        INamespaceSymbol namespaceSymbol,
        INamedTypeSymbol? generateCommandAttribute,
        INamedTypeSymbol? generateProjectionAttribute,
        INamedTypeSymbol? projectionPathAttribute,
        Dictionary<string, HashSet<string>> aggregateNamesByDomain,
        Dictionary<string, Dictionary<string, string>> projectionsByDomain
    )
    {
        foreach (INamedTypeSymbol typeSymbol in namespaceSymbol.GetTypeMembers())
        {
            ProcessTypeMember(
                typeSymbol,
                generateCommandAttribute,
                generateProjectionAttribute,
                projectionPathAttribute,
                aggregateNamesByDomain,
                projectionsByDomain);
        }

        foreach (INamespaceSymbol child in namespaceSymbol.GetNamespaceMembers())
        {
            GatherFromNamespace(
                child,
                generateCommandAttribute,
                generateProjectionAttribute,
                projectionPathAttribute,
                aggregateNamesByDomain,
                projectionsByDomain);
        }
    }

    private static string GenerateRegistrationsSource(
        IReadOnlyList<DomainRegistrationModel> models,
        string targetRootNamespace
    )
    {
        StringBuilder sb = new();
        bool includesAggregateMappers = models.Any(model => model.AggregateNames.Count > 0);
        bool includesProjectionMappers = models.Any(model => model.ProjectionNames.Count > 0);
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Mississippi.Sdk.Gateway;");
        sb.AppendLine();
        if (includesAggregateMappers)
        {
            sb.AppendLine($"using {targetRootNamespace}.Controllers.Aggregates.Mappers;");
        }

        if (includesProjectionMappers)
        {
            sb.AppendLine($"using {targetRootNamespace}.Controllers.Projections.Mappers;");
        }

        if (includesAggregateMappers || includesProjectionMappers)
        {
            sb.AppendLine();
        }

        string outputNamespace = targetRootNamespace + ".Controllers.Mappers";
        sb.AppendLine($"namespace {outputNamespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("///     Extension methods for registering complete gateway domain mapping feature sets.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[System.CodeDom.Compiler.GeneratedCode(\"DomainServerRegistrationGenerator\", \"1.0.0\")]");
        sb.AppendLine("public static class DomainGatewayRegistrations");
        sb.AppendLine("{");
        foreach (DomainRegistrationModel model in models.OrderBy(m => m.DomainMethodName, StringComparer.Ordinal))
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    ///     Adds all generated gateway registrations for the {model.DomainRoot} domain.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    /// <param name=\"gateway\">The Mississippi gateway builder.</param>");
            sb.AppendLine($"    public static void {model.DomainMethodName}(this MississippiGatewayBuilder gateway)");
            sb.AppendLine("    {");
            sb.AppendLine("        ArgumentNullException.ThrowIfNull(gateway);");
            sb.AppendLine("        gateway.RegisterDomainMappers(services =>");
            sb.AppendLine("        {");
            foreach (string aggregate in model.AggregateNames.OrderBy(n => n, StringComparer.Ordinal))
            {
                sb.AppendLine($"            services.Add{aggregate}AggregateMappers();");
            }

            foreach (string projection in model.ProjectionNames.OrderBy(n => n, StringComparer.Ordinal))
            {
                sb.AppendLine($"            services.Add{projection}ProjectionMappers();");
            }

            sb.AppendLine("        });");
            foreach (ProjectionRegistrationModel projection in model.Projections.OrderBy(
                         p => p.Name,
                         StringComparer.Ordinal))
            {
                sb.AppendLine($"        gateway.RegisterProjectionAuthorization<{projection.TypeName}>();");
            }

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static DomainRegistrationModel[] GetDomainRegistrations(
        Compilation compilation
    )
    {
        INamedTypeSymbol? generateCommandAttribute =
            compilation.GetTypeByMetadataName(GenerateCommandAttributeFullName);
        INamedTypeSymbol? generateProjectionAttribute =
            compilation.GetTypeByMetadataName(GenerateProjectionEndpointsAttributeFullName);
        INamedTypeSymbol? projectionPathAttribute = compilation.GetTypeByMetadataName(ProjectionPathAttributeFullName);
        Dictionary<string, HashSet<string>> aggregateNamesByDomain = new(StringComparer.Ordinal);
        Dictionary<string, Dictionary<string, string>> projectionsByDomain = new(StringComparer.Ordinal);
        foreach (IAssemblySymbol assembly in GeneratorSymbolAnalysis.GetReferencedAssemblies(compilation))
        {
            GatherFromNamespace(
                assembly.GlobalNamespace,
                generateCommandAttribute,
                generateProjectionAttribute,
                projectionPathAttribute,
                aggregateNamesByDomain,
                projectionsByDomain);
        }

        HashSet<string> domains = new(StringComparer.Ordinal);
        foreach (string domain in aggregateNamesByDomain.Keys)
        {
            domains.Add(domain);
        }

        foreach (string domain in projectionsByDomain.Keys)
        {
            domains.Add(domain);
        }

        return domains.Select(domain =>
            {
                string[] aggregateNames = aggregateNamesByDomain.TryGetValue(domain, out HashSet<string>? aggregates)
                    ? aggregates.OrderBy(n => n, StringComparer.Ordinal).ToArray()
                    : [];
                ProjectionRegistrationModel[] projections =
                    projectionsByDomain.TryGetValue(domain, out Dictionary<string, string>? projectionMap)
                        ? projectionMap.OrderBy(pair => pair.Key, StringComparer.Ordinal)
                            .Select(pair => new ProjectionRegistrationModel(pair.Key, pair.Value))
                            .ToArray()
                        : [];
                string[] projectionNames = projections.Select(projection => projection.Name).ToArray();
                return new DomainRegistrationModel(
                    NamingConventions.GetDomainRegistrationMethodName(domain) + "Gateway",
                    domain,
                    aggregateNames,
                    projections,
                    projectionNames);
            })
            .Where(model => (model.AggregateNames.Count > 0) || (model.ProjectionNames.Count > 0))
            .OrderBy(model => model.DomainMethodName, StringComparer.Ordinal)
            .ToArray();
    }

    private static void ProcessTypeMember(
        INamedTypeSymbol typeSymbol,
        INamedTypeSymbol? generateCommandAttribute,
        INamedTypeSymbol? generateProjectionAttribute,
        INamedTypeSymbol? projectionPathAttribute,
        Dictionary<string, HashSet<string>> aggregateNamesByDomain,
        Dictionary<string, Dictionary<string, string>> projectionsByDomain
    )
    {
        string containingNamespace = typeSymbol.ContainingNamespace.ToDisplayString();
        if (string.IsNullOrWhiteSpace(containingNamespace))
        {
            return;
        }

        string domainRoot = NamingConventions.GetDomainRootNamespace(containingNamespace);
        if (string.IsNullOrWhiteSpace(domainRoot))
        {
            return;
        }

        AddAggregateNameIfPresent(
            typeSymbol,
            generateCommandAttribute,
            containingNamespace,
            domainRoot,
            aggregateNamesByDomain);
        AddProjectionInfoIfPresent(
            typeSymbol,
            generateProjectionAttribute,
            projectionPathAttribute,
            domainRoot,
            projectionsByDomain);
    }

    /// <inheritdoc />
    public void Initialize(
        IncrementalGeneratorInitializationContext context
    )
    {
        IncrementalValueProvider<(Compilation Compilation, AnalyzerConfigOptionsProvider Options)>
            compilationAndOptions = context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider);
        IncrementalValueProvider<(IReadOnlyList<DomainRegistrationModel> Domains, string TargetRootNamespace)>
            domainsProvider = compilationAndOptions.Select((
                source,
                _
            ) =>
            {
                source.Options.GlobalOptions.TryGetValue(
                    TargetNamespaceResolver.RootNamespaceProperty,
                    out string? rootNamespace);
                source.Options.GlobalOptions.TryGetValue(
                    TargetNamespaceResolver.AssemblyNameProperty,
                    out string? assemblyName);
                string targetRootNamespace = TargetNamespaceResolver.GetTargetRootNamespace(
                    rootNamespace,
                    assemblyName,
                    source.Compilation);
                IReadOnlyList<DomainRegistrationModel> domains = GetDomainRegistrations(source.Compilation);
                return (domains, targetRootNamespace);
            });
        context.RegisterSourceOutput(
            domainsProvider,
            static (
                spc,
                result
            ) =>
            {
                if (result.Domains.Count == 0)
                {
                    return;
                }

                string source = GenerateRegistrationsSource(result.Domains, result.TargetRootNamespace);
                spc.AddSource("DomainGatewayRegistrations.g.cs", SourceText.From(source, Encoding.UTF8));
            });
    }

    private sealed class DomainRegistrationModel
    {
        public DomainRegistrationModel(
            string domainMethodName,
            string domainRoot,
            IReadOnlyList<string> aggregateNames,
            IReadOnlyList<ProjectionRegistrationModel> projections,
            IReadOnlyList<string> projectionNames
        )
        {
            DomainMethodName = domainMethodName;
            DomainRoot = domainRoot;
            AggregateNames = aggregateNames;
            Projections = projections;
            ProjectionNames = projectionNames;
        }

        public IReadOnlyList<string> AggregateNames { get; }

        public string DomainMethodName { get; }

        public string DomainRoot { get; }

        public IReadOnlyList<string> ProjectionNames { get; }

        public IReadOnlyList<ProjectionRegistrationModel> Projections { get; }
    }

    private sealed class ProjectionRegistrationModel
    {
        public ProjectionRegistrationModel(
            string name,
            string typeName
        )
        {
            Name = name;
            TypeName = typeName;
        }

        public string Name { get; }

        public string TypeName { get; }
    }
}