using System;
using System.Threading.Tasks;

using Cascade.Web.Contracts.Grains;

using Microsoft.AspNetCore.SignalR;

using Mississippi.Aqueduct.Abstractions;
using Mississippi.Aqueduct.Abstractions.Grains;

using Orleans;


namespace Cascade.Web.Server.Hubs;

/// <summary>
///     SignalR hub for broadcasting messages and calling Orleans grains.
/// </summary>
/// <remarks>
///     This hub demonstrates the WebAssembly → SignalR → Orleans grain flow
///     for real-time communication with grain operations.
/// </remarks>
internal sealed class MessageHub : Hub
{
    /// <summary>
    ///     Well-known group name for broadcast messages. All clients join this group on connect.
    /// </summary>
    public const string BroadcastGroupName = "broadcast";

    /// <summary>
    ///     The hub name used for SignalR grain keys.
    /// </summary>
    public const string HubName = nameof(MessageHub);

    /// <summary>
    ///     Initializes a new instance of the <see cref="MessageHub" /> class.
    /// </summary>
    /// <param name="grainFactory">The Orleans grain factory for calling grains.</param>
    /// <param name="aqueductGrainFactory">The Aqueduct grain factory for managing groups.</param>
    public MessageHub(
        IGrainFactory grainFactory,
        IAqueductGrainFactory aqueductGrainFactory
    )
    {
        GrainFactory = grainFactory ?? throw new ArgumentNullException(nameof(grainFactory));
        AqueductGrainFactory = aqueductGrainFactory ?? throw new ArgumentNullException(nameof(aqueductGrainFactory));
    }

    private IAqueductGrainFactory AqueductGrainFactory { get; }

    private IGrainFactory GrainFactory { get; }

    /// <summary>
    ///     Greets a name using the Orleans GreeterGrain and broadcasts the result.
    /// </summary>
    /// <param name="name">The name to greet.</param>
    /// <returns>A task representing the async operation.</returns>
    /// <remarks>
    ///     This demonstrates the SignalR → Orleans grain → SignalR broadcast flow.
    ///     The greeting is generated by the grain and broadcast to all clients.
    /// </remarks>
    public async Task GreetAsync(
        string name
    )
    {
        IGreeterGrain grain = GrainFactory.GetGrain<IGreeterGrain>(name);
        GreetResponse response = await grain.GreetAsync();

        // Broadcast the greeting to all connected clients
        await Clients.All.SendAsync("ReceiveGreeting", response.Greeting, response.UppercaseName, response.GeneratedAt);
    }

    /// <inheritdoc />
    public override async Task OnConnectedAsync()
    {
        // Add connection to the broadcast group so grains can send to all clients
        ISignalRGroupGrain groupGrain = AqueductGrainFactory.GetGroupGrain(HubName, BroadcastGroupName);
        await groupGrain.AddConnectionAsync(Context.ConnectionId);
        await base.OnConnectedAsync();
    }

    /// <inheritdoc />
    public override async Task OnDisconnectedAsync(
        Exception? exception
    )
    {
        // Remove connection from the broadcast group
        ISignalRGroupGrain groupGrain = AqueductGrainFactory.GetGroupGrain(HubName, BroadcastGroupName);
        await groupGrain.RemoveConnectionAsync(Context.ConnectionId);
        await base.OnDisconnectedAsync(exception);
    }

    /// <summary>
    ///     Sends a message to all connected clients.
    /// </summary>
    /// <param name="message">The message to broadcast.</param>
    /// <returns>A task representing the async operation.</returns>
    public async Task SendMessageAsync(
        string message
    ) =>
        await Clients.All.SendAsync("ReceiveMessage", message);

    /// <summary>
    ///     Converts a string to uppercase using the Orleans GreeterGrain and returns the result.
    /// </summary>
    /// <param name="input">The string to convert.</param>
    /// <returns>The uppercase string.</returns>
    /// <remarks>
    ///     This demonstrates a SignalR → Orleans grain flow with direct response.
    /// </remarks>
    public async Task<string> ToUpperAsync(
        string input
    )
    {
        IGreeterGrain grain = GrainFactory.GetGrain<IGreeterGrain>("converter");
        return await grain.ToUpperAsync(input);
    }
}