using System;
using System.Threading.Tasks;

using Cascade.Web.Contracts.Grains;

using Microsoft.AspNetCore.SignalR;

using Orleans;


namespace Cascade.Web.Server.Hubs;

/// <summary>
///     SignalR hub for broadcasting messages and calling Orleans grains.
/// </summary>
/// <remarks>
///     This hub demonstrates the WebAssembly → SignalR → Orleans grain flow
///     for real-time communication with grain operations.
/// </remarks>
internal sealed class MessageHub : Hub
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="MessageHub" /> class.
    /// </summary>
    /// <param name="grainFactory">The Orleans grain factory for calling grains.</param>
    public MessageHub(IGrainFactory grainFactory)
    {
        GrainFactory = grainFactory ?? throw new ArgumentNullException(nameof(grainFactory));
    }

    private IGrainFactory GrainFactory { get; }

    /// <summary>
    ///     Sends a message to all connected clients.
    /// </summary>
    /// <param name="message">The message to broadcast.</param>
    /// <returns>A task representing the async operation.</returns>
    public async Task SendMessageAsync(string message) =>
        await Clients.All.SendAsync("ReceiveMessage", message);

    /// <summary>
    ///     Greets a name using the Orleans GreeterGrain and broadcasts the result.
    /// </summary>
    /// <param name="name">The name to greet.</param>
    /// <returns>A task representing the async operation.</returns>
    /// <remarks>
    ///     This demonstrates the SignalR → Orleans grain → SignalR broadcast flow.
    ///     The greeting is generated by the grain and broadcast to all clients.
    /// </remarks>
    public async Task GreetAsync(string name)
    {
        IGreeterGrain grain = GrainFactory.GetGrain<IGreeterGrain>(name);
        GreetResponse response = await grain.GreetAsync();

        // Broadcast the greeting to all connected clients
        await Clients.All.SendAsync("ReceiveGreeting", response.Greeting, response.UppercaseName, response.GeneratedAt);
    }

    /// <summary>
    ///     Converts a string to uppercase using the Orleans GreeterGrain and returns the result.
    /// </summary>
    /// <param name="input">The string to convert.</param>
    /// <returns>The uppercase string.</returns>
    /// <remarks>
    ///     This demonstrates a SignalR → Orleans grain flow with direct response.
    /// </remarks>
    public async Task<string> ToUpperAsync(string input)
    {
        IGreeterGrain grain = GrainFactory.GetGrain<IGreeterGrain>("converter");
        return await grain.ToUpperAsync(input);
    }
}
