<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Brooks.Abstractions\Brooks.Abstractions.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <Description>Interfaces for brook storage providers: IBrookStorageProvider, IBrookStorageReader, and IBrookStorageWriter.</Description>
  </PropertyGroup>
</Project>
