#!/usr/bin/env pwsh

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Invoke-MonthlyCleanupCommand {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$FilePath,
        [Parameter(Mandatory)][string[]]$Arguments,
        [int[]]$AllowedExitCodes = @(0)
    )

    $output = @(& $FilePath @Arguments)
    $exitCode = $LASTEXITCODE
    if ($AllowedExitCodes -notcontains $exitCode) {
        throw "Command failed with exit code $exitCode`: $FilePath $($Arguments -join ' ')"
    }

    return [pscustomobject]@{
        ExitCode = $exitCode
        Output   = @($output | ForEach-Object { [string]$_ })
    }
}

function New-MonthlyCleanupPullRequestBody {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string[]]$StagedFiles)

    $fileManifest = @(
        $StagedFiles | Sort-Object | ForEach-Object {
            "- ``$_`` — Canonical full-repository ReSharper cleanup output."
        }
    ) -join "`n"

    return @"
## Business Value

Keeps the repository aligned with its canonical ReSharper profile by applying $($StagedFiles.Count) formatting drift file(s) in one isolated maintenance change.

## How It Works

The scheduled workflow runs ``pwsh ./clean-up.ps1`` against the complete repository, publishes the resulting patch through a least-privilege job, and creates or refreshes this single reconciliation PR.

## Files Changed

$fileManifest

## Quality Gates

- [x] Canonical full-repository cleanup completed successfully.
- [x] The cleanup patch applied cleanly to the recorded default-branch SHA.
- [ ] Build, test, analysis, and cleanup workflows must pass on the branch after it is reconciled with the latest default branch.

## Migration Notes

No API or behavior migration is required; this PR contains automated formatting drift only.

## Related Issues

Generated by the monthly cleanup drift backstop introduced by #523.
"@
}

function Publish-MonthlyCleanupPullRequest {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][ValidateSet('true', 'false')][string]$DriftState,
        [Parameter(Mandatory)][string]$PatchPath,
        [Parameter(Mandatory)][string]$DefaultBranch,
        [Parameter(Mandatory)][string]$RepositoryOwner,
        [Parameter(Mandatory)][string]$PullRequestTitle,
        [Parameter(Mandatory)][string]$RunId,
        [Parameter(Mandatory)][string]$RunAttempt
    )

    if ($DriftState -eq 'true') {
        if (-not (Test-Path -LiteralPath $PatchPath -PathType Leaf)) {
            throw "Cleanup drift artifact not found: $PatchPath"
        }
        $null = Invoke-MonthlyCleanupCommand -FilePath git -Arguments @(
            'apply', '--index', '--whitespace=nowarn', $PatchPath)
    }

    $search = '"' + $PullRequestTitle + '" in:title'
    $pullRequestResult = Invoke-MonthlyCleanupCommand -FilePath gh -Arguments @(
        'pr', 'list', '--base', $DefaultBranch, '--state', 'open', '--search', $search,
        '--limit', '1000', '--json', 'number,title,headRefName,url,isCrossRepository,headRepositoryOwner')
    $existingPullRequests = @(
        (($pullRequestResult.Output -join "`n") | ConvertFrom-Json) |
            Where-Object {
                $_.title -eq $PullRequestTitle -and
                $_.headRefName -like 'automation/monthly-cleanup-*' -and
                -not ([bool]$_.isCrossRepository) -and
                [string]$_.headRepositoryOwner.login -eq $RepositoryOwner
            }
    )
    $existing = $existingPullRequests | Select-Object -First 1

    $driftResult = Invoke-MonthlyCleanupCommand `
        -FilePath git `
        -Arguments @('diff', '--cached', '--quiet') `
        -AllowedExitCodes @(0, 1)
    if ($driftResult.ExitCode -eq 0) {
        $existingPullRequestNumber = $null
        if ($null -ne $existing) {
            $existingPullRequestNumber = $existing.number
            $null = Invoke-MonthlyCleanupCommand -FilePath gh -Arguments @(
                'pr', 'close', [string]$existing.number,
                '--comment', 'Closing this automation PR because the current default branch no longer has cleanup drift.',
                '--delete-branch')
        }
        return [pscustomobject]@{
            Action            = 'NoDrift'
            Branch            = ''
            PullRequestNumber = $existingPullRequestNumber
        }
    }

    $stagedFileResult = Invoke-MonthlyCleanupCommand -FilePath git -Arguments @(
        'diff', '--cached', '--name-only')
    $stagedFiles = @($stagedFileResult.Output | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
    $body = New-MonthlyCleanupPullRequestBody -StagedFiles $stagedFiles

    $null = Invoke-MonthlyCleanupCommand -FilePath git -Arguments @(
        'config', 'user.name', 'github-actions[bot]')
    $null = Invoke-MonthlyCleanupCommand -FilePath git -Arguments @(
        'config', 'user.email', '41898282+github-actions[bot]@users.noreply.github.com')

    if ($null -ne $existing) {
        $null = Invoke-MonthlyCleanupCommand -FilePath git -Arguments @(
            'commit', '--message', $PullRequestTitle)
        $cleanupCommitResult = Invoke-MonthlyCleanupCommand -FilePath git -Arguments @('rev-parse', 'HEAD')
        $cleanupCommit = ([string]$cleanupCommitResult.Output[0]).Trim()
        $existingBranch = [string]$existing.headRefName
        $remoteTrackingRef = "refs/remotes/origin/$existingBranch"
        $null = Invoke-MonthlyCleanupCommand -FilePath git -Arguments @(
            'fetch', '--no-tags', 'origin', "refs/heads/$existingBranch`:$remoteTrackingRef")
        $remoteShaResult = Invoke-MonthlyCleanupCommand -FilePath git -Arguments @(
            'rev-parse', $remoteTrackingRef)
        $expectedRemoteSha = ([string]$remoteShaResult.Output[0]).Trim()
        $lease = "refs/heads/$existingBranch`:$expectedRemoteSha"
        $null = Invoke-MonthlyCleanupCommand -FilePath git -Arguments @(
            'push', "--force-with-lease=$lease", 'origin',
            "$cleanupCommit`:refs/heads/$existingBranch")
        $null = Invoke-MonthlyCleanupCommand -FilePath gh -Arguments @(
            'pr', 'edit', [string]$existing.number, '--body', $body)
        return [pscustomobject]@{
            Action            = 'Updated'
            Branch            = $existingBranch
            PullRequestNumber = $existing.number
        }
    }

    $branchName = "automation/monthly-cleanup-$RunId-$RunAttempt"
    $null = Invoke-MonthlyCleanupCommand -FilePath git -Arguments @(
        'switch', '--create', $branchName)
    $null = Invoke-MonthlyCleanupCommand -FilePath git -Arguments @(
        'commit', '--message', $PullRequestTitle)
    $null = Invoke-MonthlyCleanupCommand -FilePath git -Arguments @(
        'push', '--set-upstream', 'origin', $branchName)
    $null = Invoke-MonthlyCleanupCommand -FilePath gh -Arguments @(
        'pr', 'create', '--base', $DefaultBranch, '--head', $branchName,
        '--title', $PullRequestTitle, '--body', $body)
    return [pscustomobject]@{ Action = 'Created'; Branch = $branchName; PullRequestNumber = $null }
}

function Invoke-MonthlyCleanupPullRequestValidation {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$CleanupBranch,
        [Parameter(Mandatory)][string]$DefaultBranch,
        [string[]]$Workflows = @(
            'aspire-locked-restore.yml',
            'cleanup.yml',
            'docusaurus.yml',
            'full-build.yml',
            'l0-tests.yml',
            'l1-tests.yml',
            'l2-tests.yml',
            'markdown-lint.yml',
            'powershell-tests.yml',
            'project-reference-hygiene-gate.yml',
            'sonar-cloud.yml',
            'stryker.yml',
            'src-csproj-description-check.yml'
        )
    )

    $baseTrackingRef = "refs/remotes/origin/$DefaultBranch"
    $cleanupTrackingRef = "refs/remotes/origin/$CleanupBranch"
    $null = Invoke-MonthlyCleanupCommand -FilePath git -Arguments @(
        'fetch', '--no-tags', 'origin',
        "refs/heads/$DefaultBranch`:$baseTrackingRef",
        "refs/heads/$CleanupBranch`:$cleanupTrackingRef")
    $null = Invoke-MonthlyCleanupCommand -FilePath git -Arguments @(
        'switch', '--force-create', $CleanupBranch, $cleanupTrackingRef)
    $null = Invoke-MonthlyCleanupCommand -FilePath git -Arguments @(
        'config', 'user.name', 'github-actions[bot]')
    $null = Invoke-MonthlyCleanupCommand -FilePath git -Arguments @(
        'config', 'user.email', '41898282+github-actions[bot]@users.noreply.github.com')
    $null = Invoke-MonthlyCleanupCommand -FilePath git -Arguments @(
        'merge', '--no-edit', $baseTrackingRef)
    $null = Invoke-MonthlyCleanupCommand -FilePath git -Arguments @(
        'push', 'origin', "HEAD:refs/heads/$CleanupBranch")

    foreach ($workflow in $Workflows) {
        $null = Invoke-MonthlyCleanupCommand -FilePath gh -Arguments @(
            'workflow', 'run', $workflow, '--ref', $CleanupBranch)
    }

    return [pscustomobject]@{ Branch = $CleanupBranch; WorkflowCount = $Workflows.Count }
}

Export-ModuleMember -Function Publish-MonthlyCleanupPullRequest, Invoke-MonthlyCleanupPullRequestValidation
