using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

using Mississippi.Inlet.Generators.Core.Emit;
using Mississippi.Inlet.Generators.Core.Naming;


namespace Mississippi.Inlet.Server.Generators;

/// <summary>
///     Generates domain registration wrappers for server projects.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class DomainServerRegistrationGenerator : IIncrementalGenerator
{
    private const string GenerateCommandAttributeFullName =
        "Mississippi.Inlet.Generators.Abstractions.GenerateCommandAttribute";

    private const string GenerateProjectionEndpointsAttributeFullName =
        "Mississippi.Inlet.Generators.Abstractions.GenerateProjectionEndpointsAttribute";

    /// <inheritdoc />
    public void Initialize(
        IncrementalGeneratorInitializationContext context
    )
    {
        IncrementalValueProvider<(Compilation Compilation, AnalyzerConfigOptionsProvider Options)> source =
            context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider);
        context.RegisterSourceOutput(
            source,
            static (
                spc,
                value
            ) => Generate(spc, value.Compilation, value.Options));
    }

    private static void Generate(
        SourceProductionContext context,
        Compilation compilation,
        AnalyzerConfigOptionsProvider optionsProvider
    )
    {
        string targetRootNamespace = ResolveTargetRootNamespace(compilation, optionsProvider);
        string? productNamespace = GetProductNamespace(targetRootNamespace, ".Server");
        if (string.IsNullOrWhiteSpace(productNamespace))
        {
            return;
        }

        string productTypeName = BuildTypeName(productNamespace);
        HashSet<string> aggregateNames = GetAggregateNames(compilation);
        HashSet<string> projectionNames = GetProjectionNames(compilation);
        if (aggregateNames.Count == 0 && projectionNames.Count == 0)
        {
            return;
        }

        string registrationsNamespace = targetRootNamespace + ".Registrations";
        string className = productTypeName + "DomainServerRegistrations";
        string methodName = "Add" + productTypeName + "Domain";

        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing("System");
        sb.AppendUsing("Mississippi.Common.Abstractions.Builders");
        sb.AppendUsing(targetRootNamespace + ".Controllers.Aggregates.Mappers");
        sb.AppendUsing(targetRootNamespace + ".Controllers.Projections.Mappers");
        sb.AppendFileScopedNamespace(registrationsNamespace);
        sb.AppendLine();
        sb.AppendSummary("Extension methods for registering the domain server mappers.");
        sb.AppendGeneratedCodeAttribute("DomainServerRegistrationGenerator");
        sb.AppendLine($"public static class {className}");
        sb.OpenBrace();
        sb.AppendSummary("Adds domain mappers generated from the domain project.");
        sb.AppendLine("/// <param name=\"builder\">The Mississippi server builder.</param>");
        sb.AppendLine("/// <returns>The builder for chaining.</returns>");
        sb.AppendLine($"public static IMississippiServerBuilder {methodName}(");
        sb.IncreaseIndent();
        sb.AppendLine("this IMississippiServerBuilder builder");
        sb.DecreaseIndent();
        sb.AppendLine(")");
        sb.OpenBrace();
        sb.AppendLine("ArgumentNullException.ThrowIfNull(builder);");
        sb.AppendLine("builder.ConfigureServices(services =>");
        sb.OpenBrace();
        foreach (string aggregateName in aggregateNames.OrderBy(x => x, StringComparer.Ordinal))
        {
            sb.AppendLine($"services.Add{aggregateName}AggregateMappers();");
        }

        foreach (string projectionName in projectionNames.OrderBy(x => x, StringComparer.Ordinal))
        {
            sb.AppendLine($"services.Add{projectionName}ProjectionMappers();");
        }

        sb.CloseBrace();
        sb.AppendLine(");");
        sb.AppendLine("return builder;");
        sb.CloseBrace();
        sb.CloseBrace();
        context.AddSource(
            className + ".g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static HashSet<string> GetAggregateNames(
        Compilation compilation
    )
    {
        HashSet<string> aggregateNames = new(StringComparer.Ordinal);
        INamedTypeSymbol? generateAttrSymbol = compilation.GetTypeByMetadataName(GenerateCommandAttributeFullName);
        if (generateAttrSymbol is null)
        {
            return aggregateNames;
        }

        foreach (IAssemblySymbol referencedAssembly in GetReferencedAssemblies(compilation))
        {
            FindCommandsInNamespace(referencedAssembly.GlobalNamespace, generateAttrSymbol, aggregateNames);
        }

        return aggregateNames;
    }

    private static HashSet<string> GetProjectionNames(
        Compilation compilation
    )
    {
        HashSet<string> projectionNames = new(StringComparer.Ordinal);
        INamedTypeSymbol? projectionAttrSymbol =
            compilation.GetTypeByMetadataName(GenerateProjectionEndpointsAttributeFullName);
        if (projectionAttrSymbol is null)
        {
            return projectionNames;
        }

        foreach (IAssemblySymbol referencedAssembly in GetReferencedAssemblies(compilation))
        {
            FindProjectionsInNamespace(referencedAssembly.GlobalNamespace, projectionAttrSymbol, projectionNames);
        }

        return projectionNames;
    }

    private static void FindCommandsInNamespace(
        INamespaceSymbol namespaceSymbol,
        INamedTypeSymbol generateAttrSymbol,
        HashSet<string> aggregateNames
    )
    {
        foreach (INamedTypeSymbol typeSymbol in namespaceSymbol.GetTypeMembers())
        {
            if (typeSymbol.GetAttributes()
                    .Any(attr => SymbolEqualityComparer.Default.Equals(attr.AttributeClass, generateAttrSymbol)))
            {
                string? aggregateName = NamingConventions.GetAggregateNameFromNamespace(
                    typeSymbol.ContainingNamespace.ToDisplayString());
                if (!string.IsNullOrWhiteSpace(aggregateName))
                {
                    aggregateNames.Add(aggregateName);
                }
            }
        }

        foreach (INamespaceSymbol child in namespaceSymbol.GetNamespaceMembers())
        {
            FindCommandsInNamespace(child, generateAttrSymbol, aggregateNames);
        }
    }

    private static void FindProjectionsInNamespace(
        INamespaceSymbol namespaceSymbol,
        INamedTypeSymbol projectionAttrSymbol,
        HashSet<string> projectionNames
    )
    {
        foreach (INamedTypeSymbol typeSymbol in namespaceSymbol.GetTypeMembers())
        {
            if (typeSymbol.GetAttributes()
                    .Any(attr => SymbolEqualityComparer.Default.Equals(attr.AttributeClass, projectionAttrSymbol)))
            {
                string projectionName = NamingConventions.RemoveSuffix(typeSymbol.Name, "Projection");
                if (!string.IsNullOrWhiteSpace(projectionName))
                {
                    projectionNames.Add(projectionName);
                }
            }
        }

        foreach (INamespaceSymbol child in namespaceSymbol.GetNamespaceMembers())
        {
            FindProjectionsInNamespace(child, projectionAttrSymbol, projectionNames);
        }
    }

    private static IEnumerable<IAssemblySymbol> GetReferencedAssemblies(
        Compilation compilation
    )
    {
        yield return compilation.Assembly;
        foreach (MetadataReference reference in compilation.References)
        {
            if (compilation.GetAssemblyOrModuleSymbol(reference) is IAssemblySymbol assemblySymbol)
            {
                yield return assemblySymbol;
            }
        }
    }

    private static string ResolveTargetRootNamespace(
        Compilation compilation,
        AnalyzerConfigOptionsProvider optionsProvider
    )
    {
        optionsProvider.GlobalOptions.TryGetValue(
            TargetNamespaceResolver.RootNamespaceProperty,
            out string? rootNamespace);
        optionsProvider.GlobalOptions.TryGetValue(
            TargetNamespaceResolver.AssemblyNameProperty,
            out string? assemblyName);
        return TargetNamespaceResolver.GetTargetRootNamespace(rootNamespace, assemblyName, compilation);
    }

    private static string? GetProductNamespace(
        string targetRootNamespace,
        string suffix
    )
    {
        if (!targetRootNamespace.EndsWith(suffix, StringComparison.Ordinal))
        {
            return null;
        }

        return targetRootNamespace.Substring(0, targetRootNamespace.Length - suffix.Length);
    }

    private static string BuildTypeName(
        string namespacePrefix
    )
    {
        string[] parts = namespacePrefix.Split('.', StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(parts);
    }
}
