using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

using Mississippi.Inlet.Generators.Core.Emit;
using Mississippi.Inlet.Generators.Core.Naming;


namespace Mississippi.Inlet.Server.Generators;

/// <summary>
///     Generates a master registration method that calls all mapper registrations in the server.
/// </summary>
/// <remarks>
///     <para>
///         This generator produces a single entry point for all server-side registrations by scanning
///         for types marked with [GenerateCommand] and [GenerateProjectionEndpoints] attributes,
///         then generating a master extension method that calls their respective mapper registration methods.
///     </para>
///     <para>
///         Example: For a project with root namespace "Spring.Server", generates "AddSpring()" in "Spring.Server".
///     </para>
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class MasterServerRegistrationGenerator : IIncrementalGenerator
{
    private const string GenerateCommandAttributeFullName =
        "Mississippi.Inlet.Generators.Abstractions.GenerateCommandAttribute";

    private const string GenerateProjectionEndpointsAttributeFullName =
        "Mississippi.Inlet.Generators.Abstractions.GenerateProjectionEndpointsAttribute";

    /// <summary>
    ///     Recursively finds commands and projections in a namespace.
    /// </summary>
    private static void FindMarkedTypesInNamespace(
        INamespaceSymbol namespaceSymbol,
        INamedTypeSymbol commandAttrSymbol,
        INamedTypeSymbol projectionAttrSymbol,
        HashSet<string> aggregateNames,
        HashSet<string> projectionNames,
        string targetRootNamespace
    )
    {
        foreach (INamedTypeSymbol typeSymbol in namespaceSymbol.GetTypeMembers())
        {
            // Check for [GenerateCommand]
            if (typeSymbol.GetAttributes()
                .Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, commandAttrSymbol)))
            {
                // Extract aggregate name from namespace
                string? aggregateName = NamingConventions.GetAggregateNameFromNamespace(typeSymbol.ContainingNamespace.ToDisplayString());
                if (aggregateName is not null)
                {
                    aggregateNames.Add(aggregateName);
                }
            }

            // Check for [GenerateProjectionEndpoints]
            if (typeSymbol.GetAttributes()
                .Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, projectionAttrSymbol)))
            {
                // Extract projection name (remove "Projection" suffix if present)
                string projectionName = typeSymbol.Name.EndsWith("Projection", StringComparison.Ordinal)
                    ? typeSymbol.Name.Substring(0, typeSymbol.Name.Length - "Projection".Length)
                    : typeSymbol.Name;
                projectionNames.Add(projectionName);
            }
        }

        foreach (INamespaceSymbol childNs in namespaceSymbol.GetNamespaceMembers())
        {
            FindMarkedTypesInNamespace(childNs, commandAttrSymbol, projectionAttrSymbol, aggregateNames, projectionNames, targetRootNamespace);
        }
    }

    /// <summary>
    ///     Generates the master registration extension method.
    /// </summary>
    private static string GenerateMasterRegistration(
        string targetRootNamespace,
        HashSet<string> aggregateNames,
        HashSet<string> projectionNames
    )
    {
        // Extract the product name from the root namespace
        // For "Spring.Server", we want "Spring"
        string productName = targetRootNamespace.Split('.')[0];

        string outputNamespace = productName + ".Server";
        string methodName = "Add" + productName;
        string aggregateMappersNamespace = productName + ".Server.Controllers.Aggregates.Mappers";
        string projectionMappersNamespace = productName + ".Server.Controllers.Projections.Mappers";

        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing("Microsoft.Extensions.DependencyInjection");

        // Add using for the mappers namespaces where generated methods live
        if (aggregateNames.Count > 0)
        {
            sb.AppendUsing(aggregateMappersNamespace);
        }

        if (projectionNames.Count > 0)
        {
            sb.AppendUsing(projectionMappersNamespace);
        }

        sb.AppendFileScopedNamespace(outputNamespace);
        sb.AppendLine();
        sb.AppendSummary($"Extension methods for registering all {productName} server services.");
        sb.AppendGeneratedCodeAttribute("MasterServerRegistrationGenerator");
        sb.AppendLine("public static class ServiceRegistration");
        sb.OpenBrace();
        sb.AppendSummary($"Adds all {productName} server services to the service collection.");
        sb.AppendLine("/// <param name=\"services\">The service collection.</param>");
        sb.AppendLine("/// <returns>The service collection for chaining.</returns>");
        sb.AppendLine($"public static IServiceCollection {methodName}(");
        sb.IncreaseIndent();
        sb.AppendLine("this IServiceCollection services");
        sb.DecreaseIndent();
        sb.AppendLine(")");
        sb.OpenBrace();

        // Call all aggregate mapper registration methods
        foreach (string aggregateName in aggregateNames.OrderBy(n => n))
        {
            sb.AppendLine($"services.Add{aggregateName}AggregateMappers();");
        }

        // Call all projection mapper registration methods
        foreach (string projectionName in projectionNames.OrderBy(n => n))
        {
            sb.AppendLine($"services.Add{projectionName}ProjectionMappers();");
        }

        sb.AppendLine();
        sb.AppendLine("return services;");
        sb.CloseBrace();
        sb.CloseBrace();
        return sb.ToString();
    }

    /// <summary>
    ///     Gets all marked types from the compilation.
    /// </summary>
    private static (HashSet<string> AggregateNames, HashSet<string> ProjectionNames) GetMarkedTypesFromCompilation(
        Compilation compilation,
        string targetRootNamespace
    )
    {
        HashSet<string> aggregateNames = new();
        HashSet<string> projectionNames = new();

        INamedTypeSymbol? commandAttrSymbol = compilation.GetTypeByMetadataName(GenerateCommandAttributeFullName);
        INamedTypeSymbol? projectionAttrSymbol = compilation.GetTypeByMetadataName(GenerateProjectionEndpointsAttributeFullName);

        if (commandAttrSymbol is null && projectionAttrSymbol is null)
        {
            return (aggregateNames, projectionNames);
        }

        // Scan all referenced assemblies
        foreach (IAssemblySymbol referencedAssembly in GetReferencedAssemblies(compilation))
        {
            FindMarkedTypesInNamespace(
                referencedAssembly.GlobalNamespace,
                commandAttrSymbol!,
                projectionAttrSymbol!,
                aggregateNames,
                projectionNames,
                targetRootNamespace);
        }

        return (aggregateNames, projectionNames);
    }

    /// <summary>
    ///     Gets all referenced assemblies from the compilation.
    /// </summary>
    private static IEnumerable<IAssemblySymbol> GetReferencedAssemblies(
        Compilation compilation
    )
    {
        // Include the current assembly
        yield return compilation.Assembly;

        // Include all referenced assemblies
        foreach (MetadataReference reference in compilation.References)
        {
            if (compilation.GetAssemblyOrModuleSymbol(reference) is IAssemblySymbol assemblySymbol)
            {
                yield return assemblySymbol;
            }
        }
    }

    /// <summary>
    ///     Initializes the generator pipeline.
    /// </summary>
    /// <param name="context">The initialization context.</param>
    public void Initialize(
        IncrementalGeneratorInitializationContext context
    )
    {
        // Combine compilation with options provider
        IncrementalValueProvider<(Compilation Compilation, AnalyzerConfigOptionsProvider Options)>
            compilationAndOptions = context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider);

        // Use the compilation provider to scan for marked types
        IncrementalValueProvider<(string TargetRootNamespace, HashSet<string> AggregateNames, HashSet<string> ProjectionNames)>
            markedTypesProvider = compilationAndOptions.Select((
                source,
                _
            ) =>
            {
                source.Options.GlobalOptions.TryGetValue(
                    TargetNamespaceResolver.RootNamespaceProperty,
                    out string? rootNamespace);
                source.Options.GlobalOptions.TryGetValue(
                    TargetNamespaceResolver.AssemblyNameProperty,
                    out string? assemblyName);
                string targetRootNamespace = TargetNamespaceResolver.GetTargetRootNamespace(
                    rootNamespace,
                    assemblyName,
                    source.Compilation);

                (HashSet<string> aggregateNames, HashSet<string> projectionNames) = GetMarkedTypesFromCompilation(
                    source.Compilation,
                    targetRootNamespace);

                return (targetRootNamespace, aggregateNames, projectionNames);
            });

        // Register source output
        context.RegisterSourceOutput(
            markedTypesProvider,
            static (
                spc,
                data
            ) =>
            {
                if (data.AggregateNames.Count == 0 && data.ProjectionNames.Count == 0)
                {
                    return;
                }

                string registrationSource = GenerateMasterRegistration(
                    data.TargetRootNamespace,
                    data.AggregateNames,
                    data.ProjectionNames);
                spc.AddSource("ServiceRegistration.g.cs", SourceText.From(registrationSource, Encoding.UTF8));
            });
    }
}
