using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

using Mississippi.Inlet.Generators.Core.Analysis;
using Mississippi.Inlet.Generators.Core.Emit;
using Mississippi.Inlet.Generators.Core.Naming;

namespace Mississippi.Inlet.Server.Generators;

/// <summary>
///     Generates server-side saga controllers for saga states marked with [GenerateSagaEndpoints].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SagaControllerGenerator : IIncrementalGenerator
{
    private const string GenerateSagaEndpointsAttributeFullName =
        "Mississippi.Inlet.Generators.Abstractions.GenerateSagaEndpointsAttribute";

    private const string SagaStateInterfaceFullName =
        "Mississippi.EventSourcing.Sagas.Abstractions.ISagaState";

    /// <inheritdoc />
    public void Initialize(
        IncrementalGeneratorInitializationContext context
    )
    {
        IncrementalValueProvider<IReadOnlyList<SagaInfo>> sagaProvider = context.CompilationProvider
            .Select((compilation, _) => GetSagasFromCompilation(compilation, string.Empty))
            .WithTrackingName("SagaControllerGenerator_Sagas");

        context.RegisterSourceOutput(sagaProvider, (spc, sagas) =>
        {
            foreach (SagaInfo saga in sagas)
            {
                string dtoSource = GenerateStartDto(saga);
                spc.AddSource($"{saga.StartDtoTypeName}.g.cs", SourceText.From(dtoSource, Encoding.UTF8));

                string controllerSource = GenerateController(saga);
                spc.AddSource($"{saga.ControllerTypeName}.g.cs", SourceText.From(controllerSource, Encoding.UTF8));
            }
        });
    }

    private static string GenerateController(
        SagaInfo saga
    )
    {
        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing("System");
        sb.AppendUsing("System.Threading");
        sb.AppendUsing("System.Threading.Tasks");
        sb.AppendUsing("Microsoft.AspNetCore.Mvc");
        sb.AppendUsing("Microsoft.Extensions.Logging");
        sb.AppendUsing("Mississippi.EventSourcing.Aggregates.Abstractions");
        sb.AppendUsing("Mississippi.EventSourcing.Aggregates.Api");
        sb.AppendUsing("Mississippi.EventSourcing.Sagas.Abstractions");
        sb.AppendUsing(saga.SagaNamespace);
        if (!string.Equals(saga.InputTypeNamespace, saga.SagaNamespace, StringComparison.Ordinal))
        {
            sb.AppendUsing(saga.InputTypeNamespace);
        }
        sb.AppendUsing(saga.StartDtoNamespace);
        sb.AppendFileScopedNamespace(saga.ControllerNamespace);
        sb.AppendLine();

        sb.AppendSummary($"Controller for {saga.SagaName} saga operations.");
        sb.AppendGeneratedCodeAttribute("SagaControllerGenerator");
        sb.AppendLine($"[Route(\"api/sagas/{saga.RoutePrefix}/{{sagaId}}\")]");
        sb.AppendLine(
            $"public sealed class {saga.ControllerTypeName} : AggregateControllerBase<{saga.SagaStateTypeName}>");
        sb.OpenBrace();

        sb.AppendSummary($"Initializes a new instance of the <see cref=\"{saga.ControllerTypeName}\" /> class.");
        sb.AppendLine("/// <param name=\"aggregateGrainFactory\">Factory for resolving saga grains.</param>");
        sb.AppendLine("/// <param name=\"logger\">The logger for diagnostic output.</param>");
        sb.AppendLine($"public {saga.ControllerTypeName}(");
        sb.IncreaseIndent();
        sb.AppendLine("IAggregateGrainFactory aggregateGrainFactory,");
        sb.AppendLine($"ILogger<{saga.ControllerTypeName}> logger");
        sb.DecreaseIndent();
        sb.AppendLine(")");
        sb.IncreaseIndent();
        sb.AppendLine(": base(logger)");
        sb.DecreaseIndent();
        sb.OpenBrace();
        sb.AppendLine("AggregateGrainFactory = aggregateGrainFactory;");
        sb.CloseBrace();
        sb.AppendLine();

        sb.AppendLine("private IAggregateGrainFactory AggregateGrainFactory { get; }");
        sb.AppendLine();

        // Start endpoint
        sb.AppendSummary($"Starts the {saga.SagaName} saga.");
        sb.AppendLine("/// <param name=\"sagaId\">The saga identifier.</param>");
        sb.AppendLine("/// <param name=\"request\">The saga start request.</param>");
        sb.AppendLine("/// <param name=\"cancellationToken\">Cancellation token.</param>");
        sb.AppendLine("/// <returns>The operation result.</returns>");
        sb.AppendLine("[HttpPost]");
        sb.AppendLine($"public Task<ActionResult<OperationResult>> StartAsync(");
        sb.IncreaseIndent();
        sb.AppendLine("[FromRoute] Guid sagaId,");
        sb.AppendLine($"[FromBody] {saga.StartDtoTypeName} request,");
        sb.AppendLine("CancellationToken cancellationToken = default");
        sb.DecreaseIndent();
        sb.AppendLine(")");
        sb.OpenBrace();
        sb.AppendLine("ArgumentNullException.ThrowIfNull(request);");
        sb.AppendLine("return ExecuteAsync(sagaId.ToString(), MapRequest(sagaId, request), ExecuteCommandAsync, cancellationToken);");
        sb.CloseBrace();
        sb.AppendLine();

        // Status endpoint
        sb.AppendSummary($"Gets the current state for the {saga.SagaName} saga.");
        sb.AppendLine("/// <param name=\"sagaId\">The saga identifier.</param>");
        sb.AppendLine("/// <param name=\"cancellationToken\">Cancellation token.</param>");
        sb.AppendLine("/// <returns>The saga state.</returns>");
        sb.AppendLine("[HttpGet(\"status\")]");
        sb.AppendLine($"public async Task<ActionResult<{saga.SagaStateTypeName}?>> GetStatusAsync(");
        sb.IncreaseIndent();
        sb.AppendLine("[FromRoute] Guid sagaId,");
        sb.AppendLine("CancellationToken cancellationToken = default");
        sb.DecreaseIndent();
        sb.AppendLine(")");
        sb.OpenBrace();
        sb.AppendLine(
            $"IGenericAggregateGrain<{saga.SagaStateTypeName}> grain = AggregateGrainFactory.GetGenericAggregate<{saga.SagaStateTypeName}>(sagaId.ToString());");
        sb.AppendLine("var state = await grain.GetStateAsync(cancellationToken);");
        sb.AppendLine("return Ok(state);");
        sb.CloseBrace();
        sb.AppendLine();

        // Command mapper
        sb.AppendLine($"private StartSagaCommand<{saga.InputTypeName}> MapRequest(");
        sb.IncreaseIndent();
        sb.AppendLine("Guid sagaId,");
        sb.AppendLine($"{saga.StartDtoTypeName} request");
        sb.DecreaseIndent();
        sb.AppendLine(")");
        sb.OpenBrace();
        sb.AppendLine("ArgumentNullException.ThrowIfNull(request);");
        sb.AppendLine($"{saga.InputTypeName} input = {GenerateInputMapping(saga)};");
        sb.AppendLine("return new StartSagaCommand<" + saga.InputTypeName + ">");
        sb.OpenBrace();
        sb.AppendLine("SagaId = sagaId,");
        sb.AppendLine("Input = input,");
        sb.AppendLine("CorrelationId = request.CorrelationId,");
        sb.CloseBrace();
        sb.AppendLine(";");
        sb.CloseBrace();
        sb.AppendLine();

        // Execute helper
        sb.AppendLine("private Task<OperationResult> ExecuteCommandAsync(");
        sb.IncreaseIndent();
        sb.AppendLine("string sagaId,");
        sb.AppendLine($"StartSagaCommand<{saga.InputTypeName}> command,");
        sb.AppendLine("CancellationToken cancellationToken");
        sb.DecreaseIndent();
        sb.AppendLine(")");
        sb.OpenBrace();
        sb.AppendLine(
            $"IGenericAggregateGrain<{saga.SagaStateTypeName}> grain = AggregateGrainFactory.GetGenericAggregate<{saga.SagaStateTypeName}>(sagaId);");
        sb.AppendLine("return grain.ExecuteAsync(command, cancellationToken);");
        sb.CloseBrace();

        sb.CloseBrace();
        return sb.ToString();
    }

    private static string GenerateStartDto(
        SagaInfo saga
    )
    {
        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing("System");
        sb.AppendUsing("System.Text.Json.Serialization");
        sb.AppendFileScopedNamespace(saga.StartDtoNamespace);
        sb.AppendLine();
        sb.AppendSummary($"Request DTO for starting the {saga.SagaName} saga.");
        sb.AppendGeneratedCodeAttribute("SagaControllerGenerator");
        sb.AppendLine($"public sealed record {saga.StartDtoTypeName}");
        sb.OpenBrace();
        foreach (PropertyModel prop in saga.InputProperties)
        {
            string jsonPropertyName = NamingConventions.ToCamelCase(prop.Name);
            sb.AppendSummary($"Gets the {NamingConventions.ToCamelCase(prop.Name)} value.");
            sb.AppendLine($"[JsonPropertyName(\"{jsonPropertyName}\")]");
            if (prop.IsRequired)
            {
                sb.AppendLine("[JsonRequired]");
                sb.AppendLine($"public required {prop.SourceTypeName} {prop.Name} {{ get; init; }}");
            }
            else if (prop.IsNullable)
            {
                sb.AppendLine($"public {prop.SourceTypeName} {prop.Name} {{ get; init; }}");
            }
            else
            {
                sb.AppendLine($"public {prop.SourceTypeName} {prop.Name} {{ get; init; }} = default!;");
            }

            sb.AppendLine();
        }

        sb.AppendSummary("Gets the optional correlation identifier.");
        sb.AppendLine("[JsonPropertyName(\"correlationId\")]\npublic string? CorrelationId { get; init; }");
        sb.CloseBrace();
        return sb.ToString();
    }

    private static string GenerateInputMapping(
        SagaInfo saga
    )
    {
        if (saga.IsInputPositionalRecord)
        {
            string args = string.Join(", ", saga.InputProperties.Select(p => $"request.{p.Name}"));
            return $"new {saga.InputTypeName}({args})";
        }

        StringBuilder sb = new();
        sb.AppendLine("new()");
        sb.AppendLine("{");
        for (int i = 0; i < saga.InputProperties.Length; i++)
        {
            PropertyModel prop = saga.InputProperties[i];
            string comma = i < (saga.InputProperties.Length - 1) ? "," : string.Empty;
            sb.AppendLine($"    {prop.Name} = request.{prop.Name}{comma}");
        }

        sb.Append("}");
        return sb.ToString();
    }

    private static List<SagaInfo> GetSagasFromCompilation(
        Compilation compilation,
        string targetRootNamespace
    )
    {
        List<SagaInfo> sagas = [];
        INamedTypeSymbol? sagaAttrSymbol =
            compilation.GetTypeByMetadataName(GenerateSagaEndpointsAttributeFullName);
        INamedTypeSymbol? sagaStateSymbol = compilation.GetTypeByMetadataName(SagaStateInterfaceFullName);
        if (sagaAttrSymbol is null || sagaStateSymbol is null)
        {
            return sagas;
        }

        foreach (IAssemblySymbol referencedAssembly in GetReferencedAssemblies(compilation))
        {
            FindSagasInNamespace(referencedAssembly.GlobalNamespace, sagaAttrSymbol, sagaStateSymbol, sagas,
                targetRootNamespace);
        }

        return sagas;
    }

    private static void FindSagasInNamespace(
        INamespaceSymbol namespaceSymbol,
        INamedTypeSymbol sagaAttrSymbol,
        INamedTypeSymbol sagaStateSymbol,
        List<SagaInfo> sagas,
        string targetRootNamespace
    )
    {
        foreach (INamedTypeSymbol typeSymbol in namespaceSymbol.GetTypeMembers())
        {
            SagaInfo? info = TryGetSagaInfo(typeSymbol, sagaAttrSymbol, sagaStateSymbol, targetRootNamespace);
            if (info is not null)
            {
                sagas.Add(info);
            }
        }

        foreach (INamespaceSymbol childNs in namespaceSymbol.GetNamespaceMembers())
        {
            FindSagasInNamespace(childNs, sagaAttrSymbol, sagaStateSymbol, sagas, targetRootNamespace);
        }
    }

    private static SagaInfo? TryGetSagaInfo(
        INamedTypeSymbol typeSymbol,
        INamedTypeSymbol sagaAttrSymbol,
        INamedTypeSymbol sagaStateSymbol,
        string targetRootNamespace
    )
    {
        AttributeData? attr = typeSymbol.GetAttributes()
            .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, sagaAttrSymbol));
        if (attr is null)
        {
            return null;
        }

        if (!typeSymbol.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, sagaStateSymbol)))
        {
            return null;
        }

        ITypeSymbol? inputType = attr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "InputType").Value.Value as ITypeSymbol;
        if (inputType is not INamedTypeSymbol inputTypeSymbol)
        {
            return null;
        }

        string? routePrefix = attr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "RoutePrefix").Value.Value?.ToString();
        if (string.IsNullOrWhiteSpace(routePrefix))
        {
            routePrefix = NamingConventions.ToKebabCase(RemoveSagaSuffix(typeSymbol.Name));
        }

        string? featureKey = attr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "FeatureKey").Value.Value?.ToString();
        if (string.IsNullOrWhiteSpace(featureKey))
        {
            featureKey = NamingConventions.ToCamelCase(RemoveSagaSuffix(typeSymbol.Name));
        }

        return new SagaInfo(typeSymbol, inputTypeSymbol, routePrefix!, featureKey!);
    }

    private static string RemoveSagaSuffix(
        string typeName
    ) =>
        typeName.EndsWith("SagaState", StringComparison.Ordinal)
            ? typeName.Substring(0, typeName.Length - "SagaState".Length)
            : typeName;

    private static IEnumerable<IAssemblySymbol> GetReferencedAssemblies(
        Compilation compilation
    )
    {
        yield return compilation.Assembly;

        foreach (MetadataReference reference in compilation.References)
        {
            if (compilation.GetAssemblyOrModuleSymbol(reference) is IAssemblySymbol assemblySymbol)
            {
                yield return assemblySymbol;
            }
        }
    }

    private sealed class SagaInfo
    {
        public SagaInfo(
            INamedTypeSymbol sagaStateType,
            INamedTypeSymbol inputType,
            string routePrefix,
            string featureKey
        )
        {
            SagaStateType = sagaStateType;
            InputType = inputType;
            RoutePrefix = routePrefix;
            FeatureKey = featureKey;
            SagaStateTypeName = sagaStateType.Name;
            InputTypeName = inputType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
            InputTypeNamespace = TypeAnalyzer.GetFullNamespace(inputType);
            SagaNamespace = TypeAnalyzer.GetFullNamespace(sagaStateType);
            SagaName = RemoveSagaSuffix(SagaStateTypeName);
            ControllerTypeName = SagaName + "SagaController";
            ControllerNamespace = SagaNamespace + ".Controllers";
            StartDtoNamespace = SagaNamespace + ".Dtos";
            StartDtoTypeName = "Start" + SagaName + "SagaDto";

            IMethodSymbol? primaryConstructor =
                inputType.Constructors.FirstOrDefault(c => (c.Parameters.Length > 0) && !c.IsStatic);
            IsInputPositionalRecord = inputType.IsRecord && (primaryConstructor?.Parameters.Length > 0);
            InputProperties = inputType.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Accessibility.Public)
                .Where(p => !p.IsStatic)
                .Where(p => p.GetMethod is not null)
                .Select(p => new PropertyModel(p))
                .ToImmutableArray();
        }

        public string ControllerNamespace { get; }

        public string ControllerTypeName { get; }

        public string FeatureKey { get; }

        public ITypeSymbol InputType { get; }

        public ImmutableArray<PropertyModel> InputProperties { get; }

        public string InputTypeName { get; }

        public string InputTypeNamespace { get; }

        public bool IsInputPositionalRecord { get; }

        public string RoutePrefix { get; }

        public string SagaName { get; }

        public string SagaNamespace { get; }

        public INamedTypeSymbol SagaStateType { get; }

        public string SagaStateTypeName { get; }

        public string StartDtoNamespace { get; }

        public string StartDtoTypeName { get; }
    }
}
