using System;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using Mississippi.Inlet.Generators.Core.Emit;
using Mississippi.Inlet.Generators.Core.Naming;


namespace Mississippi.Inlet.Server.Generators;

/// <summary>
///     Generates Spring domain registration wrappers for server projects.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SpringDomainServerRegistrationGenerator : IIncrementalGenerator
{
    private const string SpringServerRootNamespace = "Spring.Server";

    /// <inheritdoc />
    public void Initialize(
        IncrementalGeneratorInitializationContext context
    )
    {
        IncrementalValueProvider<(Compilation Compilation, AnalyzerConfigOptionsProvider Options)> source =
            context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider);
        context.RegisterSourceOutput(
            source,
            static (
                spc,
                value
            ) =>
            {
                string targetRootNamespace = ResolveTargetRootNamespace(value.Compilation, value.Options);
                if (!string.Equals(targetRootNamespace, SpringServerRootNamespace, StringComparison.Ordinal))
                {
                    return;
                }

                SourceBuilder sb = new();
                sb.AppendAutoGeneratedHeader();
                sb.AppendUsing("System");
                sb.AppendUsing("Mississippi.Common.Abstractions.Builders");
                sb.AppendUsing("Spring.Server.Controllers.Aggregates.Mappers");
                sb.AppendUsing("Spring.Server.Controllers.Projections.Mappers");
                sb.AppendFileScopedNamespace("Spring.Server.Registrations");
                sb.AppendLine();
                sb.AppendSummary("Extension methods for registering the Spring domain server mappers.");
                sb.AppendGeneratedCodeAttribute("SpringDomainServerRegistrationGenerator");
                sb.AppendLine("public static class SpringDomainServerRegistrations");
                sb.OpenBrace();
                sb.AppendSummary("Adds Spring domain mappers generated from the domain project.");
                sb.AppendLine("/// <param name=\"builder\">The Mississippi server builder.</param>");
                sb.AppendLine("/// <returns>The builder for chaining.</returns>");
                sb.AppendLine("public static IMississippiServerBuilder AddSpringDomain(");
                sb.IncreaseIndent();
                sb.AppendLine("this IMississippiServerBuilder builder");
                sb.DecreaseIndent();
                sb.AppendLine(")");
                sb.OpenBrace();
                sb.AppendLine("ArgumentNullException.ThrowIfNull(builder);");
                sb.AppendLine("builder.ConfigureServices(services =>");
                sb.OpenBrace();
                sb.AppendLine("services.AddBankAccountAggregateMappers();");
                sb.AppendLine("services.AddBankAccountBalanceProjectionMappers();");
                sb.AppendLine("services.AddBankAccountLedgerProjectionMappers();");
                sb.AppendLine("services.AddFlaggedTransactionsProjectionMappers();");
                sb.AppendLine("services.AddMoneyTransferStatusProjectionMappers();");
                sb.CloseBrace();
                sb.AppendLine(");");
                sb.AppendLine("return builder;");
                sb.CloseBrace();
                sb.CloseBrace();
                spc.AddSource(
                    "SpringDomainServerRegistrations.g.cs",
                    SourceText.From(sb.ToString(), Encoding.UTF8));
            });
    }

    private static string ResolveTargetRootNamespace(
        Compilation compilation,
        AnalyzerConfigOptionsProvider optionsProvider
    )
    {
        optionsProvider.GlobalOptions.TryGetValue(
            TargetNamespaceResolver.RootNamespaceProperty,
            out string? rootNamespace);
        optionsProvider.GlobalOptions.TryGetValue(
            TargetNamespaceResolver.AssemblyNameProperty,
            out string? assemblyName);
        return TargetNamespaceResolver.GetTargetRootNamespace(rootNamespace, assemblyName, compilation);
    }
}
