using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

using Mississippi.Inlet.Generators.Core.Analysis;
using Mississippi.Inlet.Generators.Core.Emit;
using Mississippi.Inlet.Generators.Core.Naming;


namespace Mississippi.Inlet.Client.Generators;

/// <summary>
///     Generates client-side action effect classes for commands marked with [GenerateCommand].
/// </summary>
/// <remarks>
///     <para>
///         This generator produces one action effect class per command that extends
///         <c>CommandActionEffectBase</c> with the appropriate type parameters and route configuration.
///     </para>
///     <para>
///         Example: For "DepositFunds" command in "Contoso.Domain.Aggregates.BankAccount.Commands",
///         generates "DepositFundsActionEffect" in "Contoso.Client.Features.BankAccountAggregate.ActionEffects".
///     </para>
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class CommandClientActionEffectsGenerator : IIncrementalGenerator
{
    private const string GenerateCommandAttributeFullName =
        "Mississippi.Inlet.Generators.Abstractions.GenerateCommandAttribute";

    /// <summary>
    ///     Recursively finds commands in a namespace.
    /// </summary>
    private static void FindCommandsInNamespace(
        INamespaceSymbol namespaceSymbol,
        INamedTypeSymbol generateAttrSymbol,
        List<CommandModel> commands
    )
    {
        foreach (INamedTypeSymbol typeSymbol in namespaceSymbol.GetTypeMembers())
        {
            CommandModel? model = TryGetCommandModel(typeSymbol, generateAttrSymbol);
            if (model is not null)
            {
                commands.Add(model);
            }
        }

        foreach (INamespaceSymbol childNs in namespaceSymbol.GetNamespaceMembers())
        {
            FindCommandsInNamespace(childNs, generateAttrSymbol, commands);
        }
    }

    /// <summary>
    ///     Generates the action effect class for a command.
    /// </summary>
    private static void GenerateActionEffect(
        SourceProductionContext context,
        CommandModel command,
        string targetRootNamespace
    )
    {
        string commandName = command.TypeName;
        string effectTypeName = commandName + "ActionEffect";
        string effectsNamespace =
            NamingConventions.GetClientActionEffectsNamespace(command.Namespace, targetRootNamespace);
        string actionsNamespace = NamingConventions.GetClientActionsNamespace(command.Namespace, targetRootNamespace);
        string dtosNamespace = NamingConventions.GetClientCommandDtoNamespace(command.Namespace, targetRootNamespace);
        string stateNamespace = NamingConventions.GetClientStateNamespace(command.Namespace, targetRootNamespace);

        // Derive aggregate route prefix from namespace
        string? aggregateName = NamingConventions.GetAggregateNameFromNamespace(command.Namespace);
        if (aggregateName is null)
        {
            return;
        }

        string stateTypeName = aggregateName + "AggregateState";
        string aggregateRouteSegment = NamingConventions.ToKebabCase(aggregateName);
        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine();
        sb.AppendUsing("Mississippi.Common.Abstractions.Mapping");
        sb.AppendUsing("Mississippi.Inlet.Blazor.WebAssembly.Abstractions.ActionEffects");
        sb.AppendLine();
        sb.AppendLine($"using {actionsNamespace};");
        sb.AppendLine($"using {dtosNamespace};");
        sb.AppendLine($"using {stateNamespace};");
        sb.AppendFileScopedNamespace(effectsNamespace);
        sb.AppendLine();
        sb.AppendSummary($"Action effect that handles the {commandName} command.");
        sb.AppendLine("/// <remarks>");
        sb.AppendLine("///     <para>");
        sb.AppendLine($"///         This action effect posts to the {aggregateRouteSegment} aggregate endpoint");
        sb.AppendLine($"///         at <c>/api/aggregates/{aggregateRouteSegment}/{{entityId}}/{command.Route}</c>.");
        sb.AppendLine("///     </para>");
        sb.AppendLine("/// </remarks>");
        sb.AppendGeneratedCodeAttribute("CommandClientActionEffectsGenerator");
        sb.AppendLine($"internal sealed class {effectTypeName}");
        sb.IncreaseIndent();
        sb.AppendLine($": CommandActionEffectBase<{commandName}Action, {commandName}RequestDto, {stateTypeName},");
        sb.AppendLine($"    {commandName}ExecutingAction, {commandName}SucceededAction, {commandName}FailedAction>");
        sb.DecreaseIndent();
        sb.OpenBrace();

        // Constructor
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"///     Initializes a new instance of the <see cref=\"{effectTypeName}\" /> class.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <param name=\"httpClient\">The HTTP client for API calls.</param>");
        sb.AppendLine("/// <param name=\"mapper\">The mapper for action-to-DTO conversion.</param>");
        sb.AppendLine("/// <param name=\"timeProvider\">The time provider for timestamps.</param>");
        sb.AppendLine($"public {effectTypeName}(");
        sb.IncreaseIndent();
        sb.AppendLine("HttpClient httpClient,");
        sb.AppendLine($"IMapper<{commandName}Action, {commandName}RequestDto> mapper,");
        sb.AppendLine("TimeProvider? timeProvider = null");
        sb.DecreaseIndent();
        sb.AppendLine(")");
        sb.IncreaseIndent();
        sb.AppendLine(": base(httpClient, mapper, timeProvider)");
        sb.DecreaseIndent();
        sb.OpenBrace();
        sb.CloseBrace();
        sb.AppendLine();

        // AggregateRoutePrefix property
        sb.AppendLine("/// <inheritdoc />");
        sb.AppendLine(
            $"protected override string AggregateRoutePrefix => \"/api/aggregates/{aggregateRouteSegment}\";");
        sb.AppendLine();

        // Route property
        sb.AppendLine("/// <inheritdoc />");
        sb.AppendLine($"protected override string Route => \"{command.Route}\";");
        sb.CloseBrace();
        context.AddSource($"{effectTypeName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    ///     Gets command models and target namespace from the compilation.
    /// </summary>
    private static (List<CommandModel> Commands, string TargetRootNamespace) GetCommandsAndTargetFromCompilation(
        Compilation compilation,
        AnalyzerConfigOptionsProvider optionsProvider
    )
    {
        List<CommandModel> commands = new();
        INamedTypeSymbol? generateAttrSymbol = compilation.GetTypeByMetadataName(GenerateCommandAttributeFullName);
        if (generateAttrSymbol is null)
        {
            return (commands, string.Empty);
        }

        optionsProvider.GlobalOptions.TryGetValue(
            TargetNamespaceResolver.RootNamespaceProperty,
            out string? rootNamespace);
        optionsProvider.GlobalOptions.TryGetValue(
            TargetNamespaceResolver.AssemblyNameProperty,
            out string? assemblyName);
        string targetRootNamespace =
            TargetNamespaceResolver.GetTargetRootNamespace(rootNamespace, assemblyName, compilation);
        foreach (IAssemblySymbol referencedAssembly in GetReferencedAssemblies(compilation))
        {
            FindCommandsInNamespace(referencedAssembly.GlobalNamespace, generateAttrSymbol, commands);
        }

        return (commands, targetRootNamespace);
    }

    /// <summary>
    ///     Gets all referenced assemblies from the compilation.
    /// </summary>
    private static IEnumerable<IAssemblySymbol> GetReferencedAssemblies(
        Compilation compilation
    )
    {
        yield return compilation.Assembly;
        foreach (MetadataReference reference in compilation.References)
        {
            if (compilation.GetAssemblyOrModuleSymbol(reference) is IAssemblySymbol assemblySymbol)
            {
                yield return assemblySymbol;
            }
        }
    }

    /// <summary>
    ///     Tries to get command model from a type symbol.
    /// </summary>
    private static CommandModel? TryGetCommandModel(
        INamedTypeSymbol typeSymbol,
        INamedTypeSymbol generateAttrSymbol
    )
    {
        AttributeData? attr = typeSymbol.GetAttributes()
            .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, generateAttrSymbol));
        if (attr is null)
        {
            return null;
        }

        // Check if client effect generation is opted out
        if (!TypeAnalyzer.GetBooleanProperty(attr, "GenerateClientEffect"))
        {
            return null;
        }

        string? route = attr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "Route").Value.Value?.ToString();
        if (string.IsNullOrEmpty(route))
        {
            route = NamingConventions.ToKebabCase(typeSymbol.Name);
        }

        string httpMethod =
            attr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "HttpMethod").Value.Value?.ToString() ?? "POST";
        return new(typeSymbol, route!, httpMethod);
    }

    /// <summary>
    ///     Initializes the generator pipeline.
    /// </summary>
    /// <param name="context">The incremental generator initialization context.</param>
    public void Initialize(
        IncrementalGeneratorInitializationContext context
    )
    {
        IncrementalValueProvider<(Compilation Compilation, AnalyzerConfigOptionsProvider Options)>
            compilationAndOptions = context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider);
        IncrementalValueProvider<(List<CommandModel> Commands, string TargetRootNamespace)> commandsProvider =
            compilationAndOptions.Select((
                source,
                _
            ) => GetCommandsAndTargetFromCompilation(source.Compilation, source.Options));
        context.RegisterSourceOutput(
            commandsProvider,
            static (
                spc,
                data
            ) =>
            {
                foreach (CommandModel command in data.Commands)
                {
                    GenerateActionEffect(spc, command, data.TargetRootNamespace);
                }
            });
    }
}