using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

using Mississippi.Inlet.Generators.Core.Emit;
using Mississippi.Inlet.Generators.Core.Naming;


namespace Mississippi.Inlet.Client.Generators;

/// <summary>
///     Generates a master registration method that calls all feature registrations in the client.
/// </summary>
/// <remarks>
///     <para>
///         This generator produces a single entry point for all client-side registrations by scanning
///         for types marked with [GenerateCommand] attribute and generating a master extension method
///         that calls their respective feature registration methods.
///     </para>
///     <para>
///         Example: For a project with root namespace "Spring.Client", generates "AddSpring()" in "Spring.Client".
///     </para>
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class MasterClientRegistrationGenerator : IIncrementalGenerator
{
    private const string GenerateCommandAttributeFullName =
        "Mississippi.Inlet.Generators.Abstractions.GenerateCommandAttribute";

    /// <summary>
    ///     Recursively finds commands in a namespace.
    /// </summary>
    private static void FindMarkedTypesInNamespace(
        INamespaceSymbol namespaceSymbol,
        INamedTypeSymbol commandAttrSymbol,
        HashSet<string> aggregateNames,
        string targetRootNamespace
    )
    {
        foreach (INamedTypeSymbol typeSymbol in namespaceSymbol.GetTypeMembers())
        {
            // Check for [GenerateCommand]
            if (typeSymbol.GetAttributes()
                .Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, commandAttrSymbol)))
            {
                // Extract aggregate name from namespace
                string? aggregateName = NamingConventions.GetAggregateNameFromNamespace(typeSymbol.ContainingNamespace.ToDisplayString());
                if (aggregateName is not null)
                {
                    aggregateNames.Add(aggregateName);
                }
            }
        }

        foreach (INamespaceSymbol childNs in namespaceSymbol.GetNamespaceMembers())
        {
            FindMarkedTypesInNamespace(childNs, commandAttrSymbol, aggregateNames, targetRootNamespace);
        }
    }

    /// <summary>
    ///     Generates the master registration extension method.
    /// </summary>
    private static string GenerateMasterRegistration(
        string targetRootNamespace,
        HashSet<string> aggregateNames
    )
    {
        // Extract the product name from the root namespace
        // For "Spring.Client", we want "Spring"
        string productName = targetRootNamespace.Split('.')[0];

        string outputNamespace = productName + ".Client";
        string methodName = "Add" + productName;
        string featuresNamespace = productName + ".Client.Features";

        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing("Microsoft.Extensions.DependencyInjection");

        // Add using for the features namespace where generated registration methods live
        if (aggregateNames.Count > 0)
        {
            // Add usings for each aggregate feature namespace
            foreach (string aggregateName in aggregateNames.OrderBy(n => n))
            {
                sb.AppendUsing($"{featuresNamespace}.{aggregateName}Aggregate");
            }
        }

        sb.AppendFileScopedNamespace(outputNamespace);
        sb.AppendLine();
        sb.AppendSummary($"Extension methods for registering all {productName} client services.");
        sb.AppendGeneratedCodeAttribute("MasterClientRegistrationGenerator");
        sb.AppendLine("public static class ServiceRegistration");
        sb.OpenBrace();
        sb.AppendSummary($"Adds all {productName} client services to the service collection.");
        sb.AppendLine("/// <param name=\"services\">The service collection.</param>");
        sb.AppendLine("/// <returns>The service collection for chaining.</returns>");
        sb.AppendLine($"public static IServiceCollection {methodName}(");
        sb.IncreaseIndent();
        sb.AppendLine("this IServiceCollection services");
        sb.DecreaseIndent();
        sb.AppendLine(")");
        sb.OpenBrace();

        // Call all aggregate feature registration methods
        foreach (string aggregateName in aggregateNames.OrderBy(n => n))
        {
            sb.AppendLine($"services.Add{aggregateName}AggregateFeature();");
        }

        sb.AppendLine();
        sb.AppendLine("return services;");
        sb.CloseBrace();
        sb.CloseBrace();
        return sb.ToString();
    }

    /// <summary>
    ///     Gets all marked types from the compilation.
    /// </summary>
    private static HashSet<string> GetMarkedTypesFromCompilation(
        Compilation compilation,
        string targetRootNamespace
    )
    {
        HashSet<string> aggregateNames = new();

        INamedTypeSymbol? commandAttrSymbol = compilation.GetTypeByMetadataName(GenerateCommandAttributeFullName);

        if (commandAttrSymbol is null)
        {
            return aggregateNames;
        }

        // Scan all referenced assemblies
        foreach (IAssemblySymbol referencedAssembly in GetReferencedAssemblies(compilation))
        {
            FindMarkedTypesInNamespace(
                referencedAssembly.GlobalNamespace,
                commandAttrSymbol!,
                aggregateNames,
                targetRootNamespace);
        }

        return aggregateNames;
    }

    /// <summary>
    ///     Gets all referenced assemblies from the compilation.
    /// </summary>
    private static IEnumerable<IAssemblySymbol> GetReferencedAssemblies(
        Compilation compilation
    )
    {
        // Include the current assembly
        yield return compilation.Assembly;

        // Include all referenced assemblies
        foreach (MetadataReference reference in compilation.References)
        {
            if (compilation.GetAssemblyOrModuleSymbol(reference) is IAssemblySymbol assemblySymbol)
            {
                yield return assemblySymbol;
            }
        }
    }

    /// <summary>
    ///     Initializes the generator pipeline.
    /// </summary>
    /// <param name="context">The initialization context.</param>
    public void Initialize(
        IncrementalGeneratorInitializationContext context
    )
    {
        // Combine compilation with options provider
        IncrementalValueProvider<(Compilation Compilation, AnalyzerConfigOptionsProvider Options)>
            compilationAndOptions = context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider);

        // Use the compilation provider to scan for marked types
        IncrementalValueProvider<(string TargetRootNamespace, HashSet<string> AggregateNames)>
            markedTypesProvider = compilationAndOptions.Select((
                source,
                _
            ) =>
            {
                source.Options.GlobalOptions.TryGetValue(
                    TargetNamespaceResolver.RootNamespaceProperty,
                    out string? rootNamespace);
                source.Options.GlobalOptions.TryGetValue(
                    TargetNamespaceResolver.AssemblyNameProperty,
                    out string? assemblyName);
                string targetRootNamespace = TargetNamespaceResolver.GetTargetRootNamespace(
                    rootNamespace,
                    assemblyName,
                    source.Compilation);

                HashSet<string> aggregateNames = GetMarkedTypesFromCompilation(
                    source.Compilation,
                    targetRootNamespace);

                return (targetRootNamespace, aggregateNames);
            });

        // Register source output
        context.RegisterSourceOutput(
            markedTypesProvider,
            static (
                spc,
                data
            ) =>
            {
                if (data.AggregateNames.Count == 0)
                {
                    return;
                }

                string registrationSource = GenerateMasterRegistration(
                    data.TargetRootNamespace,
                    data.AggregateNames);
                spc.AddSource("ServiceRegistration.g.cs", SourceText.From(registrationSource, Encoding.UTF8));
            });
    }
}
