using System.Collections.Generic;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using Mississippi.Inlet.Generators.Core.Emit;

namespace Mississippi.Inlet.Client.Generators;

/// <summary>
///     Generates client-side feature registration classes for sagas marked with [GenerateSagaEndpoints].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SagaClientRegistrationGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(
        IncrementalGeneratorInitializationContext context
    )
    {
        IncrementalValueProvider<(Compilation Compilation, AnalyzerConfigOptionsProvider Options)>
            compilationAndOptions = context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider);
        IncrementalValueProvider<List<SagaClientGeneratorHelper.SagaClientInfo>> sagasProvider =
            compilationAndOptions.Select((source, _) =>
                SagaClientGeneratorHelper.GetSagasFromCompilation(source.Compilation, source.Options));
        context.RegisterSourceOutput(sagasProvider, static (spc, sagas) =>
        {
            foreach (SagaClientGeneratorHelper.SagaClientInfo saga in sagas)
            {
                GenerateRegistration(spc, saga);
            }
        });
    }

    private static void GenerateRegistration(
        SourceProductionContext context,
        SagaClientGeneratorHelper.SagaClientInfo saga
    )
    {
        string registrationTypeName = $"{saga.SagaName}SagaFeatureRegistration";
        string stateTypeName = $"{saga.SagaName}SagaState";
        string reducersTypeName = $"{saga.SagaName}SagaReducers";
        string actionPrefix = $"Start{saga.SagaName}Saga";
        string methodName = $"Add{saga.SagaName}SagaFeature";
        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing("Microsoft.Extensions.DependencyInjection");
        sb.AppendLine();
        sb.AppendUsing("Mississippi.Common.Abstractions.Mapping");
        sb.AppendUsing("Mississippi.Reservoir");
        sb.AppendLine();
        sb.AppendLine($"using {saga.ActionsNamespace};");
        sb.AppendLine($"using {saga.DtosNamespace};");
        sb.AppendLine($"using {saga.ActionEffectsNamespace};");
        sb.AppendLine($"using {saga.MappersNamespace};");
        sb.AppendLine($"using {saga.ReducersNamespace};");
        sb.AppendLine($"using {saga.StateNamespace};");
        sb.AppendFileScopedNamespace(saga.FeatureRootNamespace);
        sb.AppendLine();
        sb.AppendSummary($"Extension methods for registering the {saga.SagaName} saga feature.");
        sb.AppendLine("/// <remarks>");
        sb.AppendLine(
            $"///     This feature handles saga start requests for the {saga.SagaName} saga.");
        sb.AppendLine("/// </remarks>");
        sb.AppendGeneratedCodeAttribute("SagaClientRegistrationGenerator");
        sb.AppendLine($"internal static class {registrationTypeName}");
        sb.OpenBrace();

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"///     Adds the {saga.SagaName} saga feature to the service collection.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <param name=\"services\">The service collection.</param>");
        sb.AppendLine("/// <returns>The service collection for chaining.</returns>");
        sb.AppendLine($"public static IServiceCollection {methodName}(");
        sb.IncreaseIndent();
        sb.AppendLine("this IServiceCollection services");
        sb.DecreaseIndent();
        sb.AppendLine(")");
        sb.OpenBrace();

        sb.AppendLine("// Mappers (Action → DTO)");
        sb.AppendLine(
            $"services.AddMapper<{actionPrefix}Action, {actionPrefix}RequestDto, {actionPrefix}ActionMapper>();");
        sb.AppendLine();

        sb.AppendLine($"// Reducers - {actionPrefix}");
        sb.AppendLine($"services.AddReducer<{actionPrefix}ExecutingAction, {stateTypeName}>(");
        sb.IncreaseIndent();
        sb.AppendLine($"{reducersTypeName}.{actionPrefix}Executing);");
        sb.DecreaseIndent();
        sb.AppendLine($"services.AddReducer<{actionPrefix}SucceededAction, {stateTypeName}>(");
        sb.IncreaseIndent();
        sb.AppendLine($"{reducersTypeName}.{actionPrefix}Succeeded);");
        sb.DecreaseIndent();
        sb.AppendLine($"services.AddReducer<{actionPrefix}FailedAction, {stateTypeName}>(");
        sb.IncreaseIndent();
        sb.AppendLine($"{reducersTypeName}.{actionPrefix}Failed);");
        sb.DecreaseIndent();
        sb.AppendLine();

        sb.AppendLine("// Action Effects");
        sb.AppendLine($"services.AddActionEffect<{stateTypeName}, {actionPrefix}ActionEffect>();");
        sb.AppendLine();
        sb.AppendLine("return services;");
        sb.CloseBrace();
        sb.CloseBrace();
        context.AddSource($"{registrationTypeName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
