using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

using Mississippi.Inlet.Generators.Core.Emit;
using Mississippi.Inlet.Generators.Core.Naming;


namespace Mississippi.Inlet.Client.Generators;

/// <summary>
///     Generates client-side saga state for sagas marked with [GenerateSagaEndpoints].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SagaClientStateGenerator : IIncrementalGenerator
{
    private const string GenerateSagaEndpointsAttributeFullName =
        "Mississippi.Inlet.Generators.Abstractions.GenerateSagaEndpointsAttribute";

    private const string GeneratorName = "SagaClientStateGenerator";

    private const string ISagaDefinitionFullName = "Mississippi.EventSourcing.Sagas.Abstractions.ISagaDefinition";

    /// <summary>
    ///     Recursively finds sagas in a namespace.
    /// </summary>
    private static void FindSagasInNamespace(
        INamespaceSymbol namespaceSymbol,
        INamedTypeSymbol sagaAttrSymbol,
        INamedTypeSymbol sagaDefinitionSymbol,
        string targetRootNamespace,
        List<SagaStateInfo> sagas
    )
    {
        foreach (INamedTypeSymbol typeSymbol in namespaceSymbol.GetTypeMembers())
        {
            SagaStateInfo? info = TryGetSagaStateInfo(
                typeSymbol,
                sagaAttrSymbol,
                sagaDefinitionSymbol,
                targetRootNamespace);
            if (info is not null)
            {
                sagas.Add(info);
            }
        }

        foreach (INamespaceSymbol childNs in namespaceSymbol.GetNamespaceMembers())
        {
            FindSagasInNamespace(childNs, sagaAttrSymbol, sagaDefinitionSymbol, targetRootNamespace, sagas);
        }
    }

    /// <summary>
    ///     Generates the client state for a saga.
    /// </summary>
    private static void GenerateState(
        SourceProductionContext context,
        SagaStateInfo saga
    )
    {
        string stateName = $"{saga.SagaName}SagaFeatureState";
        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing("System");
        sb.AppendUsing("Mississippi.Reservoir.Abstractions.State");
        sb.AppendFileScopedNamespace(saga.StateNamespace);
        sb.AppendLine();
        sb.AppendSummary($"Client-side feature state for {saga.SagaName} saga operations.");
        sb.AppendGeneratedCodeAttribute(GeneratorName);
        sb.AppendLine($"public sealed record {stateName} : IFeatureState");
        sb.OpenBrace();

        // FeatureKey static property (required by IFeatureState)
        sb.AppendSummary("Gets the unique key identifying this feature state in the store.");
        sb.AppendLine($"public static string FeatureKey => \"{saga.SagaName}Saga\";");
        sb.AppendLine();

        // Default state factory
        sb.AppendSummary("Creates the default state instance.");
        sb.AppendLine($"public static {stateName} Default => new();");
        sb.AppendLine();

        // IsExecuting property
        sb.AppendSummary("Gets a value indicating whether a saga start is in progress.");
        sb.AppendLine("public bool IsExecuting { get; init; }");
        sb.AppendLine();

        // ExecutingSagaId property
        sb.AppendSummary("Gets the saga ID currently being executed, if any.");
        sb.AppendLine("public Guid? ExecutingSagaId { get; init; }");
        sb.AppendLine();

        // ErrorMessage property
        sb.AppendSummary("Gets the error message from the last failed saga start.");
        sb.AppendLine("public string? ErrorMessage { get; init; }");
        sb.AppendLine();

        // ErrorCode property
        sb.AppendSummary("Gets the error code from the last failed saga start.");
        sb.AppendLine("public string? ErrorCode { get; init; }");
        sb.AppendLine();

        // LastStartedSagaId property
        sb.AppendSummary("Gets the last successfully started saga ID.");
        sb.AppendLine("public Guid? LastStartedSagaId { get; init; }");
        sb.CloseBrace();
        context.AddSource($"{stateName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    ///     Gets all referenced assemblies from the compilation.
    /// </summary>
    private static IEnumerable<IAssemblySymbol> GetReferencedAssemblies(
        Compilation compilation
    )
    {
        yield return compilation.Assembly;
        foreach (MetadataReference reference in compilation.References)
        {
            if (compilation.GetAssemblyOrModuleSymbol(reference) is IAssemblySymbol assemblySymbol)
            {
                yield return assemblySymbol;
            }
        }
    }

    /// <summary>
    ///     Gets saga information from the compilation.
    /// </summary>
    private static List<SagaStateInfo> GetSagasFromCompilation(
        Compilation compilation,
        string targetRootNamespace
    )
    {
        List<SagaStateInfo> sagas = [];
        INamedTypeSymbol? sagaAttrSymbol = compilation.GetTypeByMetadataName(GenerateSagaEndpointsAttributeFullName);
        INamedTypeSymbol? sagaDefinitionSymbol = compilation.GetTypeByMetadataName(ISagaDefinitionFullName);
        if (sagaAttrSymbol is null || sagaDefinitionSymbol is null)
        {
            return sagas;
        }

        foreach (IAssemblySymbol referencedAssembly in GetReferencedAssemblies(compilation))
        {
            FindSagasInNamespace(
                referencedAssembly.GlobalNamespace,
                sagaAttrSymbol,
                sagaDefinitionSymbol,
                targetRootNamespace,
                sagas);
        }

        return sagas;
    }

    /// <summary>
    ///     Tries to get saga state info from a type symbol.
    /// </summary>
    private static SagaStateInfo? TryGetSagaStateInfo(
        INamedTypeSymbol typeSymbol,
        INamedTypeSymbol sagaAttrSymbol,
        INamedTypeSymbol sagaDefinitionSymbol,
        string targetRootNamespace
    )
    {
        AttributeData? attr = typeSymbol.GetAttributes()
            .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, sagaAttrSymbol));
        if (attr is null)
        {
            return null;
        }

        bool implementsSagaDefinition = typeSymbol.AllInterfaces.Any(i =>
            SymbolEqualityComparer.Default.Equals(i, sagaDefinitionSymbol));
        if (!implementsSagaDefinition)
        {
            return null;
        }

        TypedConstant inputTypeArg = attr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "InputType").Value;
        if (inputTypeArg.IsNull || inputTypeArg.Value is not INamedTypeSymbol)
        {
            return null;
        }

        // Extract saga name
        string sagaName = typeSymbol.Name;
        if (sagaName.EndsWith("SagaState", StringComparison.Ordinal))
        {
            sagaName = sagaName.Substring(0, sagaName.Length - "SagaState".Length);
        }
        else if (sagaName.EndsWith("Saga", StringComparison.Ordinal))
        {
            sagaName = sagaName.Substring(0, sagaName.Length - "Saga".Length);
        }

        string domainNamespace = typeSymbol.ContainingNamespace.ToDisplayString();
        string stateNamespace = NamingConventions.GetClientSagaFeatureNamespace(
            domainNamespace,
            targetRootNamespace,
            "State");
        return new(sagaName, stateNamespace);
    }

    /// <inheritdoc />
    public void Initialize(
        IncrementalGeneratorInitializationContext context
    )
    {
        IncrementalValueProvider<(Compilation Compilation, AnalyzerConfigOptionsProvider Options)>
            compilationAndOptions = context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider);
        IncrementalValueProvider<List<SagaStateInfo>> sagasProvider = compilationAndOptions.Select((
            source,
            _
        ) =>
        {
            source.Options.GlobalOptions.TryGetValue(
                TargetNamespaceResolver.RootNamespaceProperty,
                out string? rootNamespace);
            source.Options.GlobalOptions.TryGetValue(
                TargetNamespaceResolver.AssemblyNameProperty,
                out string? assemblyName);
            string targetRootNamespace = TargetNamespaceResolver.GetTargetRootNamespace(
                rootNamespace,
                assemblyName,
                source.Compilation);
            return GetSagasFromCompilation(source.Compilation, targetRootNamespace);
        });
        context.RegisterSourceOutput(
            sagasProvider,
            static (
                spc,
                sagas
            ) =>
            {
                foreach (SagaStateInfo saga in sagas)
                {
                    GenerateState(spc, saga);
                }
            });
    }

    /// <summary>
    ///     Information about a saga for state generation.
    /// </summary>
    private sealed class SagaStateInfo
    {
        public SagaStateInfo(
            string sagaName,
            string stateNamespace
        )
        {
            SagaName = sagaName;
            StateNamespace = stateNamespace;
        }

        public string SagaName { get; }

        public string StateNamespace { get; }
    }
}