using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

using Mississippi.Inlet.Generators.Core.Analysis;
using Mississippi.Inlet.Generators.Core.Emit;
using Mississippi.Inlet.Generators.Core.Naming;


namespace Mississippi.Inlet.Client.Generators;

/// <summary>
///     Generates client-side DTOs for sagas marked with [GenerateSagaEndpoints].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SagaClientDtoGenerator : IIncrementalGenerator
{
    private const string GenerateSagaEndpointsAttributeFullName =
        "Mississippi.Inlet.Generators.Abstractions.GenerateSagaEndpointsAttribute";

    private const string GeneratorName = "SagaClientDtoGenerator";

    private const string ISagaDefinitionFullName = "Mississippi.EventSourcing.Sagas.Abstractions.ISagaDefinition";

    /// <summary>
    ///     Recursively finds sagas in a namespace.
    /// </summary>
    private static void FindSagasInNamespace(
        INamespaceSymbol namespaceSymbol,
        INamedTypeSymbol sagaAttrSymbol,
        INamedTypeSymbol sagaDefinitionSymbol,
        string targetRootNamespace,
        List<SagaClientInfo> sagas
    )
    {
        foreach (INamedTypeSymbol typeSymbol in namespaceSymbol.GetTypeMembers())
        {
            SagaClientInfo? info = TryGetSagaClientInfo(
                typeSymbol,
                sagaAttrSymbol,
                sagaDefinitionSymbol,
                targetRootNamespace);
            if (info is not null)
            {
                sagas.Add(info);
            }
        }

        foreach (INamespaceSymbol childNs in namespaceSymbol.GetNamespaceMembers())
        {
            FindSagasInNamespace(childNs, sagaAttrSymbol, sagaDefinitionSymbol, targetRootNamespace, sagas);
        }
    }

    /// <summary>
    ///     Generates the DTO for a saga.
    /// </summary>
    private static void GenerateDto(
        SourceProductionContext context,
        SagaClientInfo saga
    )
    {
        string dtoName = $"Start{saga.SagaName}SagaDto";
        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing("System");
        sb.AppendUsing("System.Text.Json.Serialization");
        sb.AppendFileScopedNamespace(saga.DtosNamespace);
        sb.AppendLine();
        sb.AppendSummary($"Client-side DTO for starting a {saga.SagaName} saga.");
        sb.AppendGeneratedCodeAttribute(GeneratorName);
        sb.AppendLine($"public sealed record {dtoName}");
        sb.OpenBrace();

        // Generate properties from input type
        foreach (PropertyModel prop in saga.InputProperties)
        {
            string jsonPropertyName = NamingConventions.ToCamelCase(prop.Name);
            sb.AppendSummary($"Gets the {jsonPropertyName} value.");
            sb.AppendLine($"[JsonPropertyName(\"{jsonPropertyName}\")]");
            if (prop.IsRequired)
            {
                sb.AppendLine("[JsonRequired]");
                sb.AppendLine($"public required {prop.SourceTypeName} {prop.Name} {{ get; init; }}");
            }
            else if (prop.IsNullable)
            {
                sb.AppendLine($"public {prop.SourceTypeName} {prop.Name} {{ get; init; }}");
            }
            else
            {
                sb.AppendLine($"public {prop.SourceTypeName} {prop.Name} {{ get; init; }} = default!;");
            }

            sb.AppendLine();
        }

        // Always add CorrelationId
        sb.AppendSummary("Gets an optional correlation ID for distributed tracing.");
        sb.AppendLine("[JsonPropertyName(\"correlationId\")]");
        sb.AppendLine("public string? CorrelationId { get; init; }");
        sb.CloseBrace();
        context.AddSource($"{dtoName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    ///     Gets all referenced assemblies from the compilation.
    /// </summary>
    private static IEnumerable<IAssemblySymbol> GetReferencedAssemblies(
        Compilation compilation
    )
    {
        yield return compilation.Assembly;
        foreach (IAssemblySymbol assemblySymbol in compilation.References
                     .Select(reference => compilation.GetAssemblyOrModuleSymbol(reference))
                     .OfType<IAssemblySymbol>())
        {
            yield return assemblySymbol;
        }
    }

    /// <summary>
    ///     Gets saga information from the compilation.
    /// </summary>
    private static List<SagaClientInfo> GetSagasFromCompilation(
        Compilation compilation,
        string targetRootNamespace
    )
    {
        List<SagaClientInfo> sagas = [];
        INamedTypeSymbol? sagaAttrSymbol = compilation.GetTypeByMetadataName(GenerateSagaEndpointsAttributeFullName);
        INamedTypeSymbol? sagaDefinitionSymbol = compilation.GetTypeByMetadataName(ISagaDefinitionFullName);
        if (sagaAttrSymbol is null || sagaDefinitionSymbol is null)
        {
            return sagas;
        }

        foreach (IAssemblySymbol referencedAssembly in GetReferencedAssemblies(compilation))
        {
            FindSagasInNamespace(
                referencedAssembly.GlobalNamespace,
                sagaAttrSymbol,
                sagaDefinitionSymbol,
                targetRootNamespace,
                sagas);
        }

        return sagas;
    }

    /// <summary>
    ///     Tries to get saga client info from a type symbol.
    /// </summary>
    private static SagaClientInfo? TryGetSagaClientInfo(
        INamedTypeSymbol typeSymbol,
        INamedTypeSymbol sagaAttrSymbol,
        INamedTypeSymbol sagaDefinitionSymbol,
        string targetRootNamespace
    )
    {
        AttributeData? attr = typeSymbol.GetAttributes()
            .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, sagaAttrSymbol));
        if (attr is null)
        {
            return null;
        }

        bool implementsSagaDefinition = typeSymbol.AllInterfaces.Any(i =>
            SymbolEqualityComparer.Default.Equals(i, sagaDefinitionSymbol));
        if (!implementsSagaDefinition)
        {
            return null;
        }

        TypedConstant inputTypeArg = attr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "InputType").Value;
        if (inputTypeArg.IsNull || inputTypeArg.Value is not INamedTypeSymbol inputTypeSymbol)
        {
            return null;
        }

        // Extract saga name
        string sagaName = typeSymbol.Name;
        if (sagaName.EndsWith("SagaState", StringComparison.Ordinal))
        {
            sagaName = sagaName.Substring(0, sagaName.Length - "SagaState".Length);
        }
        else if (sagaName.EndsWith("Saga", StringComparison.Ordinal))
        {
            sagaName = sagaName.Substring(0, sagaName.Length - "Saga".Length);
        }

        string stateNamespace = typeSymbol.ContainingNamespace.ToDisplayString();

        // Get client feature namespace: {targetRoot}.Features.{SagaName}Saga.Dtos
        string dtosNamespace = NamingConventions.GetClientSagaFeatureNamespace(
            stateNamespace,
            targetRootNamespace,
            "Dtos");

        // Extract input properties
        PropertyModel[] inputProperties = inputTypeSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => (p.DeclaredAccessibility == Accessibility.Public) && p.GetMethod is not null)
            .Select(p => new PropertyModel(p))
            .ToArray();
        return new(sagaName, dtosNamespace, inputProperties);
    }

    /// <inheritdoc />
    public void Initialize(
        IncrementalGeneratorInitializationContext context
    )
    {
        IncrementalValueProvider<(Compilation Compilation, AnalyzerConfigOptionsProvider Options)>
            compilationAndOptions = context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider);
        IncrementalValueProvider<List<SagaClientInfo>> sagasProvider = compilationAndOptions.Select((
            source,
            _
        ) =>
        {
            source.Options.GlobalOptions.TryGetValue(
                TargetNamespaceResolver.RootNamespaceProperty,
                out string? rootNamespace);
            source.Options.GlobalOptions.TryGetValue(
                TargetNamespaceResolver.AssemblyNameProperty,
                out string? assemblyName);
            string targetRootNamespace = TargetNamespaceResolver.GetTargetRootNamespace(
                rootNamespace,
                assemblyName,
                source.Compilation);
            return GetSagasFromCompilation(source.Compilation, targetRootNamespace);
        });
        context.RegisterSourceOutput(
            sagasProvider,
            static (
                spc,
                sagas
            ) =>
            {
                foreach (SagaClientInfo saga in sagas)
                {
                    GenerateDto(spc, saga);
                }
            });
    }

    /// <summary>
    ///     Information about a saga for client DTO generation.
    /// </summary>
    private sealed class SagaClientInfo
    {
        public SagaClientInfo(
            string sagaName,
            string dtosNamespace,
            PropertyModel[] inputProperties
        )
        {
            SagaName = sagaName;
            DtosNamespace = dtosNamespace;
            InputProperties = inputProperties;
        }

        public string DtosNamespace { get; }

        public PropertyModel[] InputProperties { get; }

        public string SagaName { get; }
    }
}