using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

using Mississippi.Inlet.Generators.Core.Emit;

namespace Mississippi.Inlet.Client.Generators;

/// <summary>
///     Generates client-side mappers that convert saga start actions to request DTOs.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SagaClientMappersGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(
        IncrementalGeneratorInitializationContext context
    )
    {
        IncrementalValueProvider<(Compilation Compilation, AnalyzerConfigOptionsProvider Options)>
            compilationAndOptions = context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider);
        IncrementalValueProvider<List<SagaClientGeneratorHelper.SagaClientInfo>> sagasProvider =
            compilationAndOptions.Select((source, _) =>
                SagaClientGeneratorHelper.GetSagasFromCompilation(source.Compilation, source.Options));
        context.RegisterSourceOutput(sagasProvider, static (spc, sagas) =>
        {
            foreach (SagaClientGeneratorHelper.SagaClientInfo saga in sagas)
            {
                GenerateMapper(spc, saga);
            }
        });
    }

    private static void GenerateMapper(
        SourceProductionContext context,
        SagaClientGeneratorHelper.SagaClientInfo saga
    )
    {
        string actionName = $"Start{saga.SagaName}SagaAction";
        string dtoName = $"Start{saga.SagaName}SagaRequestDto";
        string mapperName = $"Start{saga.SagaName}SagaActionMapper";
        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing("Mississippi.Common.Abstractions.Mapping");
        sb.AppendLine($"using {saga.ActionsNamespace};");
        sb.AppendLine($"using {saga.DtosNamespace};");
        sb.AppendLine();
        sb.AppendFileScopedNamespace(saga.MappersNamespace);
        sb.AppendLine();
        sb.AppendSummary($"Maps {actionName} to {dtoName}.");
        sb.AppendLine("/// <remarks>");
        sb.AppendLine($"///     Derived from saga input: <c>{saga.InputTypeName}</c>.");
        sb.AppendLine("/// </remarks>");
        sb.AppendGeneratedCodeAttribute("SagaClientMappersGenerator");
        sb.AppendLine($"internal sealed class {mapperName} : IMapper<{actionName}, {dtoName}>");
        sb.OpenBrace();
        sb.AppendLine("/// <inheritdoc />");
        sb.AppendLine($"public {dtoName} Map({actionName} input) =>");
        sb.IncreaseIndent();

        string dtoArgs = string.Join(", ", saga.InputProperties.Select(p => $"input.{p.Name}"));
        if (!string.IsNullOrEmpty(dtoArgs))
        {
            dtoArgs += ", ";
        }

        dtoArgs += "input.CorrelationId";
        sb.AppendLine($"new({dtoArgs});");
        sb.DecreaseIndent();
        sb.CloseBrace();
        context.AddSource($"{mapperName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
