using System.Collections.Generic;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

using Mississippi.Inlet.Generators.Core.Emit;

namespace Mississippi.Inlet.Client.Generators;

/// <summary>
///     Generates client-side action effect classes for sagas marked with [GenerateSagaEndpoints].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SagaClientActionEffectsGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(
        IncrementalGeneratorInitializationContext context
    )
    {
        IncrementalValueProvider<(Compilation Compilation, AnalyzerConfigOptionsProvider Options)>
            compilationAndOptions = context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider);
        IncrementalValueProvider<List<SagaClientGeneratorHelper.SagaClientInfo>> sagasProvider =
            compilationAndOptions.Select((source, _) =>
                SagaClientGeneratorHelper.GetSagasFromCompilation(source.Compilation, source.Options));
        context.RegisterSourceOutput(sagasProvider, static (spc, sagas) =>
        {
            foreach (SagaClientGeneratorHelper.SagaClientInfo saga in sagas)
            {
                GenerateActionEffect(spc, saga);
            }
        });
    }

    private static void GenerateActionEffect(
        SourceProductionContext context,
        SagaClientGeneratorHelper.SagaClientInfo saga
    )
    {
        string actionName = $"Start{saga.SagaName}SagaAction";
        string effectTypeName = $"Start{saga.SagaName}SagaActionEffect";
        string dtoName = $"Start{saga.SagaName}SagaRequestDto";
        string stateTypeName = $"{saga.SagaName}SagaState";
        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine();
        sb.AppendUsing("Mississippi.Common.Abstractions.Mapping");
        sb.AppendUsing("Mississippi.Inlet.Client.Abstractions.ActionEffects");
        sb.AppendLine();
        sb.AppendLine($"using {saga.ActionsNamespace};");
        sb.AppendLine($"using {saga.DtosNamespace};");
        sb.AppendLine($"using {saga.StateNamespace};");
        sb.AppendFileScopedNamespace(saga.ActionEffectsNamespace);
        sb.AppendLine();
        sb.AppendSummary($"Action effect that handles the {saga.SagaName} saga start request.");
        sb.AppendLine("/// <remarks>");
        sb.AppendLine("///     <para>");
        sb.AppendLine(
            $"///         This action effect posts to the {saga.SagaName} saga endpoint at <c>/api/sagas/{saga.RoutePrefix}/{{sagaId}}</c>.");
        sb.AppendLine("///     </para>");
        sb.AppendLine("/// </remarks>");
        sb.AppendGeneratedCodeAttribute("SagaClientActionEffectsGenerator");
        sb.AppendLine($"internal sealed class {effectTypeName}");
        sb.IncreaseIndent();
        sb.AppendLine($": CommandActionEffectBase<{actionName}, {dtoName}, {stateTypeName},");
        sb.AppendLine($"    Start{saga.SagaName}SagaExecutingAction, Start{saga.SagaName}SagaSucceededAction, Start{saga.SagaName}SagaFailedAction>");
        sb.DecreaseIndent();
        sb.OpenBrace();

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"///     Initializes a new instance of the <see cref=\"{effectTypeName}\" /> class.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <param name=\"httpClient\">The HTTP client for API calls.</param>");
        sb.AppendLine("/// <param name=\"mapper\">The mapper for action-to-DTO conversion.</param>");
        sb.AppendLine("/// <param name=\"timeProvider\">The time provider for timestamps.</param>");
        sb.AppendLine($"public {effectTypeName}(");
        sb.IncreaseIndent();
        sb.AppendLine("HttpClient httpClient,");
        sb.AppendLine($"IMapper<{actionName}, {dtoName}> mapper,");
        sb.AppendLine("TimeProvider? timeProvider = null");
        sb.DecreaseIndent();
        sb.AppendLine(")");
        sb.IncreaseIndent();
        sb.AppendLine(": base(httpClient, mapper, timeProvider)");
        sb.DecreaseIndent();
        sb.OpenBrace();
        sb.CloseBrace();
        sb.AppendLine();

        sb.AppendLine("/// <inheritdoc />");
        sb.AppendLine($"protected override string AggregateRoutePrefix => \"/api/sagas/{saga.RoutePrefix}\";");
        sb.AppendLine();

        sb.AppendLine("/// <inheritdoc />");
        sb.AppendLine("protected override string Route => string.Empty;");
        sb.AppendLine();

        sb.AppendLine("/// <inheritdoc />");
        sb.AppendLine($"protected override string GetEndpoint({actionName} action) =>");
        sb.IncreaseIndent();
        sb.AppendLine($"$\"{{AggregateRoutePrefix}}/{{action.SagaId}}\";");
        sb.DecreaseIndent();
        sb.CloseBrace();
        context.AddSource($"{effectTypeName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
