using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

using Mississippi.Inlet.Generators.Core.Emit;
using Mississippi.Inlet.Generators.Core.Naming;


namespace Mississippi.Inlet.Client.Generators;

/// <summary>
///     Generates client-side saga reducers for sagas marked with [GenerateSagaEndpoints].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SagaClientReducersGenerator : IIncrementalGenerator
{
    private const string GenerateSagaEndpointsAttributeFullName =
        "Mississippi.Inlet.Generators.Abstractions.GenerateSagaEndpointsAttribute";

    private const string GeneratorName = "SagaClientReducersGenerator";

    private const string ISagaDefinitionFullName = "Mississippi.EventSourcing.Sagas.Abstractions.ISagaDefinition";

    /// <summary>
    ///     Recursively finds sagas in a namespace.
    /// </summary>
    private static void FindSagasInNamespace(
        INamespaceSymbol namespaceSymbol,
        INamedTypeSymbol sagaAttrSymbol,
        INamedTypeSymbol sagaDefinitionSymbol,
        string targetRootNamespace,
        List<SagaReducerInfo> sagas
    )
    {
        foreach (INamedTypeSymbol typeSymbol in namespaceSymbol.GetTypeMembers())
        {
            SagaReducerInfo? info = TryGetSagaReducerInfo(
                typeSymbol,
                sagaAttrSymbol,
                sagaDefinitionSymbol,
                targetRootNamespace);
            if (info is not null)
            {
                sagas.Add(info);
            }
        }

        foreach (INamespaceSymbol childNs in namespaceSymbol.GetNamespaceMembers())
        {
            FindSagasInNamespace(childNs, sagaAttrSymbol, sagaDefinitionSymbol, targetRootNamespace, sagas);
        }
    }

    /// <summary>
    ///     Generates the executing reducer.
    /// </summary>
    private static void GenerateExecutingReducer(
        SourceProductionContext context,
        SagaReducerInfo saga
    )
    {
        string reducerName = $"Start{saga.SagaName}SagaExecutingReducer";
        string actionName = $"Start{saga.SagaName}SagaExecutingAction";
        string stateName = $"{saga.SagaName}SagaFeatureState";
        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing("Mississippi.Reservoir.Abstractions");
        sb.AppendUsing("Mississippi.Reservoir.Abstractions.Actions");
        sb.AppendUsing(saga.ActionsNamespace);
        sb.AppendUsing(saga.StateNamespace);
        sb.AppendFileScopedNamespace(saga.ReducersNamespace);
        sb.AppendLine();
        sb.AppendSummary($"Reducer for {actionName}.");
        sb.AppendGeneratedCodeAttribute(GeneratorName);
        sb.AppendLine($"internal sealed class {reducerName} : ActionReducerBase<{actionName}, {stateName}>");
        sb.OpenBrace();
        sb.AppendLine("/// <inheritdoc />");
        sb.AppendLine($"public override {stateName} Reduce(");
        sb.IncreaseIndent();
        sb.AppendLine($"{stateName} state,");
        sb.AppendLine($"{actionName} action");
        sb.DecreaseIndent();
        sb.AppendLine(")");
        sb.OpenBrace();
        sb.AppendLine("return state with");
        sb.OpenBrace();
        sb.AppendLine("IsExecuting = true,");
        sb.AppendLine("ExecutingSagaId = action.SagaId,");
        sb.AppendLine("ErrorMessage = null,");
        sb.AppendLine("ErrorCode = null");
        sb.CloseBrace();
        sb.AppendLine(";");
        sb.CloseBrace();
        sb.CloseBrace();
        context.AddSource($"{reducerName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    ///     Generates the failed reducer.
    /// </summary>
    private static void GenerateFailedReducer(
        SourceProductionContext context,
        SagaReducerInfo saga
    )
    {
        string reducerName = $"Start{saga.SagaName}SagaFailedReducer";
        string actionName = $"Start{saga.SagaName}SagaFailedAction";
        string stateName = $"{saga.SagaName}SagaFeatureState";
        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing("Mississippi.Reservoir.Abstractions");
        sb.AppendUsing("Mississippi.Reservoir.Abstractions.Actions");
        sb.AppendUsing(saga.ActionsNamespace);
        sb.AppendUsing(saga.StateNamespace);
        sb.AppendFileScopedNamespace(saga.ReducersNamespace);
        sb.AppendLine();
        sb.AppendSummary($"Reducer for {actionName}.");
        sb.AppendGeneratedCodeAttribute(GeneratorName);
        sb.AppendLine($"internal sealed class {reducerName} : ActionReducerBase<{actionName}, {stateName}>");
        sb.OpenBrace();
        sb.AppendLine("/// <inheritdoc />");
        sb.AppendLine($"public override {stateName} Reduce(");
        sb.IncreaseIndent();
        sb.AppendLine($"{stateName} state,");
        sb.AppendLine($"{actionName} action");
        sb.DecreaseIndent();
        sb.AppendLine(")");
        sb.OpenBrace();
        sb.AppendLine("return state with");
        sb.OpenBrace();
        sb.AppendLine("IsExecuting = false,");
        sb.AppendLine("ExecutingSagaId = null,");
        sb.AppendLine("ErrorMessage = action.ErrorMessage,");
        sb.AppendLine("ErrorCode = action.ErrorCode");
        sb.CloseBrace();
        sb.AppendLine(";");
        sb.CloseBrace();
        sb.CloseBrace();
        context.AddSource($"{reducerName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    ///     Generates all reducers for a saga.
    /// </summary>
    private static void GenerateReducers(
        SourceProductionContext context,
        SagaReducerInfo saga
    )
    {
        GenerateExecutingReducer(context, saga);
        GenerateSucceededReducer(context, saga);
        GenerateFailedReducer(context, saga);
    }

    /// <summary>
    ///     Generates the succeeded reducer.
    /// </summary>
    private static void GenerateSucceededReducer(
        SourceProductionContext context,
        SagaReducerInfo saga
    )
    {
        string reducerName = $"Start{saga.SagaName}SagaSucceededReducer";
        string actionName = $"Start{saga.SagaName}SagaSucceededAction";
        string stateName = $"{saga.SagaName}SagaFeatureState";
        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing("Mississippi.Reservoir.Abstractions");
        sb.AppendUsing("Mississippi.Reservoir.Abstractions.Actions");
        sb.AppendUsing(saga.ActionsNamespace);
        sb.AppendUsing(saga.StateNamespace);
        sb.AppendFileScopedNamespace(saga.ReducersNamespace);
        sb.AppendLine();
        sb.AppendSummary($"Reducer for {actionName}.");
        sb.AppendGeneratedCodeAttribute(GeneratorName);
        sb.AppendLine($"internal sealed class {reducerName} : ActionReducerBase<{actionName}, {stateName}>");
        sb.OpenBrace();
        sb.AppendLine("/// <inheritdoc />");
        sb.AppendLine($"public override {stateName} Reduce(");
        sb.IncreaseIndent();
        sb.AppendLine($"{stateName} state,");
        sb.AppendLine($"{actionName} action");
        sb.DecreaseIndent();
        sb.AppendLine(")");
        sb.OpenBrace();
        sb.AppendLine("return state with");
        sb.OpenBrace();
        sb.AppendLine("IsExecuting = false,");
        sb.AppendLine("ExecutingSagaId = null,");
        sb.AppendLine("LastStartedSagaId = action.SagaId");
        sb.CloseBrace();
        sb.AppendLine(";");
        sb.CloseBrace();
        sb.CloseBrace();
        context.AddSource($"{reducerName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    ///     Gets all referenced assemblies from the compilation.
    /// </summary>
    private static IEnumerable<IAssemblySymbol> GetReferencedAssemblies(
        Compilation compilation
    )
    {
        yield return compilation.Assembly;
        foreach (IAssemblySymbol assemblySymbol in compilation.References
                     .Select(reference => compilation.GetAssemblyOrModuleSymbol(reference))
                     .OfType<IAssemblySymbol>())
        {
            yield return assemblySymbol;
        }
    }

    /// <summary>
    ///     Gets saga information from the compilation.
    /// </summary>
    private static List<SagaReducerInfo> GetSagasFromCompilation(
        Compilation compilation,
        string targetRootNamespace
    )
    {
        List<SagaReducerInfo> sagas = [];
        INamedTypeSymbol? sagaAttrSymbol = compilation.GetTypeByMetadataName(GenerateSagaEndpointsAttributeFullName);
        INamedTypeSymbol? sagaDefinitionSymbol = compilation.GetTypeByMetadataName(ISagaDefinitionFullName);
        if (sagaAttrSymbol is null || sagaDefinitionSymbol is null)
        {
            return sagas;
        }

        foreach (IAssemblySymbol referencedAssembly in GetReferencedAssemblies(compilation))
        {
            FindSagasInNamespace(
                referencedAssembly.GlobalNamespace,
                sagaAttrSymbol,
                sagaDefinitionSymbol,
                targetRootNamespace,
                sagas);
        }

        return sagas;
    }

    /// <summary>
    ///     Tries to get saga reducer info from a type symbol.
    /// </summary>
    private static SagaReducerInfo? TryGetSagaReducerInfo(
        INamedTypeSymbol typeSymbol,
        INamedTypeSymbol sagaAttrSymbol,
        INamedTypeSymbol sagaDefinitionSymbol,
        string targetRootNamespace
    )
    {
        AttributeData? attr = typeSymbol.GetAttributes()
            .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, sagaAttrSymbol));
        if (attr is null)
        {
            return null;
        }

        bool implementsSagaDefinition = typeSymbol.AllInterfaces.Any(i =>
            SymbolEqualityComparer.Default.Equals(i, sagaDefinitionSymbol));
        if (!implementsSagaDefinition)
        {
            return null;
        }

        TypedConstant inputTypeArg = attr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "InputType").Value;
        if (inputTypeArg.IsNull || inputTypeArg.Value is not INamedTypeSymbol)
        {
            return null;
        }

        // Extract saga name
        string sagaName = typeSymbol.Name;
        if (sagaName.EndsWith("SagaState", StringComparison.Ordinal))
        {
            sagaName = sagaName.Substring(0, sagaName.Length - "SagaState".Length);
        }
        else if (sagaName.EndsWith("Saga", StringComparison.Ordinal))
        {
            sagaName = sagaName.Substring(0, sagaName.Length - "Saga".Length);
        }

        string domainNamespace = typeSymbol.ContainingNamespace.ToDisplayString();
        string actionsNamespace = NamingConventions.GetClientSagaFeatureNamespace(
            domainNamespace,
            targetRootNamespace,
            "Actions");
        string stateNamespace = NamingConventions.GetClientSagaFeatureNamespace(
            domainNamespace,
            targetRootNamespace,
            "State");
        string reducersNamespace = NamingConventions.GetClientSagaFeatureNamespace(
            domainNamespace,
            targetRootNamespace,
            "Reducers");
        return new(sagaName, actionsNamespace, stateNamespace, reducersNamespace);
    }

    /// <inheritdoc />
    public void Initialize(
        IncrementalGeneratorInitializationContext context
    )
    {
        IncrementalValueProvider<(Compilation Compilation, AnalyzerConfigOptionsProvider Options)>
            compilationAndOptions = context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider);
        IncrementalValueProvider<List<SagaReducerInfo>> sagasProvider = compilationAndOptions.Select((
            source,
            _
        ) =>
        {
            source.Options.GlobalOptions.TryGetValue(
                TargetNamespaceResolver.RootNamespaceProperty,
                out string? rootNamespace);
            source.Options.GlobalOptions.TryGetValue(
                TargetNamespaceResolver.AssemblyNameProperty,
                out string? assemblyName);
            string targetRootNamespace = TargetNamespaceResolver.GetTargetRootNamespace(
                rootNamespace,
                assemblyName,
                source.Compilation);
            return GetSagasFromCompilation(source.Compilation, targetRootNamespace);
        });
        context.RegisterSourceOutput(
            sagasProvider,
            static (
                spc,
                sagas
            ) =>
            {
                foreach (SagaReducerInfo saga in sagas)
                {
                    GenerateReducers(spc, saga);
                }
            });
    }

    /// <summary>
    ///     Information about a saga for reducer generation.
    /// </summary>
    private sealed class SagaReducerInfo
    {
        public SagaReducerInfo(
            string sagaName,
            string actionsNamespace,
            string stateNamespace,
            string reducersNamespace
        )
        {
            SagaName = sagaName;
            ActionsNamespace = actionsNamespace;
            StateNamespace = stateNamespace;
            ReducersNamespace = reducersNamespace;
        }

        public string ActionsNamespace { get; }

        public string ReducersNamespace { get; }

        public string SagaName { get; }

        public string StateNamespace { get; }
    }
}