using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

using Mississippi.Inlet.Generators.Core.Analysis;
using Mississippi.Inlet.Generators.Core.Emit;
using Mississippi.Inlet.Generators.Core.Naming;


namespace Mississippi.Inlet.Client.Generators;

/// <summary>
///     Generates client-side saga mappers for sagas marked with [GenerateSagaEndpoints].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SagaClientMappersGenerator : IIncrementalGenerator
{
    private const string GenerateSagaEndpointsAttributeFullName =
        "Mississippi.Inlet.Generators.Abstractions.GenerateSagaEndpointsAttribute";

    private const string GeneratorName = "SagaClientMappersGenerator";

    private const string ISagaDefinitionFullName = "Mississippi.EventSourcing.Sagas.Abstractions.ISagaDefinition";

    /// <summary>
    ///     Recursively finds sagas in a namespace.
    /// </summary>
    private static void FindSagasInNamespace(
        INamespaceSymbol namespaceSymbol,
        INamedTypeSymbol sagaAttrSymbol,
        INamedTypeSymbol sagaDefinitionSymbol,
        string targetRootNamespace,
        List<SagaClientInfo> sagas
    )
    {
        foreach (INamedTypeSymbol typeSymbol in namespaceSymbol.GetTypeMembers())
        {
            SagaClientInfo? info = TryGetSagaClientInfo(
                typeSymbol,
                sagaAttrSymbol,
                sagaDefinitionSymbol,
                targetRootNamespace);
            if (info is not null)
            {
                sagas.Add(info);
            }
        }

        foreach (INamespaceSymbol childNs in namespaceSymbol.GetNamespaceMembers())
        {
            FindSagasInNamespace(childNs, sagaAttrSymbol, sagaDefinitionSymbol, targetRootNamespace, sagas);
        }
    }

    /// <summary>
    ///     Generates the mapper for a saga.
    /// </summary>
    private static void GenerateMapper(
        SourceProductionContext context,
        SagaClientInfo saga
    )
    {
        string mapperName = $"Start{saga.SagaName}SagaActionMapper";
        string actionName = $"Start{saga.SagaName}SagaAction";
        string dtoName = $"Start{saga.SagaName}SagaDto";
        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing("System");
        sb.AppendUsing("Mississippi.Common.Abstractions.Mapping");
        sb.AppendUsing(saga.ActionsNamespace);
        sb.AppendUsing(saga.DtosNamespace);
        sb.AppendFileScopedNamespace(saga.MappersNamespace);
        sb.AppendLine();
        sb.AppendSummary($"Maps {actionName} to {dtoName}.");
        sb.AppendGeneratedCodeAttribute(GeneratorName);
        sb.AppendLine($"internal sealed class {mapperName} : IMapper<{actionName}, {dtoName}>");
        sb.OpenBrace();

        // Map method
        sb.AppendLine("/// <inheritdoc />");
        sb.AppendLine($"public {dtoName} Map(");
        sb.IncreaseIndent();
        sb.AppendLine($"{actionName} input");
        sb.DecreaseIndent();
        sb.AppendLine(")");
        sb.OpenBrace();
        sb.AppendLine("ArgumentNullException.ThrowIfNull(input);");
        sb.AppendLine();
        sb.AppendLine($"return new {dtoName}");
        sb.OpenBrace();
        sb.AppendLines(saga.InputProperties.Select(prop => $"{prop.Name} = input.{prop.Name},"));
        sb.AppendLine("CorrelationId = input.CorrelationId");
        sb.CloseBrace();
        sb.AppendLine(";");
        sb.CloseBrace();
        sb.CloseBrace();
        context.AddSource($"{mapperName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    ///     Gets all referenced assemblies from the compilation.
    /// </summary>
    private static IEnumerable<IAssemblySymbol> GetReferencedAssemblies(
        Compilation compilation
    )
    {
        yield return compilation.Assembly;
        foreach (IAssemblySymbol assemblySymbol in compilation.References
                     .Select(reference => compilation.GetAssemblyOrModuleSymbol(reference))
                     .OfType<IAssemblySymbol>())
        {
            yield return assemblySymbol;
        }
    }

    /// <summary>
    ///     Gets saga information from the compilation.
    /// </summary>
    private static List<SagaClientInfo> GetSagasFromCompilation(
        Compilation compilation,
        string targetRootNamespace
    )
    {
        List<SagaClientInfo> sagas = [];
        INamedTypeSymbol? sagaAttrSymbol = compilation.GetTypeByMetadataName(GenerateSagaEndpointsAttributeFullName);
        INamedTypeSymbol? sagaDefinitionSymbol = compilation.GetTypeByMetadataName(ISagaDefinitionFullName);
        if (sagaAttrSymbol is null || sagaDefinitionSymbol is null)
        {
            return sagas;
        }

        foreach (IAssemblySymbol referencedAssembly in GetReferencedAssemblies(compilation))
        {
            FindSagasInNamespace(
                referencedAssembly.GlobalNamespace,
                sagaAttrSymbol,
                sagaDefinitionSymbol,
                targetRootNamespace,
                sagas);
        }

        return sagas;
    }

    /// <summary>
    ///     Tries to get saga client info from a type symbol.
    /// </summary>
    private static SagaClientInfo? TryGetSagaClientInfo(
        INamedTypeSymbol typeSymbol,
        INamedTypeSymbol sagaAttrSymbol,
        INamedTypeSymbol sagaDefinitionSymbol,
        string targetRootNamespace
    )
    {
        AttributeData? attr = typeSymbol.GetAttributes()
            .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, sagaAttrSymbol));
        if (attr is null)
        {
            return null;
        }

        bool implementsSagaDefinition = typeSymbol.AllInterfaces.Any(i =>
            SymbolEqualityComparer.Default.Equals(i, sagaDefinitionSymbol));
        if (!implementsSagaDefinition)
        {
            return null;
        }

        TypedConstant inputTypeArg = attr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "InputType").Value;
        if (inputTypeArg.IsNull || inputTypeArg.Value is not INamedTypeSymbol inputTypeSymbol)
        {
            return null;
        }

        // Extract saga name
        string sagaName = typeSymbol.Name;
        if (sagaName.EndsWith("SagaState", StringComparison.Ordinal))
        {
            sagaName = sagaName.Substring(0, sagaName.Length - "SagaState".Length);
        }
        else if (sagaName.EndsWith("Saga", StringComparison.Ordinal))
        {
            sagaName = sagaName.Substring(0, sagaName.Length - "Saga".Length);
        }

        string stateNamespace = typeSymbol.ContainingNamespace.ToDisplayString();
        string actionsNamespace = NamingConventions.GetClientSagaFeatureNamespace(
            stateNamespace,
            targetRootNamespace,
            "Actions");
        string dtosNamespace = NamingConventions.GetClientSagaFeatureNamespace(
            stateNamespace,
            targetRootNamespace,
            "Dtos");
        string mappersNamespace = NamingConventions.GetClientSagaFeatureNamespace(
            stateNamespace,
            targetRootNamespace,
            "Mappers");

        // Extract input properties
        PropertyModel[] inputProperties = inputTypeSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => (p.DeclaredAccessibility == Accessibility.Public) && p.GetMethod is not null)
            .Select(p => new PropertyModel(p))
            .ToArray();
        return new(sagaName, actionsNamespace, dtosNamespace, mappersNamespace, inputProperties);
    }

    /// <inheritdoc />
    public void Initialize(
        IncrementalGeneratorInitializationContext context
    )
    {
        IncrementalValueProvider<(Compilation Compilation, AnalyzerConfigOptionsProvider Options)>
            compilationAndOptions = context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider);
        IncrementalValueProvider<List<SagaClientInfo>> sagasProvider = compilationAndOptions.Select((
            source,
            _
        ) =>
        {
            source.Options.GlobalOptions.TryGetValue(
                TargetNamespaceResolver.RootNamespaceProperty,
                out string? rootNamespace);
            source.Options.GlobalOptions.TryGetValue(
                TargetNamespaceResolver.AssemblyNameProperty,
                out string? assemblyName);
            string targetRootNamespace = TargetNamespaceResolver.GetTargetRootNamespace(
                rootNamespace,
                assemblyName,
                source.Compilation);
            return GetSagasFromCompilation(source.Compilation, targetRootNamespace);
        });
        context.RegisterSourceOutput(
            sagasProvider,
            static (
                spc,
                sagas
            ) =>
            {
                foreach (SagaClientInfo saga in sagas)
                {
                    GenerateMapper(spc, saga);
                }
            });
    }

    /// <summary>
    ///     Information about a saga for client mapper generation.
    /// </summary>
    private sealed class SagaClientInfo
    {
        public SagaClientInfo(
            string sagaName,
            string actionsNamespace,
            string dtosNamespace,
            string mappersNamespace,
            PropertyModel[] inputProperties
        )
        {
            SagaName = sagaName;
            ActionsNamespace = actionsNamespace;
            DtosNamespace = dtosNamespace;
            MappersNamespace = mappersNamespace;
            InputProperties = inputProperties;
        }

        public string ActionsNamespace { get; }

        public string DtosNamespace { get; }

        public PropertyModel[] InputProperties { get; }

        public string MappersNamespace { get; }

        public string SagaName { get; }
    }
}