using System.Collections.Generic;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

using Mississippi.Inlet.Generators.Core.Emit;


namespace Mississippi.Inlet.Client.Generators;

/// <summary>
///     Generates client-side feature registration classes for sagas marked with [GenerateSagaEndpoints].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SagaClientRegistrationGenerator : IIncrementalGenerator
{
    private static void GenerateRegistration(
        SourceProductionContext context,
        SagaClientGeneratorHelper.SagaClientInfo saga
    )
    {
        string registrationTypeName = $"{saga.SagaName}SagaFeatureRegistration";
        string stateTypeName = $"{saga.SagaName}SagaState";
        string reducersTypeName = $"{saga.SagaName}SagaReducers";
        string actionPrefix = $"Start{saga.SagaName}Saga";
        string methodName = $"Add{saga.SagaName}SagaFeature";
        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing("Mississippi.Common.Abstractions.Mapping");
        sb.AppendUsing("Mississippi.Reservoir.Abstractions.Builders");
        sb.AppendLine();
        sb.AppendLine($"using {saga.ActionsNamespace};");
        sb.AppendLine($"using {saga.DtosNamespace};");
        sb.AppendLine($"using {saga.ActionEffectsNamespace};");
        sb.AppendLine($"using {saga.MappersNamespace};");
        sb.AppendLine($"using {saga.ReducersNamespace};");
        sb.AppendLine($"using {saga.StateNamespace};");
        sb.AppendFileScopedNamespace(saga.FeatureRootNamespace);
        sb.AppendLine();
        sb.AppendSummary($"Extension methods for registering the {saga.SagaName} saga feature.");
        sb.AppendLine("/// <remarks>");
        sb.AppendLine($"///     This feature handles saga start requests for the {saga.SagaName} saga.");
        sb.AppendLine("/// </remarks>");
        sb.AppendGeneratedCodeAttribute("SagaClientRegistrationGenerator");
        sb.AppendLine($"internal static class {registrationTypeName}");
        sb.OpenBrace();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"///     Adds the {saga.SagaName} saga feature to the Reservoir builder.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <param name=\"builder\">The Reservoir builder.</param>");
        sb.AppendLine("/// <returns>The Reservoir builder for chaining.</returns>");
        sb.AppendLine($"public static IReservoirBuilder {methodName}(");
        sb.IncreaseIndent();
        sb.AppendLine("this IReservoirBuilder builder");
        sb.DecreaseIndent();
        sb.AppendLine(")");
        sb.OpenBrace();
        sb.AppendLine("// Mappers (Action → DTO)");
        sb.AppendLine("builder.ConfigureServices(services =>");
        sb.OpenBrace();
        sb.AppendLine(
            $"services.AddMapper<{actionPrefix}Action, {actionPrefix}RequestDto, {actionPrefix}ActionMapper>();");
        sb.CloseBrace();
        sb.AppendLine(");");
        sb.AppendLine();
        sb.AppendLine($"builder.AddFeature<{stateTypeName}>(featureBuilder =>");
        sb.OpenBrace();
        sb.AppendLine($"// Reducers - {actionPrefix}");
        sb.AppendLine($"featureBuilder.AddReducer<{actionPrefix}ExecutingAction>(");
        sb.IncreaseIndent();
        sb.AppendLine($"{reducersTypeName}.{actionPrefix}Executing);");
        sb.DecreaseIndent();
        sb.AppendLine($"featureBuilder.AddReducer<{actionPrefix}SucceededAction>(");
        sb.IncreaseIndent();
        sb.AppendLine($"{reducersTypeName}.{actionPrefix}Succeeded);");
        sb.DecreaseIndent();
        sb.AppendLine($"featureBuilder.AddReducer<{actionPrefix}FailedAction>(");
        sb.IncreaseIndent();
        sb.AppendLine($"{reducersTypeName}.{actionPrefix}Failed);");
        sb.DecreaseIndent();
        sb.AppendLine();
        sb.AppendLine("// Action Effects");
        sb.AppendLine($"featureBuilder.AddActionEffect<{actionPrefix}ActionEffect>();");
        sb.CloseBrace();
        sb.AppendLine(");");
        sb.AppendLine();
        sb.AppendLine("return builder;");
        sb.CloseBrace();
        sb.CloseBrace();
        context.AddSource($"{registrationTypeName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <inheritdoc />
    public void Initialize(
        IncrementalGeneratorInitializationContext context
    )
    {
        IncrementalValueProvider<(Compilation Compilation, AnalyzerConfigOptionsProvider Options)>
            compilationAndOptions = context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider);
        IncrementalValueProvider<List<SagaClientGeneratorHelper.SagaClientInfo>> sagasProvider =
            compilationAndOptions.Select((
                source,
                _
            ) => SagaClientGeneratorHelper.GetSagasFromCompilation(source.Compilation, source.Options));
        context.RegisterSourceOutput(
            sagasProvider,
            static (
                spc,
                sagas
            ) =>
            {
                foreach (SagaClientGeneratorHelper.SagaClientInfo saga in sagas)
                {
                    GenerateRegistration(spc, saga);
                }
            });
    }
}