using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

using Mississippi.Inlet.Generators.Core.Analysis;
using Mississippi.Inlet.Generators.Core.Emit;
using Mississippi.Inlet.Generators.Core.Naming;


namespace Mississippi.Inlet.Client.Generators;

/// <summary>
///     Generates client-side Flux actions for sagas marked with [GenerateSagaEndpoints].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SagaClientActionsGenerator : IIncrementalGenerator
{
    private const string ActionsNamespace = "Mississippi.Inlet.Client.Abstractions.Actions";

    private const string CommandIdParamComment =
        "/// <param name=\"CommandId\">The unique command invocation identifier.</param>";

    private const string CommandIdParameter = "string commandId,";

    private const string GeneratorName = "SagaClientActionsGenerator";

    private const string InheritdocComment = "/// <inheritdoc />";

    private const string SystemNamespace = "System";

    private const string TimestampParameter = "DateTimeOffset timestamp";

    private static void GenerateActions(
        SourceProductionContext context,
        SagaClientGeneratorHelper.SagaClientInfo saga
    )
    {
        GeneratePrimaryAction(context, saga);
        GenerateExecutingAction(context, saga);
        GenerateSucceededAction(context, saga);
        GenerateFailedAction(context, saga);
        GenerateResumePrimaryAction(context, saga);
        GenerateResumeExecutingAction(context, saga);
        GenerateResumeSucceededAction(context, saga);
        GenerateResumeFailedAction(context, saga);
    }

    private static void GenerateExecutingAction(
        SourceProductionContext context,
        SagaClientGeneratorHelper.SagaClientInfo saga
    )
    {
        string actionName = $"Start{saga.SagaName}SagaExecutingAction";
        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing(SystemNamespace);
        sb.AppendUsing(ActionsNamespace);
        sb.AppendFileScopedNamespace(saga.ActionsNamespace);
        sb.AppendLine();
        sb.AppendSummary($"Action dispatched when the {saga.SagaName} saga start request is executing.");
        sb.AppendLine(CommandIdParamComment);
        sb.AppendLine("/// <param name=\"CommandType\">The name of the command type.</param>");
        sb.AppendLine("/// <param name=\"Timestamp\">The timestamp when the request started.</param>");
        sb.AppendGeneratedCodeAttribute(GeneratorName);
        sb.AppendLine(
            $"internal sealed record {actionName}(string CommandId, string CommandType, DateTimeOffset Timestamp)");
        sb.IncreaseIndent();
        sb.AppendLine($": ICommandExecutingAction<{actionName}>");
        sb.DecreaseIndent();
        sb.OpenBrace();
        sb.AppendLine(InheritdocComment);
        sb.AppendLine($"public static {actionName} Create(");
        sb.IncreaseIndent();
        sb.AppendLine(CommandIdParameter);
        sb.AppendLine("string commandType,");
        sb.AppendLine(TimestampParameter);
        sb.DecreaseIndent();
        sb.AppendLine(") =>");
        sb.IncreaseIndent();
        sb.AppendLine("new(commandId, commandType, timestamp);");
        sb.DecreaseIndent();
        sb.CloseBrace();
        context.AddSource($"{actionName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateFailedAction(
        SourceProductionContext context,
        SagaClientGeneratorHelper.SagaClientInfo saga
    )
    {
        string actionName = $"Start{saga.SagaName}SagaFailedAction";
        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing(SystemNamespace);
        sb.AppendUsing(ActionsNamespace);
        sb.AppendFileScopedNamespace(saga.ActionsNamespace);
        sb.AppendLine();
        sb.AppendSummary($"Action dispatched when the {saga.SagaName} saga start request fails.");
        sb.AppendLine(CommandIdParamComment);
        sb.AppendLine("/// <param name=\"ErrorCode\">The error code.</param>");
        sb.AppendLine("/// <param name=\"ErrorMessage\">The error message.</param>");
        sb.AppendLine("/// <param name=\"Timestamp\">The timestamp when the request failed.</param>");
        sb.AppendGeneratedCodeAttribute(GeneratorName);
        sb.AppendLine($"internal sealed record {actionName}(");
        sb.IncreaseIndent();
        sb.AppendLine("string CommandId,");
        sb.AppendLine("string? ErrorCode,");
        sb.AppendLine("string? ErrorMessage,");
        sb.AppendLine("DateTimeOffset Timestamp");
        sb.DecreaseIndent();
        sb.AppendLine(") : ICommandFailedAction<" + actionName + ">");
        sb.OpenBrace();
        sb.AppendLine(InheritdocComment);
        sb.AppendLine($"public static {actionName} Create(");
        sb.IncreaseIndent();
        sb.AppendLine(CommandIdParameter);
        sb.AppendLine("string? errorCode,");
        sb.AppendLine("string? errorMessage,");
        sb.AppendLine(TimestampParameter);
        sb.DecreaseIndent();
        sb.AppendLine(") =>");
        sb.IncreaseIndent();
        sb.AppendLine("new(commandId, errorCode, errorMessage, timestamp);");
        sb.DecreaseIndent();
        sb.CloseBrace();
        context.AddSource($"{actionName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GeneratePrimaryAction(
        SourceProductionContext context,
        SagaClientGeneratorHelper.SagaClientInfo saga
    )
    {
        string actionName = $"Start{saga.SagaName}SagaAction";
        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing(SystemNamespace);
        sb.AppendUsing(ActionsNamespace);
        sb.AppendFileScopedNamespace(saga.ActionsNamespace);
        sb.AppendLine();
        sb.AppendSummary($"Action dispatched to start the {saga.SagaName} saga.");
        sb.AppendLine("/// <remarks>");
        sb.AppendLine($"///     Derived from saga input: <c>{saga.InputTypeName}</c>.");
        sb.AppendLine("/// </remarks>");
        sb.AppendLine("/// <param name=\"SagaId\">The saga identifier.</param>");
        saga.InputProperties.ToList()
            .ForEach(prop => sb.AppendLine(
                $"/// <param name=\"{prop.Name}\">The {NamingConventions.ToCamelCase(prop.Name)} value.</param>"));
        sb.AppendLine("/// <param name=\"CorrelationId\">The optional correlation identifier.</param>");
        sb.AppendGeneratedCodeAttribute(GeneratorName);
        StringBuilder parameters = new();
        parameters.Append("Guid SagaId");
        foreach (PropertyModel prop in saga.InputProperties)
        {
            parameters.Append(", ").Append(prop.SourceTypeName).Append(' ').Append(prop.Name);
        }

        parameters.Append(", string? CorrelationId");
        sb.AppendLine($"internal sealed record {actionName}({parameters}) : ICommandAction");
        sb.OpenBrace();
        sb.AppendLine(InheritdocComment);
        sb.AppendLine("public string EntityId => SagaId.ToString();");
        sb.CloseBrace();
        context.AddSource($"{actionName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateResumeExecutingAction(
        SourceProductionContext context,
        SagaClientGeneratorHelper.SagaClientInfo saga
    )
    {
        string actionName = $"Resume{saga.SagaName}SagaExecutingAction";
        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing(SystemNamespace);
        sb.AppendUsing(ActionsNamespace);
        sb.AppendFileScopedNamespace(saga.ActionsNamespace);
        sb.AppendLine();
        sb.AppendSummary($"Action dispatched when the {saga.SagaName} saga manual resume request is executing.");
        sb.AppendLine(CommandIdParamComment);
        sb.AppendLine("/// <param name=\"CommandType\">The name of the command type.</param>");
        sb.AppendLine("/// <param name=\"Timestamp\">The timestamp when the request started.</param>");
        sb.AppendGeneratedCodeAttribute(GeneratorName);
        sb.AppendLine(
            $"internal sealed record {actionName}(string CommandId, string CommandType, DateTimeOffset Timestamp)");
        sb.IncreaseIndent();
        sb.AppendLine($": ICommandExecutingAction<{actionName}>");
        sb.DecreaseIndent();
        sb.OpenBrace();
        sb.AppendLine(InheritdocComment);
        sb.AppendLine($"public static {actionName} Create(");
        sb.IncreaseIndent();
        sb.AppendLine(CommandIdParameter);
        sb.AppendLine("string commandType,");
        sb.AppendLine(TimestampParameter);
        sb.DecreaseIndent();
        sb.AppendLine(") =>");
        sb.IncreaseIndent();
        sb.AppendLine("new(commandId, commandType, timestamp);");
        sb.DecreaseIndent();
        sb.CloseBrace();
        context.AddSource($"{actionName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateResumeFailedAction(
        SourceProductionContext context,
        SagaClientGeneratorHelper.SagaClientInfo saga
    )
    {
        string actionName = $"Resume{saga.SagaName}SagaFailedAction";
        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing(SystemNamespace);
        sb.AppendUsing(ActionsNamespace);
        sb.AppendFileScopedNamespace(saga.ActionsNamespace);
        sb.AppendLine();
        sb.AppendSummary($"Action dispatched when the {saga.SagaName} saga manual resume request fails.");
        sb.AppendLine(CommandIdParamComment);
        sb.AppendLine("/// <param name=\"ErrorCode\">The error code.</param>");
        sb.AppendLine("/// <param name=\"ErrorMessage\">The error message.</param>");
        sb.AppendLine("/// <param name=\"Timestamp\">The timestamp when the request failed.</param>");
        sb.AppendGeneratedCodeAttribute(GeneratorName);
        sb.AppendLine($"internal sealed record {actionName}(");
        sb.IncreaseIndent();
        sb.AppendLine("string CommandId,");
        sb.AppendLine("string? ErrorCode,");
        sb.AppendLine("string? ErrorMessage,");
        sb.AppendLine("DateTimeOffset Timestamp");
        sb.DecreaseIndent();
        sb.AppendLine(") : ICommandFailedAction<" + actionName + ">");
        sb.OpenBrace();
        sb.AppendLine(InheritdocComment);
        sb.AppendLine($"public static {actionName} Create(");
        sb.IncreaseIndent();
        sb.AppendLine(CommandIdParameter);
        sb.AppendLine("string? errorCode,");
        sb.AppendLine("string? errorMessage,");
        sb.AppendLine(TimestampParameter);
        sb.DecreaseIndent();
        sb.AppendLine(") =>");
        sb.IncreaseIndent();
        sb.AppendLine("new(commandId, errorCode, errorMessage, timestamp);");
        sb.DecreaseIndent();
        sb.CloseBrace();
        context.AddSource($"{actionName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateResumePrimaryAction(
        SourceProductionContext context,
        SagaClientGeneratorHelper.SagaClientInfo saga
    )
    {
        string actionName = $"Resume{saga.SagaName}SagaAction";
        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing(SystemNamespace);
        sb.AppendUsing(ActionsNamespace);
        sb.AppendFileScopedNamespace(saga.ActionsNamespace);
        sb.AppendLine();
        sb.AppendSummary($"Action dispatched to request a manual resume for the {saga.SagaName} saga.");
        sb.AppendLine("/// <param name=\"SagaId\">The saga identifier.</param>");
        sb.AppendGeneratedCodeAttribute(GeneratorName);
        sb.AppendLine($"internal sealed record {actionName}(Guid SagaId) : ICommandAction");
        sb.OpenBrace();
        sb.AppendLine(InheritdocComment);
        sb.AppendLine("public string EntityId => SagaId.ToString();");
        sb.CloseBrace();
        context.AddSource($"{actionName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateResumeSucceededAction(
        SourceProductionContext context,
        SagaClientGeneratorHelper.SagaClientInfo saga
    )
    {
        string actionName = $"Resume{saga.SagaName}SagaSucceededAction";
        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing(SystemNamespace);
        sb.AppendUsing("Mississippi.DomainModeling.Abstractions");
        sb.AppendUsing(ActionsNamespace);
        sb.AppendFileScopedNamespace(saga.ActionsNamespace);
        sb.AppendLine();
        sb.AppendSummary($"Action dispatched when the {saga.SagaName} saga manual resume request succeeds.");
        sb.AppendLine(CommandIdParamComment);
        sb.AppendLine("/// <param name=\"Response\">The typed manual-resume response.</param>");
        sb.AppendLine("/// <param name=\"Timestamp\">The timestamp when the request succeeded.</param>");
        sb.AppendGeneratedCodeAttribute(GeneratorName);
        sb.AppendLine(
            $"internal sealed record {actionName}(string CommandId, SagaResumeResponse Response, DateTimeOffset Timestamp) : ICommandSucceededAction");
        sb.OpenBrace();
        sb.AppendLine($"public static {actionName} Create(");
        sb.IncreaseIndent();
        sb.AppendLine(CommandIdParameter);
        sb.AppendLine("SagaResumeResponse response,");
        sb.AppendLine(TimestampParameter);
        sb.DecreaseIndent();
        sb.AppendLine(") =>");
        sb.IncreaseIndent();
        sb.AppendLine("new(commandId, response, timestamp);");
        sb.DecreaseIndent();
        sb.CloseBrace();
        context.AddSource($"{actionName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateSucceededAction(
        SourceProductionContext context,
        SagaClientGeneratorHelper.SagaClientInfo saga
    )
    {
        string actionName = $"Start{saga.SagaName}SagaSucceededAction";
        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing(SystemNamespace);
        sb.AppendUsing(ActionsNamespace);
        sb.AppendFileScopedNamespace(saga.ActionsNamespace);
        sb.AppendLine();
        sb.AppendSummary($"Action dispatched when the {saga.SagaName} saga start request succeeds.");
        sb.AppendLine(CommandIdParamComment);
        sb.AppendLine("/// <param name=\"Timestamp\">The timestamp when the request succeeded.</param>");
        sb.AppendGeneratedCodeAttribute(GeneratorName);
        sb.AppendLine(
            $"internal sealed record {actionName}(string CommandId, DateTimeOffset Timestamp) : ICommandSucceededAction<{actionName}>");
        sb.OpenBrace();
        sb.AppendLine(InheritdocComment);
        sb.AppendLine($"public static {actionName} Create(");
        sb.IncreaseIndent();
        sb.AppendLine(CommandIdParameter);
        sb.AppendLine(TimestampParameter);
        sb.DecreaseIndent();
        sb.AppendLine(") =>");
        sb.IncreaseIndent();
        sb.AppendLine("new(commandId, timestamp);");
        sb.DecreaseIndent();
        sb.CloseBrace();
        context.AddSource($"{actionName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <inheritdoc />
    public void Initialize(
        IncrementalGeneratorInitializationContext context
    )
    {
        IncrementalValueProvider<(Compilation Compilation, AnalyzerConfigOptionsProvider Options)>
            compilationAndOptions = context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider);
        IncrementalValueProvider<List<SagaClientGeneratorHelper.SagaClientInfo>> sagasProvider =
            compilationAndOptions.Select((
                source,
                _
            ) => SagaClientGeneratorHelper.GetSagasFromCompilation(source.Compilation, source.Options));
        context.RegisterSourceOutput(
            sagasProvider,
            static (
                spc,
                sagas
            ) =>
            {
                foreach (SagaClientGeneratorHelper.SagaClientInfo saga in sagas)
                {
                    GenerateActions(spc, saga);
                }
            });
    }
}