using System.Collections.Generic;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using Mississippi.Inlet.Generators.Core.Emit;

namespace Mississippi.Inlet.Client.Generators;

/// <summary>
///     Generates client-side feature state records for sagas marked with [GenerateSagaEndpoints].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SagaClientStateGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(
        IncrementalGeneratorInitializationContext context
    )
    {
        IncrementalValueProvider<(Compilation Compilation, AnalyzerConfigOptionsProvider Options)>
            compilationAndOptions = context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider);
        IncrementalValueProvider<List<SagaClientGeneratorHelper.SagaClientInfo>> sagasProvider =
            compilationAndOptions.Select((source, _) =>
                SagaClientGeneratorHelper.GetSagasFromCompilation(source.Compilation, source.Options));
        context.RegisterSourceOutput(sagasProvider, static (spc, sagas) =>
        {
            foreach (SagaClientGeneratorHelper.SagaClientInfo saga in sagas)
            {
                GenerateState(spc, saga);
            }
        });
    }

    private static void GenerateState(
        SourceProductionContext context,
        SagaClientGeneratorHelper.SagaClientInfo saga
    )
    {
        string stateTypeName = $"{saga.SagaName}SagaState";
        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing("Mississippi.Inlet.Client.Abstractions.State");
        sb.AppendFileScopedNamespace(saga.StateNamespace);
        sb.AppendLine();
        sb.AppendSummary($"Feature state for {saga.SagaName} saga start execution.");
        sb.AppendLine("/// <remarks>");
        sb.AppendLine("///     <para>");
        sb.AppendLine(
            "///         This state tracks saga start requests (executing, success, failure) via command-style tracking.");
        sb.AppendLine("///     </para>");
        sb.AppendLine("/// </remarks>");
        sb.AppendGeneratedCodeAttribute("SagaClientStateGenerator");
        sb.AppendLine($"internal sealed record {stateTypeName} : AggregateCommandStateBase, IAggregateCommandState");
        sb.OpenBrace();
        sb.AppendLine("/// <inheritdoc />");
        sb.AppendLine($"public static string FeatureKey => \"{saga.FeatureKey}\";");
        sb.CloseBrace();
        context.AddSource($"{stateTypeName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
