using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

using Mississippi.Inlet.Generators.Core.Emit;
using Mississippi.Inlet.Generators.Core.Naming;


namespace Mississippi.Inlet.Client.Generators;

/// <summary>
///     Generates client-side saga action effects for sagas marked with [GenerateSagaEndpoints].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SagaClientActionEffectsGenerator : IIncrementalGenerator
{
    private const string GenerateSagaEndpointsAttributeFullName =
        "Mississippi.Inlet.Generators.Abstractions.GenerateSagaEndpointsAttribute";

    private const string GeneratorName = "SagaClientActionEffectsGenerator";

    private const string ISagaDefinitionFullName = "Mississippi.EventSourcing.Sagas.Abstractions.ISagaDefinition";

    /// <summary>
    ///     Recursively finds sagas in a namespace.
    /// </summary>
    private static void FindSagasInNamespace(
        INamespaceSymbol namespaceSymbol,
        INamedTypeSymbol sagaAttrSymbol,
        INamedTypeSymbol sagaDefinitionSymbol,
        string targetRootNamespace,
        List<SagaEffectInfo> sagas
    )
    {
        foreach (INamedTypeSymbol typeSymbol in namespaceSymbol.GetTypeMembers())
        {
            SagaEffectInfo? info = TryGetSagaEffectInfo(
                typeSymbol,
                sagaAttrSymbol,
                sagaDefinitionSymbol,
                targetRootNamespace);
            if (info is not null)
            {
                sagas.Add(info);
            }
        }

        foreach (INamespaceSymbol childNs in namespaceSymbol.GetNamespaceMembers())
        {
            FindSagasInNamespace(childNs, sagaAttrSymbol, sagaDefinitionSymbol, targetRootNamespace, sagas);
        }
    }

    /// <summary>
    ///     Generates the action effect for a saga.
    /// </summary>
    private static void GenerateActionEffect(
        SourceProductionContext context,
        SagaEffectInfo saga
    )
    {
        string effectName = $"Start{saga.SagaName}SagaActionEffect";
        string actionName = $"Start{saga.SagaName}SagaAction";
        string dtoName = $"Start{saga.SagaName}SagaDto";
        string stateName = $"{saga.SagaName}SagaFeatureState";
        string executingActionName = $"Start{saga.SagaName}SagaExecutingAction";
        string succeededActionName = $"Start{saga.SagaName}SagaSucceededAction";
        string failedActionName = $"Start{saga.SagaName}SagaFailedAction";
        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing("System");
        sb.AppendUsing("System.Net.Http");
        sb.AppendUsing("Mississippi.Common.Abstractions.Mapping");
        sb.AppendUsing("Mississippi.Inlet.Client.Abstractions.ActionEffects");
        sb.AppendUsing("Mississippi.Reservoir.Abstractions.Actions");
        sb.AppendUsing(saga.ActionsNamespace);
        sb.AppendUsing(saga.DtosNamespace);
        sb.AppendUsing(saga.StateNamespace);
        sb.AppendFileScopedNamespace(saga.EffectsNamespace);
        sb.AppendLine();
        sb.AppendSummary($"Action effect for {actionName}.");
        sb.AppendGeneratedCodeAttribute(GeneratorName);
        sb.AppendLine($"internal sealed class {effectName}");
        sb.IncreaseIndent();
        sb.AppendLine($": SagaActionEffectBase<{actionName}, {stateName}>");
        sb.DecreaseIndent();
        sb.OpenBrace();
        sb.AppendLine($"private IMapper<{actionName}, {dtoName}> Mapper {{ get; }}");
        sb.AppendLine();

        // Constructor
        sb.AppendSummary($"Initializes a new instance of the <see cref=\"{effectName}\" /> class.");
        sb.AppendLine("/// <param name=\"httpClient\">The HTTP client.</param>");
        sb.AppendLine("/// <param name=\"mapper\">The action to DTO mapper.</param>");
        sb.AppendLine("/// <param name=\"timeProvider\">Optional time provider.</param>");
        sb.AppendLine($"public {effectName}(");
        sb.IncreaseIndent();
        sb.AppendLine("HttpClient httpClient,");
        sb.AppendLine($"IMapper<{actionName}, {dtoName}> mapper,");
        sb.AppendLine("TimeProvider? timeProvider = null");
        sb.DecreaseIndent();
        sb.AppendLine(")");
        sb.IncreaseIndent();
        sb.AppendLine(": base(httpClient, timeProvider)");
        sb.DecreaseIndent();
        sb.OpenBrace();
        sb.AppendLine("Mapper = mapper;");
        sb.CloseBrace();
        sb.AppendLine();

        // SagaRoute property
        sb.AppendLine("/// <inheritdoc />");
        sb.AppendLine($"protected override string SagaRoute => \"{saga.SagaRouteKebab}\";");
        sb.AppendLine();
        sb.AppendLine("/// <inheritdoc />");
        sb.AppendLine($"protected override object CreateRequestBody({actionName} action) => Mapper.Map(action);");
        sb.AppendLine();
        sb.AppendLine("/// <inheritdoc />");
        sb.AppendLine(
            "protected override IAction CreateExecutingAction(Guid sagaId, string sagaType, DateTimeOffset timestamp) =>");
        sb.IncreaseIndent();
        sb.AppendLine($"{executingActionName}.Create(sagaId, sagaType, timestamp);");
        sb.DecreaseIndent();
        sb.AppendLine();
        sb.AppendLine("/// <inheritdoc />");
        sb.AppendLine("protected override IAction CreateSucceededAction(Guid sagaId, DateTimeOffset timestamp) =>");
        sb.IncreaseIndent();
        sb.AppendLine($"{succeededActionName}.Create(sagaId, timestamp);");
        sb.DecreaseIndent();
        sb.AppendLine();
        sb.AppendLine("/// <inheritdoc />");
        sb.AppendLine(
            "protected override IAction CreateFailedAction(Guid sagaId, string? errorCode, string errorMessage, DateTimeOffset timestamp) =>");
        sb.IncreaseIndent();
        sb.AppendLine($"{failedActionName}.Create(sagaId, errorCode, errorMessage, timestamp);");
        sb.DecreaseIndent();
        sb.CloseBrace();
        context.AddSource($"{effectName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    ///     Gets all referenced assemblies from the compilation.
    /// </summary>
    private static IEnumerable<IAssemblySymbol> GetReferencedAssemblies(
        Compilation compilation
    )
    {
        yield return compilation.Assembly;
        foreach (IAssemblySymbol assemblySymbol in compilation.References
                     .Select(reference => compilation.GetAssemblyOrModuleSymbol(reference))
                     .OfType<IAssemblySymbol>())
        {
            yield return assemblySymbol;
        }
    }

    /// <summary>
    ///     Gets saga information from the compilation.
    /// </summary>
    private static List<SagaEffectInfo> GetSagasFromCompilation(
        Compilation compilation,
        string targetRootNamespace
    )
    {
        List<SagaEffectInfo> sagas = [];
        INamedTypeSymbol? sagaAttrSymbol = compilation.GetTypeByMetadataName(GenerateSagaEndpointsAttributeFullName);
        INamedTypeSymbol? sagaDefinitionSymbol = compilation.GetTypeByMetadataName(ISagaDefinitionFullName);
        if (sagaAttrSymbol is null || sagaDefinitionSymbol is null)
        {
            return sagas;
        }

        foreach (IAssemblySymbol referencedAssembly in GetReferencedAssemblies(compilation))
        {
            FindSagasInNamespace(
                referencedAssembly.GlobalNamespace,
                sagaAttrSymbol,
                sagaDefinitionSymbol,
                targetRootNamespace,
                sagas);
        }

        return sagas;
    }

    /// <summary>
    ///     Tries to get saga effect info from a type symbol.
    /// </summary>
    private static SagaEffectInfo? TryGetSagaEffectInfo(
        INamedTypeSymbol typeSymbol,
        INamedTypeSymbol sagaAttrSymbol,
        INamedTypeSymbol sagaDefinitionSymbol,
        string targetRootNamespace
    )
    {
        AttributeData? attr = typeSymbol.GetAttributes()
            .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, sagaAttrSymbol));
        if (attr is null)
        {
            return null;
        }

        bool implementsSagaDefinition = typeSymbol.AllInterfaces.Any(i =>
            SymbolEqualityComparer.Default.Equals(i, sagaDefinitionSymbol));
        if (!implementsSagaDefinition)
        {
            return null;
        }

        TypedConstant inputTypeArg = attr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "InputType").Value;
        if (inputTypeArg.IsNull || inputTypeArg.Value is not INamedTypeSymbol)
        {
            return null;
        }

        // Extract saga name
        string sagaName = typeSymbol.Name;
        if (sagaName.EndsWith("SagaState", StringComparison.Ordinal))
        {
            sagaName = sagaName.Substring(0, sagaName.Length - "SagaState".Length);
        }
        else if (sagaName.EndsWith("Saga", StringComparison.Ordinal))
        {
            sagaName = sagaName.Substring(0, sagaName.Length - "Saga".Length);
        }

        string domainNamespace = typeSymbol.ContainingNamespace.ToDisplayString();
        string actionsNamespace = NamingConventions.GetClientSagaFeatureNamespace(
            domainNamespace,
            targetRootNamespace,
            "Actions");
        string dtosNamespace = NamingConventions.GetClientSagaFeatureNamespace(
            domainNamespace,
            targetRootNamespace,
            "Dtos");
        string stateNamespace = NamingConventions.GetClientSagaFeatureNamespace(
            domainNamespace,
            targetRootNamespace,
            "State");
        string effectsNamespace = NamingConventions.GetClientSagaFeatureNamespace(
            domainNamespace,
            targetRootNamespace,
            "ActionEffects");

        // Convert saga name to kebab-case for route
        string sagaRouteKebab = NamingConventions.ToKebabCase(sagaName);
        return new(sagaName, sagaRouteKebab, actionsNamespace, dtosNamespace, stateNamespace, effectsNamespace);
    }

    /// <inheritdoc />
    public void Initialize(
        IncrementalGeneratorInitializationContext context
    )
    {
        IncrementalValueProvider<(Compilation Compilation, AnalyzerConfigOptionsProvider Options)>
            compilationAndOptions = context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider);
        IncrementalValueProvider<List<SagaEffectInfo>> sagasProvider = compilationAndOptions.Select((
            source,
            _
        ) =>
        {
            source.Options.GlobalOptions.TryGetValue(
                TargetNamespaceResolver.RootNamespaceProperty,
                out string? rootNamespace);
            source.Options.GlobalOptions.TryGetValue(
                TargetNamespaceResolver.AssemblyNameProperty,
                out string? assemblyName);
            string targetRootNamespace = TargetNamespaceResolver.GetTargetRootNamespace(
                rootNamespace,
                assemblyName,
                source.Compilation);
            return GetSagasFromCompilation(source.Compilation, targetRootNamespace);
        });
        context.RegisterSourceOutput(
            sagasProvider,
            static (
                spc,
                sagas
            ) =>
            {
                foreach (SagaEffectInfo saga in sagas)
                {
                    GenerateActionEffect(spc, saga);
                }
            });
    }

    /// <summary>
    ///     Information about a saga for action effect generation.
    /// </summary>
    private sealed class SagaEffectInfo
    {
        public SagaEffectInfo(
            string sagaName,
            string sagaRouteKebab,
            string actionsNamespace,
            string dtosNamespace,
            string stateNamespace,
            string effectsNamespace
        )
        {
            SagaName = sagaName;
            SagaRouteKebab = sagaRouteKebab;
            ActionsNamespace = actionsNamespace;
            DtosNamespace = dtosNamespace;
            StateNamespace = stateNamespace;
            EffectsNamespace = effectsNamespace;
        }

        public string ActionsNamespace { get; }

        public string DtosNamespace { get; }

        public string EffectsNamespace { get; }

        public string SagaName { get; }

        public string SagaRouteKebab { get; }

        public string StateNamespace { get; }
    }
}