using System;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using Mississippi.Inlet.Generators.Core.Emit;
using Mississippi.Inlet.Generators.Core.Naming;


namespace Mississippi.Inlet.Client.Generators;

/// <summary>
///     Generates Spring domain registration wrappers for client projects.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SpringDomainClientRegistrationGenerator : IIncrementalGenerator
{
    private const string SpringClientRootNamespace = "Spring.Client";

    /// <inheritdoc />
    public void Initialize(
        IncrementalGeneratorInitializationContext context
    )
    {
        IncrementalValueProvider<(Compilation Compilation, AnalyzerConfigOptionsProvider Options)> source =
            context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider);
        context.RegisterSourceOutput(
            source,
            static (
                spc,
                value
            ) =>
            {
                string targetRootNamespace = ResolveTargetRootNamespace(value.Compilation, value.Options);
                if (!string.Equals(targetRootNamespace, SpringClientRootNamespace, StringComparison.Ordinal))
                {
                    return;
                }

                SourceBuilder sb = new();
                sb.AppendAutoGeneratedHeader();
                sb.AppendUsing("System");
                sb.AppendUsing("Mississippi.Reservoir.Abstractions.Builders");
                sb.AppendUsing("Spring.Client.Features");
                sb.AppendUsing("Spring.Client.Features.BankAccountAggregate");
                sb.AppendUsing("Spring.Client.Features.MoneyTransferSaga");
                sb.AppendFileScopedNamespace("Spring.Client.Registrations");
                sb.AppendLine();
                sb.AppendSummary("Extension methods for registering the Spring domain client features.");
                sb.AppendGeneratedCodeAttribute("SpringDomainClientRegistrationGenerator");
                sb.AppendLine("public static class SpringDomainClientRegistrations");
                sb.OpenBrace();
                sb.AppendSummary("Adds Spring domain features generated from the domain project.");
                sb.AppendLine("/// <param name=\"builder\">The Reservoir builder.</param>");
                sb.AppendLine("/// <returns>The Reservoir builder for chaining.</returns>");
                sb.AppendLine("public static IReservoirBuilder AddSpringDomain(");
                sb.IncreaseIndent();
                sb.AppendLine("this IReservoirBuilder builder");
                sb.DecreaseIndent();
                sb.AppendLine(")");
                sb.OpenBrace();
                sb.AppendLine("ArgumentNullException.ThrowIfNull(builder);");
                sb.AppendLine("builder.AddBankAccountAggregateFeature();");
                sb.AppendLine("builder.AddMoneyTransferSagaFeature();");
                sb.AppendLine("builder.AddProjectionsFeature();");
                sb.AppendLine("return builder;");
                sb.CloseBrace();
                sb.CloseBrace();
                spc.AddSource(
                    "SpringDomainClientRegistrations.g.cs",
                    SourceText.From(sb.ToString(), Encoding.UTF8));
            });
    }

    private static string ResolveTargetRootNamespace(
        Compilation compilation,
        AnalyzerConfigOptionsProvider optionsProvider
    )
    {
        optionsProvider.GlobalOptions.TryGetValue(
            TargetNamespaceResolver.RootNamespaceProperty,
            out string? rootNamespace);
        optionsProvider.GlobalOptions.TryGetValue(
            TargetNamespaceResolver.AssemblyNameProperty,
            out string? assemblyName);
        return TargetNamespaceResolver.GetTargetRootNamespace(rootNamespace, assemblyName, compilation);
    }
}
