namespace Mississippi.EventSourcing.Brooks.Abstractions;

/// <summary>
///     Marker interface for types that define a brook (event stream) identity.
///     Provides compile-time type safety for referencing brooks across aggregates and projections.
/// </summary>
/// <remarks>
///     <para>
///         Implement this interface to define a brook identity that can be shared between
///         aggregates (write-side) and projections (read-side). The <see cref="BrookName" />
///         property should match the value generated by <see cref="Attributes.BrookNameAttribute" />.
///     </para>
///     <example>
///         <code>
///         [BrookName("SHOP", "ORDERS", "ORDERSTREAM")]
///         public sealed class OrderBrook : IBrookDefinition
///         {
///             public static string BrookName =&gt; "SHOP.ORDERS.ORDERSTREAM";
///         }
///         </code>
///     </example>
/// </remarks>
public interface IBrookDefinition
{
    /// <summary>
    ///     Gets the fully qualified brook name in the format {AppName}.{ModuleName}.{Name}.
    /// </summary>
    /// <remarks>
    ///     This value should match the <see cref="Attributes.BrookNameAttribute.BrookName" /> property
    ///     when the attribute is also applied to the implementing type.
    /// </remarks>
    static abstract string BrookName { get; }
}