<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <MutationSourceProject>../Spring.Client/Spring.Client.csproj</MutationSourceProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AngleSharp" />
        <PackageReference Include="bunit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Spring.Client\Spring.Client.csproj" />
        <ProjectReference Include="..\..\..\src\Reservoir.TestHarness\Reservoir.TestHarness.csproj" />
    </ItemGroup>

</Project>
