using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;


namespace Mississippi.Inlet.Client.Generators.L0Tests;

/// <summary>
///     Tests for <see cref="SagaClientMappersGenerator" />.
/// </summary>
public class SagaClientMappersGeneratorTests
{
    /// <summary>
    ///     Minimal stubs needed for compilation without referencing the full SDK.
    /// </summary>
    private const string AttributeStubs = """
                                          namespace Mississippi.Inlet.Generators.Abstractions
                                          {
                                              using System;

                                              [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, Inherited = false)]
                                              public sealed class GenerateSagaEndpointsAttribute : Attribute
                                              {
                                                  public Type? InputType { get; set; }
                                              }
                                          }

                                          namespace Mississippi.EventSourcing.Sagas.Abstractions
                                          {
                                              public interface ISagaDefinition { }
                                          }
                                          """;

    /// <summary>
    ///     Creates a Roslyn compilation from the provided source code and runs the generator.
    /// </summary>
    private static (Compilation OutputCompilation, ImmutableArray<Diagnostic> Diagnostics, GeneratorDriverRunResult
        RunResult) RunGenerator(
            params string[] sources
        )
    {
        SyntaxTree[] syntaxTrees = sources.Select(s => CSharpSyntaxTree.ParseText(s)).ToArray();
        string runtimeDirectory = Path.GetDirectoryName(typeof(object).Assembly.Location)!;
        List<MetadataReference> references =
        [
            MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
            MetadataReference.CreateFromFile(Path.Combine(runtimeDirectory, "System.Runtime.dll")),
            MetadataReference.CreateFromFile(Path.Combine(runtimeDirectory, "System.Collections.dll")),
            MetadataReference.CreateFromFile(Path.Combine(runtimeDirectory, "System.Collections.Immutable.dll")),
        ];
        string netstandardPath = Path.Combine(runtimeDirectory, "netstandard.dll");
        if (File.Exists(netstandardPath))
        {
            references.Add(MetadataReference.CreateFromFile(netstandardPath));
        }

        CSharpCompilation compilation = CSharpCompilation.Create(
            "TestAssembly",
            syntaxTrees,
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary).WithNullableContextOptions(
                NullableContextOptions.Enable));
        SagaClientMappersGenerator generator = new();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);
        driver = driver.RunGeneratorsAndUpdateCompilation(
            compilation,
            out Compilation outputCompilation,
            out ImmutableArray<Diagnostic> diagnostics);
        return (outputCompilation, diagnostics, driver.GetRunResult());
    }

    /// <summary>
    ///     Generated mappers should have auto-generated header.
    /// </summary>
    [Fact]
    public void GeneratedMappersHaveAutoGeneratedHeader()
    {
        const string sagaSource = """
                                  using System;
                                  using Mississippi.Inlet.Generators.Abstractions;
                                  using Mississippi.EventSourcing.Sagas.Abstractions;

                                  namespace TestApp.Domain.Sagas.TransferFunds
                                  {
                                      public sealed record StartTransferFundsSagaInput
                                      {
                                          public string SourceAccountId { get; init; }
                                      }

                                      [GenerateSagaEndpoints(InputType = typeof(StartTransferFundsSagaInput))]
                                      public sealed class TransferFundsSaga : ISagaDefinition
                                      {
                                      }
                                  }
                                  """;
        (Compilation _, ImmutableArray<Diagnostic> _, GeneratorDriverRunResult runResult) =
            RunGenerator(AttributeStubs, sagaSource);
        Assert.NotEmpty(runResult.GeneratedTrees);
        string generatedCode = runResult.GeneratedTrees[0].GetText().ToString();
        Assert.Contains("// <auto-generated", generatedCode, StringComparison.Ordinal);
    }

    /// <summary>
    ///     Should generate action to DTO mapper.
    /// </summary>
    [Fact]
    public void GeneratesActionToDtoMapper()
    {
        const string sagaSource = """
                                  using System;
                                  using Mississippi.Inlet.Generators.Abstractions;
                                  using Mississippi.EventSourcing.Sagas.Abstractions;

                                  namespace TestApp.Domain.Sagas.TransferFunds
                                  {
                                      public sealed record StartTransferFundsSagaInput
                                      {
                                          public string SourceAccountId { get; init; }
                                      }

                                      [GenerateSagaEndpoints(InputType = typeof(StartTransferFundsSagaInput))]
                                      public sealed class TransferFundsSaga : ISagaDefinition
                                      {
                                      }
                                  }
                                  """;
        (Compilation _, ImmutableArray<Diagnostic> _, GeneratorDriverRunResult runResult) =
            RunGenerator(AttributeStubs, sagaSource);
        bool hasMapper = runResult.GeneratedTrees.Any(t => t.FilePath.Contains(
            "StartTransferFundsSagaActionMapper.g.cs",
            StringComparison.Ordinal));
        Assert.True(hasMapper, "Should generate StartTransferFundsSagaActionMapper.g.cs");
    }

    /// <summary>
    ///     Mapper should implement IMapper interface.
    /// </summary>
    [Fact]
    public void MapperImplementsIMapperInterface()
    {
        const string sagaSource = """
                                  using System;
                                  using Mississippi.Inlet.Generators.Abstractions;
                                  using Mississippi.EventSourcing.Sagas.Abstractions;

                                  namespace TestApp.Domain.Sagas.TransferFunds
                                  {
                                      public sealed record StartTransferFundsSagaInput
                                      {
                                          public string SourceAccountId { get; init; }
                                      }

                                      [GenerateSagaEndpoints(InputType = typeof(StartTransferFundsSagaInput))]
                                      public sealed class TransferFundsSaga : ISagaDefinition
                                      {
                                      }
                                  }
                                  """;
        (Compilation _, ImmutableArray<Diagnostic> _, GeneratorDriverRunResult runResult) =
            RunGenerator(AttributeStubs, sagaSource);
        SyntaxTree? mapperTree = runResult.GeneratedTrees.FirstOrDefault(t =>
            t.FilePath.Contains("StartTransferFundsSagaActionMapper.g.cs", StringComparison.Ordinal));
        Assert.NotNull(mapperTree);
        string code = mapperTree.GetText().ToString();
        Assert.Contains("IMapper<", code, StringComparison.Ordinal);
    }

    /// <summary>
    ///     Mapper should map CorrelationId.
    /// </summary>
    [Fact]
    public void MapperMapsCorrelationId()
    {
        const string sagaSource = """
                                  using System;
                                  using Mississippi.Inlet.Generators.Abstractions;
                                  using Mississippi.EventSourcing.Sagas.Abstractions;

                                  namespace TestApp.Domain.Sagas.TransferFunds
                                  {
                                      public sealed record StartTransferFundsSagaInput
                                      {
                                          public string SourceAccountId { get; init; }
                                      }

                                      [GenerateSagaEndpoints(InputType = typeof(StartTransferFundsSagaInput))]
                                      public sealed class TransferFundsSaga : ISagaDefinition
                                      {
                                      }
                                  }
                                  """;
        (Compilation _, ImmutableArray<Diagnostic> _, GeneratorDriverRunResult runResult) =
            RunGenerator(AttributeStubs, sagaSource);
        SyntaxTree? mapperTree = runResult.GeneratedTrees.FirstOrDefault(t =>
            t.FilePath.Contains("StartTransferFundsSagaActionMapper.g.cs", StringComparison.Ordinal));
        Assert.NotNull(mapperTree);
        string code = mapperTree.GetText().ToString();
        Assert.Contains("CorrelationId = input.CorrelationId", code, StringComparison.Ordinal);
    }

    /// <summary>
    ///     Mapper should map input properties.
    /// </summary>
    [Fact]
    public void MapperMapsInputProperties()
    {
        const string sagaSource = """
                                  using System;
                                  using Mississippi.Inlet.Generators.Abstractions;
                                  using Mississippi.EventSourcing.Sagas.Abstractions;

                                  namespace TestApp.Domain.Sagas.TransferFunds
                                  {
                                      public sealed record StartTransferFundsSagaInput
                                      {
                                          public string SourceAccountId { get; init; }
                                          public string TargetAccountId { get; init; }
                                          public decimal Amount { get; init; }
                                      }

                                      [GenerateSagaEndpoints(InputType = typeof(StartTransferFundsSagaInput))]
                                      public sealed class TransferFundsSaga : ISagaDefinition
                                      {
                                      }
                                  }
                                  """;
        (Compilation _, ImmutableArray<Diagnostic> _, GeneratorDriverRunResult runResult) =
            RunGenerator(AttributeStubs, sagaSource);
        SyntaxTree? mapperTree = runResult.GeneratedTrees.FirstOrDefault(t =>
            t.FilePath.Contains("StartTransferFundsSagaActionMapper.g.cs", StringComparison.Ordinal));
        Assert.NotNull(mapperTree);
        string code = mapperTree.GetText().ToString();
        Assert.Contains("SourceAccountId = input.SourceAccountId", code, StringComparison.Ordinal);
        Assert.Contains("TargetAccountId = input.TargetAccountId", code, StringComparison.Ordinal);
        Assert.Contains("Amount = input.Amount", code, StringComparison.Ordinal);
    }

    /// <summary>
    ///     Mapper should validate input is not null.
    /// </summary>
    [Fact]
    public void MapperValidatesInputNotNull()
    {
        const string sagaSource = """
                                  using System;
                                  using Mississippi.Inlet.Generators.Abstractions;
                                  using Mississippi.EventSourcing.Sagas.Abstractions;

                                  namespace TestApp.Domain.Sagas.TransferFunds
                                  {
                                      public sealed record StartTransferFundsSagaInput
                                      {
                                          public string SourceAccountId { get; init; }
                                      }

                                      [GenerateSagaEndpoints(InputType = typeof(StartTransferFundsSagaInput))]
                                      public sealed class TransferFundsSaga : ISagaDefinition
                                      {
                                      }
                                  }
                                  """;
        (Compilation _, ImmutableArray<Diagnostic> _, GeneratorDriverRunResult runResult) =
            RunGenerator(AttributeStubs, sagaSource);
        SyntaxTree? mapperTree = runResult.GeneratedTrees.FirstOrDefault(t =>
            t.FilePath.Contains("StartTransferFundsSagaActionMapper.g.cs", StringComparison.Ordinal));
        Assert.NotNull(mapperTree);
        string code = mapperTree.GetText().ToString();
        Assert.Contains("ArgumentNullException.ThrowIfNull(input)", code, StringComparison.Ordinal);
    }

    /// <summary>
    ///     Mappers should be in correct feature namespace with Mappers sub-namespace.
    /// </summary>
    [Fact]
    public void MappersAreInCorrectNamespace()
    {
        const string sagaSource = """
                                  using System;
                                  using Mississippi.Inlet.Generators.Abstractions;
                                  using Mississippi.EventSourcing.Sagas.Abstractions;

                                  namespace TestApp.Domain.Sagas.TransferFunds
                                  {
                                      public sealed record StartTransferFundsSagaInput
                                      {
                                          public string SourceAccountId { get; init; }
                                      }

                                      [GenerateSagaEndpoints(InputType = typeof(StartTransferFundsSagaInput))]
                                      public sealed class TransferFundsSaga : ISagaDefinition
                                      {
                                      }
                                  }
                                  """;
        (Compilation _, ImmutableArray<Diagnostic> _, GeneratorDriverRunResult runResult) =
            RunGenerator(AttributeStubs, sagaSource);
        SyntaxTree? mapperTree = runResult.GeneratedTrees.FirstOrDefault(t =>
            t.FilePath.Contains("StartTransferFundsSagaActionMapper.g.cs", StringComparison.Ordinal));
        Assert.NotNull(mapperTree);
        string code = mapperTree.GetText().ToString();

        // Should be in Features.TransferFundsSaga.Mappers namespace
        Assert.Contains("Features.TransferFundsSaga.Mappers", code, StringComparison.Ordinal);
    }
}