using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;


namespace Mississippi.Inlet.Client.Generators.L0Tests;

/// <summary>
///     Tests for <see cref="SagaClientRegistrationGenerator" />.
/// </summary>
public class SagaClientRegistrationGeneratorTests
{
    /// <summary>
    ///     Minimal stubs needed for compilation without referencing the full SDK.
    /// </summary>
    private const string AttributeStubs = """
                                          namespace Mississippi.Inlet.Generators.Abstractions
                                          {
                                              using System;

                                              [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, Inherited = false)]
                                              public sealed class GenerateSagaEndpointsAttribute : Attribute
                                              {
                                                  public Type? InputType { get; set; }
                                              }
                                          }

                                          namespace Mississippi.EventSourcing.Sagas.Abstractions
                                          {
                                              public interface ISagaDefinition { }
                                          }
                                          """;

    /// <summary>
    ///     Creates a Roslyn compilation from the provided source code and runs the generator.
    /// </summary>
    private static (Compilation OutputCompilation, ImmutableArray<Diagnostic> Diagnostics, GeneratorDriverRunResult
        RunResult) RunGenerator(
            params string[] sources
        )
    {
        SyntaxTree[] syntaxTrees = sources.Select(s => CSharpSyntaxTree.ParseText(s)).ToArray();
        string runtimeDirectory = Path.GetDirectoryName(typeof(object).Assembly.Location)!;
        List<MetadataReference> references =
        [
            MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
            MetadataReference.CreateFromFile(Path.Combine(runtimeDirectory, "System.Runtime.dll")),
            MetadataReference.CreateFromFile(Path.Combine(runtimeDirectory, "System.Collections.dll")),
            MetadataReference.CreateFromFile(Path.Combine(runtimeDirectory, "System.Collections.Immutable.dll")),
        ];
        string netstandardPath = Path.Combine(runtimeDirectory, "netstandard.dll");
        if (File.Exists(netstandardPath))
        {
            references.Add(MetadataReference.CreateFromFile(netstandardPath));
        }

        CSharpCompilation compilation = CSharpCompilation.Create(
            "TestAssembly",
            syntaxTrees,
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary).WithNullableContextOptions(
                NullableContextOptions.Enable));
        SagaClientRegistrationGenerator generator = new();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);
        driver = driver.RunGeneratorsAndUpdateCompilation(
            compilation,
            out Compilation outputCompilation,
            out ImmutableArray<Diagnostic> diagnostics);
        return (outputCompilation, diagnostics, driver.GetRunResult());
    }

    /// <summary>
    ///     Generated registrations should have auto-generated header.
    /// </summary>
    [Fact]
    public void GeneratedRegistrationsHaveAutoGeneratedHeader()
    {
        const string sagaSource = """
                                  using System;
                                  using Mississippi.Inlet.Generators.Abstractions;
                                  using Mississippi.EventSourcing.Sagas.Abstractions;

                                  namespace TestApp.Domain.Sagas.TransferFunds
                                  {
                                      public sealed record StartTransferFundsSagaInput
                                      {
                                          public string SourceAccountId { get; init; }
                                      }

                                      [GenerateSagaEndpoints(InputType = typeof(StartTransferFundsSagaInput))]
                                      public sealed class TransferFundsSaga : ISagaDefinition
                                      {
                                      }
                                  }
                                  """;
        (Compilation _, ImmutableArray<Diagnostic> _, GeneratorDriverRunResult runResult) =
            RunGenerator(AttributeStubs, sagaSource);
        Assert.NotEmpty(runResult.GeneratedTrees);
        string generatedCode = runResult.GeneratedTrees[0].GetText().ToString();
        Assert.Contains("// <auto-generated", generatedCode, StringComparison.Ordinal);
    }

    /// <summary>
    ///     Should generate registration class.
    /// </summary>
    [Fact]
    public void GeneratesRegistrationClass()
    {
        const string sagaSource = """
                                  using System;
                                  using Mississippi.Inlet.Generators.Abstractions;
                                  using Mississippi.EventSourcing.Sagas.Abstractions;

                                  namespace TestApp.Domain.Sagas.TransferFunds
                                  {
                                      public sealed record StartTransferFundsSagaInput
                                      {
                                          public string SourceAccountId { get; init; }
                                      }

                                      [GenerateSagaEndpoints(InputType = typeof(StartTransferFundsSagaInput))]
                                      public sealed class TransferFundsSaga : ISagaDefinition
                                      {
                                      }
                                  }
                                  """;
        (Compilation _, ImmutableArray<Diagnostic> _, GeneratorDriverRunResult runResult) =
            RunGenerator(AttributeStubs, sagaSource);
        bool hasRegistration = runResult.GeneratedTrees.Any(t => t.FilePath.Contains(
            "TransferFundsSagaFeatureRegistrations.g.cs",
            StringComparison.Ordinal));
        Assert.True(hasRegistration, "Should generate TransferFundsSagaFeatureRegistrations.g.cs");
    }

    /// <summary>
    ///     Registration should have extension method.
    /// </summary>
    [Fact]
    public void RegistrationHasExtensionMethod()
    {
        const string sagaSource = """
                                  using System;
                                  using Mississippi.Inlet.Generators.Abstractions;
                                  using Mississippi.EventSourcing.Sagas.Abstractions;

                                  namespace TestApp.Domain.Sagas.TransferFunds
                                  {
                                      public sealed record StartTransferFundsSagaInput
                                      {
                                          public string SourceAccountId { get; init; }
                                      }

                                      [GenerateSagaEndpoints(InputType = typeof(StartTransferFundsSagaInput))]
                                      public sealed class TransferFundsSaga : ISagaDefinition
                                      {
                                      }
                                  }
                                  """;
        (Compilation _, ImmutableArray<Diagnostic> _, GeneratorDriverRunResult runResult) =
            RunGenerator(AttributeStubs, sagaSource);
        SyntaxTree? registrationTree = runResult.GeneratedTrees.FirstOrDefault(t =>
            t.FilePath.Contains("TransferFundsSagaFeatureRegistrations.g.cs", StringComparison.Ordinal));
        Assert.NotNull(registrationTree);
        string code = registrationTree.GetText().ToString();
        Assert.Contains("AddTransferFundsSagaFeature", code, StringComparison.Ordinal);
        Assert.Contains("this IServiceCollection services", code, StringComparison.Ordinal);
    }

    /// <summary>
    ///     Registration should be in correct feature namespace with Registration sub-namespace.
    /// </summary>
    [Fact]
    public void RegistrationIsInCorrectNamespace()
    {
        const string sagaSource = """
                                  using System;
                                  using Mississippi.Inlet.Generators.Abstractions;
                                  using Mississippi.EventSourcing.Sagas.Abstractions;

                                  namespace TestApp.Domain.Sagas.TransferFunds
                                  {
                                      public sealed record StartTransferFundsSagaInput
                                      {
                                          public string SourceAccountId { get; init; }
                                      }

                                      [GenerateSagaEndpoints(InputType = typeof(StartTransferFundsSagaInput))]
                                      public sealed class TransferFundsSaga : ISagaDefinition
                                      {
                                      }
                                  }
                                  """;
        (Compilation _, ImmutableArray<Diagnostic> _, GeneratorDriverRunResult runResult) =
            RunGenerator(AttributeStubs, sagaSource);
        SyntaxTree? registrationTree = runResult.GeneratedTrees.FirstOrDefault(t =>
            t.FilePath.Contains("TransferFundsSagaFeatureRegistrations.g.cs", StringComparison.Ordinal));
        Assert.NotNull(registrationTree);
        string code = registrationTree.GetText().ToString();

        // Should be in Features.TransferFundsSaga.Registration namespace
        Assert.Contains("Features.TransferFundsSaga.Registration", code, StringComparison.Ordinal);
    }

    /// <summary>
    ///     Registration should register action effect.
    /// </summary>
    [Fact]
    public void RegistrationRegistersActionEffect()
    {
        const string sagaSource = """
                                  using System;
                                  using Mississippi.Inlet.Generators.Abstractions;
                                  using Mississippi.EventSourcing.Sagas.Abstractions;

                                  namespace TestApp.Domain.Sagas.TransferFunds
                                  {
                                      public sealed record StartTransferFundsSagaInput
                                      {
                                          public string SourceAccountId { get; init; }
                                      }

                                      [GenerateSagaEndpoints(InputType = typeof(StartTransferFundsSagaInput))]
                                      public sealed class TransferFundsSaga : ISagaDefinition
                                      {
                                      }
                                  }
                                  """;
        (Compilation _, ImmutableArray<Diagnostic> _, GeneratorDriverRunResult runResult) =
            RunGenerator(AttributeStubs, sagaSource);
        SyntaxTree? registrationTree = runResult.GeneratedTrees.FirstOrDefault(t =>
            t.FilePath.Contains("TransferFundsSagaFeatureRegistrations.g.cs", StringComparison.Ordinal));
        Assert.NotNull(registrationTree);
        string code = registrationTree.GetText().ToString();
        Assert.Contains("AddActionEffect<", code, StringComparison.Ordinal);
        Assert.Contains("SagaActionEffect", code, StringComparison.Ordinal);
    }

    /// <summary>
    ///     Registration should register feature state.
    /// </summary>
    [Fact]
    public void RegistrationRegistersFeatureState()
    {
        const string sagaSource = """
                                  using System;
                                  using Mississippi.Inlet.Generators.Abstractions;
                                  using Mississippi.EventSourcing.Sagas.Abstractions;

                                  namespace TestApp.Domain.Sagas.TransferFunds
                                  {
                                      public sealed record StartTransferFundsSagaInput
                                      {
                                          public string SourceAccountId { get; init; }
                                      }

                                      [GenerateSagaEndpoints(InputType = typeof(StartTransferFundsSagaInput))]
                                      public sealed class TransferFundsSaga : ISagaDefinition
                                      {
                                      }
                                  }
                                  """;
        (Compilation _, ImmutableArray<Diagnostic> _, GeneratorDriverRunResult runResult) =
            RunGenerator(AttributeStubs, sagaSource);
        SyntaxTree? registrationTree = runResult.GeneratedTrees.FirstOrDefault(t =>
            t.FilePath.Contains("TransferFundsSagaFeatureRegistrations.g.cs", StringComparison.Ordinal));
        Assert.NotNull(registrationTree);
        string code = registrationTree.GetText().ToString();

        // The generator uses TransferFundsSagaFeatureState in reducer registrations
        Assert.Contains("TransferFundsSagaFeatureState", code, StringComparison.Ordinal);
    }

    /// <summary>
    ///     Registration should register mapper.
    /// </summary>
    [Fact]
    public void RegistrationRegistersMapper()
    {
        const string sagaSource = """
                                  using System;
                                  using Mississippi.Inlet.Generators.Abstractions;
                                  using Mississippi.EventSourcing.Sagas.Abstractions;

                                  namespace TestApp.Domain.Sagas.TransferFunds
                                  {
                                      public sealed record StartTransferFundsSagaInput
                                      {
                                          public string SourceAccountId { get; init; }
                                      }

                                      [GenerateSagaEndpoints(InputType = typeof(StartTransferFundsSagaInput))]
                                      public sealed class TransferFundsSaga : ISagaDefinition
                                      {
                                      }
                                  }
                                  """;
        (Compilation _, ImmutableArray<Diagnostic> _, GeneratorDriverRunResult runResult) =
            RunGenerator(AttributeStubs, sagaSource);
        SyntaxTree? registrationTree = runResult.GeneratedTrees.FirstOrDefault(t =>
            t.FilePath.Contains("TransferFundsSagaFeatureRegistrations.g.cs", StringComparison.Ordinal));
        Assert.NotNull(registrationTree);
        string code = registrationTree.GetText().ToString();
        Assert.Contains("IMapper<", code, StringComparison.Ordinal);
        Assert.Contains("ActionMapper", code, StringComparison.Ordinal);
    }

    /// <summary>
    ///     Registration should register reducers.
    /// </summary>
    [Fact]
    public void RegistrationRegistersReducers()
    {
        const string sagaSource = """
                                  using System;
                                  using Mississippi.Inlet.Generators.Abstractions;
                                  using Mississippi.EventSourcing.Sagas.Abstractions;

                                  namespace TestApp.Domain.Sagas.TransferFunds
                                  {
                                      public sealed record StartTransferFundsSagaInput
                                      {
                                          public string SourceAccountId { get; init; }
                                      }

                                      [GenerateSagaEndpoints(InputType = typeof(StartTransferFundsSagaInput))]
                                      public sealed class TransferFundsSaga : ISagaDefinition
                                      {
                                      }
                                  }
                                  """;
        (Compilation _, ImmutableArray<Diagnostic> _, GeneratorDriverRunResult runResult) =
            RunGenerator(AttributeStubs, sagaSource);
        SyntaxTree? registrationTree = runResult.GeneratedTrees.FirstOrDefault(t =>
            t.FilePath.Contains("TransferFundsSagaFeatureRegistrations.g.cs", StringComparison.Ordinal));
        Assert.NotNull(registrationTree);
        string code = registrationTree.GetText().ToString();
        Assert.Contains("AddReducer<", code, StringComparison.Ordinal);
        Assert.Contains("ExecutingReducer", code, StringComparison.Ordinal);
        Assert.Contains("SucceededReducer", code, StringComparison.Ordinal);
        Assert.Contains("FailedReducer", code, StringComparison.Ordinal);
    }
}