<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\DomainModeling.Abstractions\DomainModeling.Abstractions.csproj" />
    <ProjectReference Include="..\Spring.TestHarness\Spring.TestHarness.csproj" />
  </ItemGroup>
</Project>
