using System;

using Allure.Xunit.Attributes;

using Mississippi.Sdk.Generators.Core.Emit;


namespace Mississippi.Sdk.Generators.Core.L0Tests.Emit;

/// <summary>
///     Tests for <see cref="SourceBuilder" /> fluent code generation API.
/// </summary>
[AllureParentSuite("SDK")]
[AllureSuite("Generators Core")]
[AllureSubSuite("Source Builder")]
public class SourceBuilderTests
{
    /// <summary>
    ///     Append should add indentation at start of line.
    /// </summary>
    [Fact]
    public void AppendAddsIndentationAtStartOfLine()
    {
        SourceBuilder builder = new();
        builder.IncreaseIndent();
        builder.Append("Indented");
        string result = builder.ToString();
        Assert.Equal("    Indented", result);
    }

    /// <summary>
    ///     Append should add text without newline.
    /// </summary>
    [Fact]
    public void AppendAddsTextWithoutNewline()
    {
        SourceBuilder builder = new();
        builder.Append("Hello").Append(" World");
        string result = builder.ToString();
        Assert.Equal("Hello World", result);
    }

    /// <summary>
    ///     AppendAutoGeneratedHeader should add standard header.
    /// </summary>
    [Fact]
    public void AppendAutoGeneratedHeaderAddsStandardHeader()
    {
        SourceBuilder builder = new();
        builder.AppendAutoGeneratedHeader();
        string result = builder.ToString();
        Assert.Contains("// <auto-generated />", result);
        Assert.Contains("#nullable enable", result);
    }

    /// <summary>
    ///     Append should not add indentation mid-line.
    /// </summary>
    [Fact]
    public void AppendDoesNotAddIndentationMidLine()
    {
        SourceBuilder builder = new();
        builder.IncreaseIndent();
        builder.Append("First").Append("Second");
        string result = builder.ToString();
        Assert.Equal("    FirstSecond", result);
    }

    /// <summary>
    ///     AppendFileScopedNamespace should add file-scoped namespace syntax.
    /// </summary>
    [Fact]
    public void AppendFileScopedNamespaceAddsFileScopedSyntax()
    {
        SourceBuilder builder = new();
        builder.AppendFileScopedNamespace("Test.Namespace");
        string result = builder.ToString();
        Assert.Contains("namespace Test.Namespace;", result);
    }

    /// <summary>
    ///     AppendGeneratedCodeAttribute should add attribute with default version.
    /// </summary>
    [Fact]
    public void AppendGeneratedCodeAttributeAddsAttributeWithDefaultVersion()
    {
        SourceBuilder builder = new();
        builder.AppendGeneratedCodeAttribute("TestGenerator");
        string result = builder.ToString();
        Assert.Contains("[global::System.CodeDom.Compiler.GeneratedCode(\"TestGenerator\", \"1.0.0\")]", result);
    }

    /// <summary>
    ///     AppendGeneratedCodeAttribute should use custom version when provided.
    /// </summary>
    [Fact]
    public void AppendGeneratedCodeAttributeUsesCustomVersion()
    {
        SourceBuilder builder = new();
        builder.AppendGeneratedCodeAttribute("TestGenerator", "2.5.0");
        string result = builder.ToString();
        Assert.Contains("[global::System.CodeDom.Compiler.GeneratedCode(\"TestGenerator\", \"2.5.0\")]", result);
    }

    /// <summary>
    ///     AppendLine should respect current indentation.
    /// </summary>
    [Fact]
    public void AppendLineRespectsCurrentIndentation()
    {
        SourceBuilder builder = new();
        builder.IncreaseIndent();
        builder.AppendLine("Indented line");
        string result = builder.ToString();
        Assert.Equal("    Indented line" + Environment.NewLine, result);
    }

    /// <summary>
    ///     AppendLine with argument should add line with content.
    /// </summary>
    [Fact]
    public void AppendLineWithArgumentAddsLineWithContent()
    {
        SourceBuilder builder = new();
        builder.AppendLine("Test line");
        string result = builder.ToString();
        Assert.Equal("Test line" + Environment.NewLine, result);
    }

    /// <summary>
    ///     AppendLine without argument should add blank line.
    /// </summary>
    [Fact]
    public void AppendLineWithoutArgumentAddsBlankLine()
    {
        SourceBuilder builder = new();
        builder.Append("First");
        builder.AppendLine();
        builder.Append("Second");
        string result = builder.ToString();
        Assert.Contains("First" + Environment.NewLine + "Second", result);
    }

    /// <summary>
    ///     AppendSummary should add XML documentation comment.
    /// </summary>
    [Fact]
    public void AppendSummaryAddsXmlDocumentationComment()
    {
        SourceBuilder builder = new();
        builder.AppendSummary("Test summary text");
        string result = builder.ToString();
        Assert.Contains("/// <summary>", result);
        Assert.Contains("///     Test summary text", result);
        Assert.Contains("/// </summary>", result);
    }

    /// <summary>
    ///     AppendUsing should add using directive.
    /// </summary>
    [Fact]
    public void AppendUsingAddsUsingDirective()
    {
        SourceBuilder builder = new();
        builder.AppendUsing("System.Collections.Generic");
        string result = builder.ToString();
        Assert.Contains("using System.Collections.Generic;", result);
    }

    /// <summary>
    ///     CloseBrace should decrease indentation and add closing brace.
    /// </summary>
    [Fact]
    public void CloseBraceDecreasesIndentationAndAddsClosingBrace()
    {
        SourceBuilder builder = new();
        builder.IncreaseIndent();
        builder.IncreaseIndent();
        builder.AppendLine("Code");
        builder.CloseBrace();
        builder.AppendLine("After");
        string result = builder.ToString();
        Assert.Contains("}" + Environment.NewLine + "    After", result);
    }

    /// <summary>
    ///     CloseBrace should not decrease indentation below zero.
    /// </summary>
    [Fact]
    public void CloseBraceDoesNotDecreaseIndentationBelowZero()
    {
        SourceBuilder builder = new();
        builder.CloseBrace();
        builder.CloseBrace();
        builder.AppendLine("No negative indent");
        string result = builder.ToString();
        Assert.StartsWith("}" + Environment.NewLine + "}" + Environment.NewLine + "No negative indent", result);
    }

    /// <summary>
    ///     CloseNamespace should delegate to CloseBrace.
    /// </summary>
    [Fact]
    public void CloseNamespaceDelegatesToCloseBrace()
    {
        SourceBuilder builder = new();
        builder.IncreaseIndent();
        builder.AppendLine("Code");
        builder.CloseNamespace();
        string result = builder.ToString();
        Assert.Contains("}" + Environment.NewLine, result);
    }

    /// <summary>
    ///     DecreaseIndent should not go below zero.
    /// </summary>
    [Fact]
    public void DecreaseIndentDoesNotGoBelowZero()
    {
        SourceBuilder builder = new();
        builder.DecreaseIndent();
        builder.DecreaseIndent();
        builder.AppendLine("No indent");
        string result = builder.ToString();
        Assert.Equal("No indent" + Environment.NewLine, result);
    }

    /// <summary>
    ///     DecreaseIndent should reduce indentation level.
    /// </summary>
    [Fact]
    public void DecreaseIndentReducesIndentationLevel()
    {
        SourceBuilder builder = new();
        builder.IncreaseIndent();
        builder.IncreaseIndent();
        builder.DecreaseIndent();
        builder.AppendLine("One level");
        string result = builder.ToString();
        Assert.Equal("    One level" + Environment.NewLine, result);
    }

    /// <summary>
    ///     Fluent API should allow method chaining.
    /// </summary>
    [Fact]
    public void FluentApiAllowsMethodChaining()
    {
        SourceBuilder builder = new();
        string result = builder.AppendAutoGeneratedHeader()
            .AppendUsing("System")
            .AppendFileScopedNamespace("Test")
            .AppendSummary("A test class")
            .AppendGeneratedCodeAttribute("TestGen")
            .AppendLine("public class TestClass")
            .OpenBrace()
            .AppendLine("public int Value { get; set; }")
            .CloseBrace()
            .ToString();
        Assert.Contains("// <auto-generated />", result);
        Assert.Contains("using System;", result);
        Assert.Contains("namespace Test;", result);
        Assert.Contains("/// <summary>", result);
        Assert.Contains("[global::System.CodeDom.Compiler.GeneratedCode(\"TestGen\", \"1.0.0\")]", result);
        Assert.Contains("public class TestClass", result);
        Assert.Contains("public int Value { get; set; }", result);
    }

    /// <summary>
    ///     IncreaseIndent should add four spaces per level.
    /// </summary>
    [Fact]
    public void IncreaseIndentAddsFourSpacesPerLevel()
    {
        SourceBuilder builder = new();
        builder.IncreaseIndent();
        builder.IncreaseIndent();
        builder.AppendLine("Two levels");
        string result = builder.ToString();
        Assert.Equal("        Two levels" + Environment.NewLine, result);
    }

    /// <summary>
    ///     OpenBrace should add opening brace and increase indentation.
    /// </summary>
    [Fact]
    public void OpenBraceAddsOpeningBraceAndIncreasesIndentation()
    {
        SourceBuilder builder = new();
        builder.OpenBrace();
        builder.AppendLine("Inside");
        string result = builder.ToString();
        Assert.Contains("{" + Environment.NewLine + "    Inside", result);
    }

    /// <summary>
    ///     OpenNamespace should add block-scoped namespace with brace.
    /// </summary>
    [Fact]
    public void OpenNamespaceAddsBlockScopedNamespaceWithBrace()
    {
        SourceBuilder builder = new();
        builder.OpenNamespace("Test.Namespace");
        builder.AppendLine("Inside namespace");
        string result = builder.ToString();
        Assert.Contains("namespace Test.Namespace", result);
        Assert.Contains("{" + Environment.NewLine, result);
        Assert.Contains("    Inside namespace", result);
    }

    /// <summary>
    ///     ToString should return all appended content.
    /// </summary>
    [Fact]
    public void ToStringReturnsAllAppendedContent()
    {
        SourceBuilder builder = new();
        builder.AppendLine("Line 1");
        builder.AppendLine("Line 2");
        builder.Append("Partial");
        string result = builder.ToString();
        Assert.Equal("Line 1" + Environment.NewLine + "Line 2" + Environment.NewLine + "Partial", result);
    }
}