using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

using Mississippi.Inlet.Generators.Core.Emit;
using Mississippi.Inlet.Generators.Core.Naming;


namespace Mississippi.Inlet.Silo.Generators;

/// <summary>
///     Generates silo-side registrations for sagas marked with [GenerateSagaEndpoints].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SagaSiloRegistrationGenerator : IIncrementalGenerator
{
    private const string CompensatableInterfaceFullName =
        "Mississippi.EventSourcing.Sagas.Abstractions.ICompensatable`1";

    private const string ReducerRegistrationsTypeFullName =
        "Mississippi.EventSourcing.Reducers.ReducerRegistrations";

    private const string EventReducerBaseFullName =
        "Mississippi.EventSourcing.Reducers.Abstractions.EventReducerBase`2";

    private const string GenerateSagaEndpointsAttributeFullName =
        "Mississippi.Inlet.Generators.Abstractions.GenerateSagaEndpointsAttribute";

    private const string GenerateSagaEndpointsAttributeGenericFullName =
        "Mississippi.Inlet.Generators.Abstractions.GenerateSagaEndpointsAttribute`1";

    private const string SagaStateInterfaceFullName = "Mississippi.EventSourcing.Sagas.Abstractions.ISagaState";

    private const string SagaStepAttributeFullName = "Mississippi.EventSourcing.Sagas.Abstractions.SagaStepAttribute";

    private const string SagaStepInterfaceFullName = "Mississippi.EventSourcing.Sagas.Abstractions.ISagaStep`1";

    private const string SagaRegistrationsTypeFullName =
        "Mississippi.EventSourcing.Sagas.SagaRegistrations";

    private const string SnapshotRegistrationsTypeFullName =
        "Mississippi.EventSourcing.Snapshots.SnapshotRegistrations";

    private static string GenerateRegistration(
        SagaRegistrationInfo saga
    )
    {
        SourceBuilder sb = new();
        sb.AppendAutoGeneratedHeader();
        sb.AppendUsing("System");
        sb.AppendUsing("Microsoft.Extensions.DependencyInjection");
        sb.AppendUsing("Mississippi.EventSourcing.Sagas");
        sb.AppendUsing("Mississippi.EventSourcing.Sagas.Abstractions");
        sb.AppendUsing("Mississippi.EventSourcing.Snapshots");
        sb.AppendUsing("Mississippi.EventSourcing.Reducers");
        sb.AppendUsing(saga.SagaNamespace);
        sb.AppendFileScopedNamespace(saga.OutputNamespace);
        sb.AppendLine();
        sb.AppendSummary($"Registrations for the {saga.SagaName} saga.");
        sb.AppendGeneratedCodeAttribute("SagaSiloRegistrationGenerator");
        sb.AppendLine($"public static class {saga.SagaName}SagaRegistrations");
        sb.OpenBrace();
        sb.AppendSummary($"Adds the {saga.SagaName} saga registrations.");
        sb.AppendLine("/// <param name=\"services\">The service collection.</param>");
        sb.AppendLine("/// <returns>The updated service collection.</returns>");
        sb.AppendLine($"public static IServiceCollection Add{saga.SagaName}Saga(this IServiceCollection services)");
        sb.OpenBrace();
        sb.AppendLine("ArgumentNullException.ThrowIfNull(services);");
        sb.AppendLine($"services.AddSagaOrchestration<{saga.SagaStateTypeName}, {saga.InputTypeName}>();");
        sb.AppendLine($"services.AddSnapshotStateConverter<{saga.SagaStateTypeName}>();");
        foreach (StepInfo step in saga.Steps)
        {
            sb.AppendLine($"services.AddTransient<{step.StepTypeName}>();");
        }

        if (saga.Steps.Count > 0)
        {
            sb.AppendLine($"services.AddSagaStepInfo<{saga.SagaStateTypeName}>(new SagaStepInfo[]");
            sb.OpenBrace();
            foreach (StepInfo step in saga.Steps)
            {
                sb.AppendLine(
                    $"new({step.StepIndex}, \"{step.StepName}\", typeof({step.StepTypeName}), hasCompensation: {(step.HasCompensation ? "true" : "false")}),");
            }

            sb.CloseBrace();
            sb.AppendLine(");");
        }

        foreach (ReducerInfo reducer in saga.Reducers)
        {
            sb.AppendLine(
                $"services.AddReducer<{reducer.EventTypeName}, {saga.SagaStateTypeName}, {reducer.ReducerTypeName}>();");
        }

        sb.AppendLine("return services;");
        sb.CloseBrace();
        sb.CloseBrace();
        return sb.ToString();
    }

    private static IEnumerable<INamespaceSymbol> GetAllNamespaces(
        INamespaceSymbol namespaceSymbol
    )
    {
        yield return namespaceSymbol;
        foreach (INamespaceSymbol child in namespaceSymbol.GetNamespaceMembers())
        {
            foreach (INamespaceSymbol descendant in GetAllNamespaces(child))
            {
                yield return descendant;
            }
        }
    }

    private static IEnumerable<INamedTypeSymbol> GetAllTypes(
        Compilation compilation
    )
    {
        foreach (IAssemblySymbol assembly in GetReferencedAssemblies(compilation))
        {
            foreach (INamespaceSymbol namespaceSymbol in GetAllNamespaces(assembly.GlobalNamespace))
            {
                foreach (INamedTypeSymbol typeSymbol in namespaceSymbol.GetTypeMembers())
                {
                    yield return typeSymbol;
                }
            }
        }
    }

    private static IEnumerable<IAssemblySymbol> GetReferencedAssemblies(
        Compilation compilation
    )
    {
        yield return compilation.Assembly;
        foreach (MetadataReference reference in compilation.References)
        {
            if (compilation.GetAssemblyOrModuleSymbol(reference) is IAssemblySymbol assemblySymbol)
            {
                yield return assemblySymbol;
            }
        }
    }

    private static List<SagaRegistrationInfo> GetSagasFromCompilation(
        Compilation compilation,
        string targetRootNamespace
    )
    {
        List<SagaRegistrationInfo> sagas = [];
        INamedTypeSymbol? sagaAttrSymbol = compilation.GetTypeByMetadataName(GenerateSagaEndpointsAttributeFullName);
        INamedTypeSymbol? sagaAttrGenericSymbol =
            compilation.GetTypeByMetadataName(GenerateSagaEndpointsAttributeGenericFullName);
        INamedTypeSymbol? sagaStateSymbol = compilation.GetTypeByMetadataName(SagaStateInterfaceFullName);
        INamedTypeSymbol? sagaStepAttrSymbol = compilation.GetTypeByMetadataName(SagaStepAttributeFullName);
        INamedTypeSymbol? sagaStepInterfaceSymbol = compilation.GetTypeByMetadataName(SagaStepInterfaceFullName);
        INamedTypeSymbol? compensatableInterfaceSymbol =
            compilation.GetTypeByMetadataName(CompensatableInterfaceFullName);
        INamedTypeSymbol? reducerBaseSymbol = compilation.GetTypeByMetadataName(EventReducerBaseFullName);
        if ((sagaAttrSymbol is null && sagaAttrGenericSymbol is null) ||
            sagaStateSymbol is null ||
            sagaStepAttrSymbol is null ||
            sagaStepInterfaceSymbol is null ||
            reducerBaseSymbol is null)
        {
            return sagas;
        }

        List<INamedTypeSymbol> allTypes = GetAllTypes(compilation).ToList();
        Dictionary<INamedTypeSymbol, SagaRegistrationInfo> sagaMap = new(SymbolEqualityComparer.Default);
        foreach (INamedTypeSymbol typeSymbol in allTypes)
        {
            SagaRegistrationInfo? info = TryGetSagaInfo(
                typeSymbol,
                sagaAttrSymbol,
                sagaAttrGenericSymbol,
                sagaStateSymbol,
                targetRootNamespace);
            if (info is not null)
            {
                sagaMap[typeSymbol] = info;
            }
        }

        foreach (INamedTypeSymbol typeSymbol in allTypes)
        {
            StepInfo? step = TryGetStepInfo(
                typeSymbol,
                sagaStepAttrSymbol,
                sagaStepInterfaceSymbol,
                compensatableInterfaceSymbol);
            if (step is not null && sagaMap.TryGetValue(step.SagaStateSymbol, out SagaRegistrationInfo? sagaInfo))
            {
                sagaInfo.Steps.Add(step);
            }
        }

        foreach (INamedTypeSymbol typeSymbol in allTypes)
        {
            ReducerInfo? reducer = TryGetReducerInfo(typeSymbol, reducerBaseSymbol);
            if (reducer is not null && sagaMap.TryGetValue(reducer.SagaStateSymbol, out SagaRegistrationInfo? sagaInfo))
            {
                sagaInfo.Reducers.Add(reducer);
            }
        }

        foreach (SagaRegistrationInfo saga in sagaMap.Values)
        {
            saga.Steps.Sort((
                a,
                b
            ) => a.StepIndex.CompareTo(b.StepIndex));
            sagas.Add(saga);
        }

        return sagas;
    }

    private static bool MatchesSagaAttribute(
        AttributeData attr,
        INamedTypeSymbol? sagaAttrSymbol,
        INamedTypeSymbol? sagaAttrGenericSymbol
    )
    {
        if (attr.AttributeClass is null)
        {
            return false;
        }

        if (sagaAttrSymbol is not null && SymbolEqualityComparer.Default.Equals(attr.AttributeClass, sagaAttrSymbol))
        {
            return true;
        }

        return sagaAttrGenericSymbol is not null &&
               SymbolEqualityComparer.Default.Equals(attr.AttributeClass.OriginalDefinition, sagaAttrGenericSymbol);
    }

    private static bool TryGetInputType(
        AttributeData attr,
        out INamedTypeSymbol? inputTypeSymbol
    )
    {
        inputTypeSymbol = null;
        if (attr.AttributeClass is not null && attr.AttributeClass.IsGenericType)
        {
            inputTypeSymbol = attr.AttributeClass.TypeArguments.FirstOrDefault() as INamedTypeSymbol;
        }

        if (inputTypeSymbol is not null)
        {
            return true;
        }

        inputTypeSymbol =
            attr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "InputType").Value.Value as INamedTypeSymbol;
        return inputTypeSymbol is not null;
    }

    private static ReducerInfo? TryGetReducerInfo(
        INamedTypeSymbol typeSymbol,
        INamedTypeSymbol reducerBaseSymbol
    )
    {
        INamedTypeSymbol? current = typeSymbol;
        while (current is not null)
        {
            if (current.IsGenericType &&
                SymbolEqualityComparer.Default.Equals(current.OriginalDefinition, reducerBaseSymbol))
            {
                INamedTypeSymbol? sagaState = current.TypeArguments[1] as INamedTypeSymbol;
                INamedTypeSymbol? eventType = current.TypeArguments[0] as INamedTypeSymbol;
                if (sagaState is null || eventType is null)
                {
                    return null;
                }

                return new(sagaState, typeSymbol, eventType);
            }

            current = current.BaseType;
        }

        return null;
    }

    private static SagaRegistrationInfo? TryGetSagaInfo(
        INamedTypeSymbol typeSymbol,
        INamedTypeSymbol? sagaAttrSymbol,
        INamedTypeSymbol? sagaAttrGenericSymbol,
        INamedTypeSymbol sagaStateSymbol,
        string targetRootNamespace
    )
    {
        if (sagaAttrSymbol is null && sagaAttrGenericSymbol is null)
        {
            return null;
        }

        AttributeData? attr = typeSymbol.GetAttributes()
            .FirstOrDefault(a => MatchesSagaAttribute(a, sagaAttrSymbol, sagaAttrGenericSymbol));
        if (attr is null)
        {
            return null;
        }

        if (!typeSymbol.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, sagaStateSymbol)))
        {
            return null;
        }

        if (!TryGetInputType(attr, out INamedTypeSymbol? inputTypeSymbol) || inputTypeSymbol is null)
        {
            return null;
        }

        INamedTypeSymbol inputType = inputTypeSymbol;
        string outputNamespace = NamingConventions.GetSiloRegistrationNamespace(
            typeSymbol.ContainingNamespace.ToDisplayString(),
            targetRootNamespace);
        return new(typeSymbol, inputType, outputNamespace);
    }

    private static StepInfo? TryGetStepInfo(
        INamedTypeSymbol typeSymbol,
        INamedTypeSymbol sagaStepAttrSymbol,
        INamedTypeSymbol sagaStepInterfaceSymbol,
        INamedTypeSymbol? compensatableInterfaceSymbol
    )
    {
        AttributeData? attr = typeSymbol.GetAttributes()
            .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, sagaStepAttrSymbol));
        if (attr is null)
        {
            return null;
        }

        int stepIndex = attr.ConstructorArguments.Length > 0 ? (int)attr.ConstructorArguments[0].Value! : 0;
        INamedTypeSymbol? sagaStateSymbol = null;
        if (attr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "Saga").Value.Value is INamedTypeSymbol sagaType)
        {
            sagaStateSymbol = sagaType;
        }
        else
        {
            INamedTypeSymbol? sagaInterface = typeSymbol.AllInterfaces.FirstOrDefault(iface =>
                iface.OriginalDefinition is not null &&
                SymbolEqualityComparer.Default.Equals(iface.OriginalDefinition, sagaStepInterfaceSymbol));
            sagaStateSymbol = sagaInterface?.TypeArguments[0] as INamedTypeSymbol;
        }

        if (sagaStateSymbol is null)
        {
            return null;
        }

        bool hasCompensation = false;
        if (compensatableInterfaceSymbol is not null)
        {
            hasCompensation = typeSymbol.AllInterfaces.Any(i =>
                i.OriginalDefinition is not null &&
                SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, compensatableInterfaceSymbol));
        }

        return new(sagaStateSymbol, typeSymbol, stepIndex, hasCompensation);
    }

    /// <inheritdoc />
    public void Initialize(
        IncrementalGeneratorInitializationContext context
    )
    {
        IncrementalValueProvider<(Compilation Compilation, AnalyzerConfigOptionsProvider Options)> source =
            context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider);
        IncrementalValueProvider<List<SagaRegistrationInfo>> sagasProvider = source.Select((
            pair,
            _
        ) =>
        {
            if (!HasRegistrationDependencies(pair.Compilation))
            {
                return [];
            }

            string? rootNamespace = pair.Options.GlobalOptions.TryGetValue(
                TargetNamespaceResolver.RootNamespaceProperty,
                out string? rootNs)
                ? rootNs
                : null;
            string? assemblyName = pair.Options.GlobalOptions.TryGetValue(
                TargetNamespaceResolver.AssemblyNameProperty,
                out string? asmName)
                ? asmName
                : null;
            string targetRootNamespace = TargetNamespaceResolver.GetTargetRootNamespace(
                rootNamespace,
                assemblyName,
                pair.Compilation);
            return GetSagasFromCompilation(pair.Compilation, targetRootNamespace);
        });
        context.RegisterSourceOutput(
            sagasProvider,
            (
                spc,
                sagas
            ) =>
            {
                foreach (SagaRegistrationInfo saga in sagas)
                {
                    string sourceText = GenerateRegistration(saga);
                    spc.AddSource($"{saga.SagaName}SagaRegistrations.g.cs", SourceText.From(sourceText, Encoding.UTF8));
                }
            });
    }

    private static bool HasRegistrationDependencies(
        Compilation compilation
    )
    {
        return compilation.GetTypeByMetadataName(SagaRegistrationsTypeFullName) is not null &&
               compilation.GetTypeByMetadataName(ReducerRegistrationsTypeFullName) is not null &&
               compilation.GetTypeByMetadataName(SnapshotRegistrationsTypeFullName) is not null;
    }

    private sealed class ReducerInfo
    {
        public ReducerInfo(
            INamedTypeSymbol sagaStateSymbol,
            INamedTypeSymbol reducerType,
            INamedTypeSymbol eventType
        )
        {
            SagaStateSymbol = sagaStateSymbol;
            ReducerType = reducerType;
            EventType = eventType;
            ReducerTypeName = reducerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            EventTypeName = eventType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        public INamedTypeSymbol EventType { get; }

        public string EventTypeName { get; }

        public INamedTypeSymbol ReducerType { get; }

        public string ReducerTypeName { get; }

        public INamedTypeSymbol SagaStateSymbol { get; }
    }

    private sealed class SagaRegistrationInfo
    {
        public SagaRegistrationInfo(
            INamedTypeSymbol sagaStateType,
            INamedTypeSymbol inputType,
            string outputNamespace
        )
        {
            SagaStateType = sagaStateType;
            InputType = inputType;
            OutputNamespace = outputNamespace;
            SagaNamespace = sagaStateType.ContainingNamespace.ToDisplayString();
            SagaName = RemoveSagaSuffix(sagaStateType.Name);
            SagaStateTypeName = sagaStateType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            InputTypeName = inputType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            Steps = [];
            Reducers = [];
        }

        public INamedTypeSymbol InputType { get; }

        public string InputTypeName { get; }

        public string OutputNamespace { get; }

        public List<ReducerInfo> Reducers { get; }

        public string SagaName { get; }

        public string SagaNamespace { get; }

        public INamedTypeSymbol SagaStateType { get; }

        public string SagaStateTypeName { get; }

        public List<StepInfo> Steps { get; }

        private static string RemoveSagaSuffix(
            string typeName
        ) =>
            typeName.EndsWith("SagaState", StringComparison.Ordinal)
                ? typeName.Substring(0, typeName.Length - "SagaState".Length)
                : typeName;
    }

    private sealed class StepInfo
    {
        public StepInfo(
            INamedTypeSymbol sagaStateSymbol,
            INamedTypeSymbol stepType,
            int stepIndex,
            bool hasCompensation
        )
        {
            SagaStateSymbol = sagaStateSymbol;
            StepType = stepType;
            StepIndex = stepIndex;
            HasCompensation = hasCompensation;
            StepTypeName = stepType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            StepName = stepType.Name;
        }

        public bool HasCompensation { get; }

        public INamedTypeSymbol SagaStateSymbol { get; }

        public int StepIndex { get; }

        public string StepName { get; }

        public INamedTypeSymbol StepType { get; }

        public string StepTypeName { get; }
    }
}