name: ReSharper Cleanup Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - feature/**

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      SOLUTION_PATH: ${{ github.workspace }}/src/mississippi.sln
      DOTSETTINGS_PATH: ${{ github.workspace }}/src/mississippi.sln.DotSettings
      CONFIGURATION: Release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore .NET Tools and Install ReSharper Global Tools
        run: |
          set -euo pipefail
          echo "Restoring dotnet tools..."
          dotnet tool restore
          echo "Installing JetBrains.ReSharper.GlobalTools..."
          dotnet tool install JetBrains.ReSharper.GlobalTools

      - name: Run ReSharper Cleanup Code
        run: |
          set -euo pipefail
          echo "Running ReSharper Cleanup Code..."
          dotnet tool run jb cleanupcode "${{ env.SOLUTION_PATH }}"
          echo "Cleanup completed."

      - name: Check for Uncommitted Changes
        run: |
          set -euo pipefail
          echo "Checking for modifications after cleanup..."
          # Capture any git changes made by the cleanup run.
          CHANGES=$(git status --porcelain)
          if [ -n "$CHANGES" ]; then
            echo "ERROR: ReSharper cleanup modified files. The following changes are required:"
            # Output the diff to show exactly what must be changed.
            git diff --color=always
            echo ""
            echo "To resolve this, run the following command locally to apply the required cleanup changes:"
            echo "dotnet tool run jb cleanupcode --profile \"Built-in: Full Cleanup\" --settings \"${DOTSETTINGS_PATH}\" \"${SOLUTION_PATH}\""
            exit 1
          else
            echo "No modifications detected. Cleanup check passed."
          fi
