name: "Build (perfect)"
on:
  push:
    branches:
      - main
  merge_group:
  pull_request:
    branches:
      - main
      - feature/**

jobs:
  Build:
    name: "Build"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    env:
      SOLUTION_PATH: ${{ github.workspace }}/src/mississippi.sln
      CONFIGURATION: Release

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache GitVersion tools
        uses: actions/cache@v4
        with:
          path: ~/.gitversion
          key: ${{ runner.os }}-gitversion
          restore-keys: ${{ runner.os }}-gitversion

      - name: Cache nugets
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: "6.0.5"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.1.11
        with:
          useConfigFile: true

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dotnet packages
        run: |
          dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Clean build artifacts
        run: |
          dotnet clean ${{ env.SOLUTION_PATH }} --configuration ${{ env.CONFIGURATION }}

      - name: Build dotnet projects
        run: |
          dotnet build ${{ env.SOLUTION_PATH }} --configuration ${{ env.CONFIGURATION }} --no-restore --no-incremental -warnaserror -p:Version=${{ steps.gitversion.outputs.SemVer }}
